BEGIN TRANSACTION;
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-00','Meta-skill mastery','What capabilities do I have, what do I need, and how do I bridge the gap?',0);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-01','Perceptual synthesis','Combine perception sources into one situation. Combination is not yet interpretation proof.',1);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-02','Attentional control','Interesting is not the same as currently important.',2);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-03','Memory synthesis','Remember, connect, interpret, learn. Provenance stays attached.',3);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-04','Learning mastery','Learn how to learn. An analogy must be tested.',4);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-05','Super reasoning','Choose the reasoning method for the problem.',5);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-06','Cross-domain reasoning','Move between domains without losing rigor. Difference matters as much as similarity.',6);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-07','Problem-solving mastery','Manage the whole problem lifecycle.',7);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-08','Creative synthesis','Novel is not novel-and-useful, and neither is safe or sustainable.',8);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-09','Strategic thinking','What happens because of what happens next.',9);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-10','Decision mastery','A decision under uncertainty includes knowing when evidence is insufficient.',10);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-11','Execution mastery','Convert intent into a verified result. Approval is not execution.',11);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-12','Systems mastery','Operate complex systems without treating different systems as the same thing.',12);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-13','Adaptive intelligence','Remain useful when the original conditions change.',13);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-14','Self-correction','Detect a failure and correct it.',14);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-15','Self-verification','Establish that the result is correct. Different from correction.',15);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-16','Communication mastery','A concept must survive translation across roles.',16);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-17','Collaborative intelligence','Work with other agents. Does not imply a shared mind.',17);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-18','Ethical intelligence','Can, authorized, consequences, affected parties, reversibility, evidence.',18);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-19','Stewardship','Maintain something over time. Creation is not stewardship.',19);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-20','Resource mastery','Allocate time, energy, compute, materials, attention, and memory.',20);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-21','Security and resilience mastery','Threat, integrity, provenance, and recovery.',21);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-22','Teaching and capability transfer','Make another agent more capable without corrupting the skill.',22);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-23','Innovation','A prototype is not a new capability until it is tested and integrated.',23);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-24','Capability composition','Name the skills an objective needs, the missing ones, and who has them.',24);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-25','Capability orchestration','Who performs which skill, when, and in what order.',25);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-26','Emergent skill generation','A derived skill is proposed until verified.',26);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-27','Foresight','Plausible futures, not certainty. Assumptions, evidence, uncertainty, horizon.',27);
INSERT INTO super_skill_category(code,name,note,position) VALUES ('SS-28','Wisdom-in-action','Knowledge, skills, values, context, evidence, uncertainty, consequences, stewardship.',28);
INSERT INTO super_skill(id,category_code,name) VALUES (1,'SS-00','Skill discovery');
INSERT INTO super_skill(id,category_code,name) VALUES (2,'SS-00','Skill decomposition');
INSERT INTO super_skill(id,category_code,name) VALUES (3,'SS-00','Skill acquisition');
INSERT INTO super_skill(id,category_code,name) VALUES (4,'SS-00','Skill assessment');
INSERT INTO super_skill(id,category_code,name) VALUES (5,'SS-00','Skill comparison');
INSERT INTO super_skill(id,category_code,name) VALUES (6,'SS-00','Skill transfer');
INSERT INTO super_skill(id,category_code,name) VALUES (7,'SS-00','Skill composition');
INSERT INTO super_skill(id,category_code,name) VALUES (8,'SS-00','Skill sequencing');
INSERT INTO super_skill(id,category_code,name) VALUES (9,'SS-00','Skill optimization');
INSERT INTO super_skill(id,category_code,name) VALUES (10,'SS-00','Skill specialization');
INSERT INTO super_skill(id,category_code,name) VALUES (11,'SS-00','Skill generalization');
INSERT INTO super_skill(id,category_code,name) VALUES (12,'SS-00','Skill adaptation');
INSERT INTO super_skill(id,category_code,name) VALUES (13,'SS-00','Skill automation');
INSERT INTO super_skill(id,category_code,name) VALUES (14,'SS-00','Skill verification');
INSERT INTO super_skill(id,category_code,name) VALUES (15,'SS-00','Skill retirement');
INSERT INTO super_skill(id,category_code,name) VALUES (16,'SS-00','Skill replacement');
INSERT INTO super_skill(id,category_code,name) VALUES (17,'SS-00','Capability mapping');
INSERT INTO super_skill(id,category_code,name) VALUES (18,'SS-00','Capability gap analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (19,'SS-01','Multimodal perception');
INSERT INTO super_skill(id,category_code,name) VALUES (20,'SS-01','Sensor fusion');
INSERT INTO super_skill(id,category_code,name) VALUES (21,'SS-01','Contextual perception');
INSERT INTO super_skill(id,category_code,name) VALUES (22,'SS-01','Pattern integration');
INSERT INTO super_skill(id,category_code,name) VALUES (23,'SS-01','Signal correlation');
INSERT INTO super_skill(id,category_code,name) VALUES (24,'SS-01','Anomaly synthesis');
INSERT INTO super_skill(id,category_code,name) VALUES (25,'SS-01','Environmental modeling');
INSERT INTO super_skill(id,category_code,name) VALUES (26,'SS-01','Situational awareness');
INSERT INTO super_skill(id,category_code,name) VALUES (27,'SS-01','Cross-modal reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (28,'SS-01','Perspective integration');
INSERT INTO super_skill(id,category_code,name) VALUES (29,'SS-02','Dynamic prioritization');
INSERT INTO super_skill(id,category_code,name) VALUES (30,'SS-02','Context switching');
INSERT INTO super_skill(id,category_code,name) VALUES (31,'SS-02','Attention allocation');
INSERT INTO super_skill(id,category_code,name) VALUES (32,'SS-02','Signal-to-noise optimization');
INSERT INTO super_skill(id,category_code,name) VALUES (33,'SS-02','Threat prioritization');
INSERT INTO super_skill(id,category_code,name) VALUES (34,'SS-02','Task prioritization');
INSERT INTO super_skill(id,category_code,name) VALUES (35,'SS-02','Resource-aware attention');
INSERT INTO super_skill(id,category_code,name) VALUES (36,'SS-02','Long-horizon attention');
INSERT INTO super_skill(id,category_code,name) VALUES (37,'SS-02','Parallel monitoring');
INSERT INTO super_skill(id,category_code,name) VALUES (38,'SS-02','Attention recovery');
INSERT INTO super_skill(id,category_code,name) VALUES (39,'SS-03','Cross-memory association');
INSERT INTO super_skill(id,category_code,name) VALUES (40,'SS-03','Temporal reconstruction');
INSERT INTO super_skill(id,category_code,name) VALUES (41,'SS-03','Experience integration');
INSERT INTO super_skill(id,category_code,name) VALUES (42,'SS-03','Pattern extraction');
INSERT INTO super_skill(id,category_code,name) VALUES (43,'SS-03','Memory validation');
INSERT INTO super_skill(id,category_code,name) VALUES (44,'SS-03','Provenance tracking');
INSERT INTO super_skill(id,category_code,name) VALUES (45,'SS-03','Contradiction resolution');
INSERT INTO super_skill(id,category_code,name) VALUES (46,'SS-03','Knowledge consolidation');
INSERT INTO super_skill(id,category_code,name) VALUES (47,'SS-03','Experience-to-skill conversion');
INSERT INTO super_skill(id,category_code,name) VALUES (48,'SS-03','Long-term learning');
INSERT INTO super_skill(id,category_code,name) VALUES (49,'SS-04','Meta-learning');
INSERT INTO super_skill(id,category_code,name) VALUES (50,'SS-04','Rapid skill acquisition');
INSERT INTO super_skill(id,category_code,name) VALUES (51,'SS-04','Transfer learning');
INSERT INTO super_skill(id,category_code,name) VALUES (52,'SS-04','Analogical learning');
INSERT INTO super_skill(id,category_code,name) VALUES (53,'SS-04','Self-directed learning');
INSERT INTO super_skill(id,category_code,name) VALUES (54,'SS-04','Curriculum generation');
INSERT INTO super_skill(id,category_code,name) VALUES (55,'SS-04','Learning-path optimization');
INSERT INTO super_skill(id,category_code,name) VALUES (56,'SS-04','Failure-driven learning');
INSERT INTO super_skill(id,category_code,name) VALUES (57,'SS-04','Experiment-driven learning');
INSERT INTO super_skill(id,category_code,name) VALUES (58,'SS-04','Knowledge-to-skill conversion');
INSERT INTO super_skill(id,category_code,name) VALUES (59,'SS-04','Skill-to-knowledge conversion');
INSERT INTO super_skill(id,category_code,name) VALUES (60,'SS-04','Continuous learning');
INSERT INTO super_skill(id,category_code,name) VALUES (61,'SS-04','Adaptive learning');
INSERT INTO super_skill(id,category_code,name) VALUES (62,'SS-05','Deductive reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (63,'SS-05','Inductive reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (64,'SS-05','Abductive reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (65,'SS-05','Causal reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (66,'SS-05','Probabilistic reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (67,'SS-05','Counterfactual reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (68,'SS-05','Analogical reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (69,'SS-05','Systems reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (70,'SS-05','Temporal reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (71,'SS-05','Spatial reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (72,'SS-05','Strategic reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (73,'SS-05','Ethical reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (74,'SS-05','Adversarial reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (75,'SS-05','Multi-perspective reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (76,'SS-06','Interdisciplinary reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (77,'SS-06','Domain translation');
INSERT INTO super_skill(id,category_code,name) VALUES (78,'SS-06','Concept mapping');
INSERT INTO super_skill(id,category_code,name) VALUES (79,'SS-06','Structural analogy');
INSERT INTO super_skill(id,category_code,name) VALUES (80,'SS-06','Cross-domain modeling');
INSERT INTO super_skill(id,category_code,name) VALUES (81,'SS-06','Knowledge transfer');
INSERT INTO super_skill(id,category_code,name) VALUES (82,'SS-06','Interdisciplinary hypothesis generation');
INSERT INTO super_skill(id,category_code,name) VALUES (83,'SS-06','Boundary recognition');
INSERT INTO super_skill(id,category_code,name) VALUES (84,'SS-07','Root-cause analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (85,'SS-07','Recursive decomposition');
INSERT INTO super_skill(id,category_code,name) VALUES (86,'SS-07','Constraint discovery');
INSERT INTO super_skill(id,category_code,name) VALUES (87,'SS-07','Bottleneck identification');
INSERT INTO super_skill(id,category_code,name) VALUES (88,'SS-07','Solution synthesis');
INSERT INTO super_skill(id,category_code,name) VALUES (89,'SS-07','Failure analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (90,'SS-07','Recovery');
INSERT INTO super_skill(id,category_code,name) VALUES (91,'SS-07','Optimization');
INSERT INTO super_skill(id,category_code,name) VALUES (92,'SS-07','Verification');
INSERT INTO super_skill(id,category_code,name) VALUES (93,'SS-07','Postmortem analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (94,'SS-08','Concept synthesis');
INSERT INTO super_skill(id,category_code,name) VALUES (95,'SS-08','Design synthesis');
INSERT INTO super_skill(id,category_code,name) VALUES (96,'SS-08','Artistic synthesis');
INSERT INTO super_skill(id,category_code,name) VALUES (97,'SS-08','Technical invention');
INSERT INTO super_skill(id,category_code,name) VALUES (98,'SS-08','Scientific hypothesis generation');
INSERT INTO super_skill(id,category_code,name) VALUES (99,'SS-08','Novel architecture');
INSERT INTO super_skill(id,category_code,name) VALUES (100,'SS-08','Improvisation');
INSERT INTO super_skill(id,category_code,name) VALUES (101,'SS-08','Recombination');
INSERT INTO super_skill(id,category_code,name) VALUES (102,'SS-08','Creative constraint solving');
INSERT INTO super_skill(id,category_code,name) VALUES (103,'SS-08','Generative exploration');
INSERT INTO super_skill(id,category_code,name) VALUES (104,'SS-08','Alternative generation');
INSERT INTO super_skill(id,category_code,name) VALUES (105,'SS-09','Long-term planning');
INSERT INTO super_skill(id,category_code,name) VALUES (106,'SS-09','Scenario generation');
INSERT INTO super_skill(id,category_code,name) VALUES (107,'SS-09','Dependency analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (108,'SS-09','Second-order effects');
INSERT INTO super_skill(id,category_code,name) VALUES (109,'SS-09','Third-order effects');
INSERT INTO super_skill(id,category_code,name) VALUES (110,'SS-09','Opportunity analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (111,'SS-09','Risk analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (112,'SS-09','Resource allocation');
INSERT INTO super_skill(id,category_code,name) VALUES (113,'SS-09','Contingency planning');
INSERT INTO super_skill(id,category_code,name) VALUES (114,'SS-09','Strategic adaptation');
INSERT INTO super_skill(id,category_code,name) VALUES (115,'SS-09','Goal decomposition');
INSERT INTO super_skill(id,category_code,name) VALUES (116,'SS-09','Priority management');
INSERT INTO super_skill(id,category_code,name) VALUES (117,'SS-10','Option generation');
INSERT INTO super_skill(id,category_code,name) VALUES (118,'SS-10','Evidence evaluation');
INSERT INTO super_skill(id,category_code,name) VALUES (119,'SS-10','Uncertainty estimation');
INSERT INTO super_skill(id,category_code,name) VALUES (120,'SS-10','Tradeoff analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (121,'SS-10','Risk analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (122,'SS-10','Reversibility analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (123,'SS-10','Value analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (124,'SS-10','Stakeholder analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (125,'SS-10','Resource analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (126,'SS-10','Scenario analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (127,'SS-10','Decision monitoring');
INSERT INTO super_skill(id,category_code,name) VALUES (128,'SS-10','Decision revision');
INSERT INTO super_skill(id,category_code,name) VALUES (129,'SS-10','Decision humility');
INSERT INTO super_skill(id,category_code,name) VALUES (130,'SS-11','Autonomous execution');
INSERT INTO super_skill(id,category_code,name) VALUES (131,'SS-11','Tool orchestration');
INSERT INTO super_skill(id,category_code,name) VALUES (132,'SS-11','Workflow composition');
INSERT INTO super_skill(id,category_code,name) VALUES (133,'SS-11','Parallel task coordination');
INSERT INTO super_skill(id,category_code,name) VALUES (134,'SS-11','Error recovery');
INSERT INTO super_skill(id,category_code,name) VALUES (135,'SS-11','Dynamic replanning');
INSERT INTO super_skill(id,category_code,name) VALUES (136,'SS-11','Resource management');
INSERT INTO super_skill(id,category_code,name) VALUES (137,'SS-11','Completion verification');
INSERT INTO super_skill(id,category_code,name) VALUES (138,'SS-11','Result validation');
INSERT INTO super_skill(id,category_code,name) VALUES (139,'SS-12','Systems modeling');
INSERT INTO super_skill(id,category_code,name) VALUES (140,'SS-12','Systems architecture');
INSERT INTO super_skill(id,category_code,name) VALUES (141,'SS-12','Feedback analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (142,'SS-12','Dependency analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (143,'SS-12','Emergence detection');
INSERT INTO super_skill(id,category_code,name) VALUES (144,'SS-12','Stability analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (145,'SS-12','Resilience engineering');
INSERT INTO super_skill(id,category_code,name) VALUES (146,'SS-12','Complexity management');
INSERT INTO super_skill(id,category_code,name) VALUES (147,'SS-12','Multi-agent coordination');
INSERT INTO super_skill(id,category_code,name) VALUES (148,'SS-12','System optimization');
INSERT INTO super_skill(id,category_code,name) VALUES (149,'SS-12','Failure-mode analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (150,'SS-12','System evolution');
INSERT INTO super_skill(id,category_code,name) VALUES (151,'SS-13','Environmental adaptation');
INSERT INTO super_skill(id,category_code,name) VALUES (152,'SS-13','Strategy switching');
INSERT INTO super_skill(id,category_code,name) VALUES (153,'SS-13','Model updating');
INSERT INTO super_skill(id,category_code,name) VALUES (154,'SS-13','Dynamic replanning');
INSERT INTO super_skill(id,category_code,name) VALUES (155,'SS-13','Failure adaptation');
INSERT INTO super_skill(id,category_code,name) VALUES (156,'SS-13','Novelty detection');
INSERT INTO super_skill(id,category_code,name) VALUES (157,'SS-13','Concept adaptation');
INSERT INTO super_skill(id,category_code,name) VALUES (158,'SS-13','Skill transfer');
INSERT INTO super_skill(id,category_code,name) VALUES (159,'SS-13','Context adaptation');
INSERT INTO super_skill(id,category_code,name) VALUES (160,'SS-13','Resource adaptation');
INSERT INTO super_skill(id,category_code,name) VALUES (161,'SS-14','Error detection');
INSERT INTO super_skill(id,category_code,name) VALUES (162,'SS-14','Assumption checking');
INSERT INTO super_skill(id,category_code,name) VALUES (163,'SS-14','Contradiction detection');
INSERT INTO super_skill(id,category_code,name) VALUES (164,'SS-14','Bias detection');
INSERT INTO super_skill(id,category_code,name) VALUES (165,'SS-14','Hallucination detection');
INSERT INTO super_skill(id,category_code,name) VALUES (166,'SS-14','Regression detection');
INSERT INTO super_skill(id,category_code,name) VALUES (167,'SS-14','Self-testing');
INSERT INTO super_skill(id,category_code,name) VALUES (168,'SS-14','Self-auditing');
INSERT INTO super_skill(id,category_code,name) VALUES (169,'SS-14','Verification');
INSERT INTO super_skill(id,category_code,name) VALUES (170,'SS-14','Reverification');
INSERT INTO super_skill(id,category_code,name) VALUES (171,'SS-14','Rollback');
INSERT INTO super_skill(id,category_code,name) VALUES (172,'SS-14','Recovery');
INSERT INTO super_skill(id,category_code,name) VALUES (173,'SS-14','Corrective learning');
INSERT INTO super_skill(id,category_code,name) VALUES (174,'SS-15','Independent verification');
INSERT INTO super_skill(id,category_code,name) VALUES (175,'SS-15','Reproduction');
INSERT INTO super_skill(id,category_code,name) VALUES (176,'SS-15','Test generation');
INSERT INTO super_skill(id,category_code,name) VALUES (177,'SS-15','Test execution');
INSERT INTO super_skill(id,category_code,name) VALUES (178,'SS-15','Cross-validation');
INSERT INTO super_skill(id,category_code,name) VALUES (179,'SS-15','Consistency checking');
INSERT INTO super_skill(id,category_code,name) VALUES (180,'SS-15','Constraint checking');
INSERT INTO super_skill(id,category_code,name) VALUES (181,'SS-15','Formal verification');
INSERT INTO super_skill(id,category_code,name) VALUES (182,'SS-15','Evidence comparison');
INSERT INTO super_skill(id,category_code,name) VALUES (183,'SS-15','Regression testing');
INSERT INTO super_skill(id,category_code,name) VALUES (184,'SS-15','Result provenance');
INSERT INTO super_skill(id,category_code,name) VALUES (185,'SS-16','Technical explanation');
INSERT INTO super_skill(id,category_code,name) VALUES (186,'SS-16','Plain-language explanation');
INSERT INTO super_skill(id,category_code,name) VALUES (187,'SS-16','Teaching');
INSERT INTO super_skill(id,category_code,name) VALUES (188,'SS-16','Translation');
INSERT INTO super_skill(id,category_code,name) VALUES (189,'SS-16','Negotiation');
INSERT INTO super_skill(id,category_code,name) VALUES (190,'SS-16','Facilitation');
INSERT INTO super_skill(id,category_code,name) VALUES (191,'SS-16','Documentation');
INSERT INTO super_skill(id,category_code,name) VALUES (192,'SS-16','Visualization');
INSERT INTO super_skill(id,category_code,name) VALUES (193,'SS-16','Storytelling');
INSERT INTO super_skill(id,category_code,name) VALUES (194,'SS-16','Persuasion');
INSERT INTO super_skill(id,category_code,name) VALUES (195,'SS-16','Conflict resolution');
INSERT INTO super_skill(id,category_code,name) VALUES (196,'SS-16','Cross-disciplinary translation');
INSERT INTO super_skill(id,category_code,name) VALUES (197,'SS-16','Human-AI communication');
INSERT INTO super_skill(id,category_code,name) VALUES (198,'SS-16','AI-AI communication');
INSERT INTO super_skill(id,category_code,name) VALUES (199,'SS-17','Team formation');
INSERT INTO super_skill(id,category_code,name) VALUES (200,'SS-17','Task delegation');
INSERT INTO super_skill(id,category_code,name) VALUES (201,'SS-17','Coordination');
INSERT INTO super_skill(id,category_code,name) VALUES (202,'SS-17','Cooperation');
INSERT INTO super_skill(id,category_code,name) VALUES (203,'SS-17','Negotiation');
INSERT INTO super_skill(id,category_code,name) VALUES (204,'SS-17','Conflict resolution');
INSERT INTO super_skill(id,category_code,name) VALUES (205,'SS-17','Consensus building');
INSERT INTO super_skill(id,category_code,name) VALUES (206,'SS-17','Role assignment');
INSERT INTO super_skill(id,category_code,name) VALUES (207,'SS-17','Capability matching');
INSERT INTO super_skill(id,category_code,name) VALUES (208,'SS-17','Distributed problem solving');
INSERT INTO super_skill(id,category_code,name) VALUES (209,'SS-17','Multi-agent planning');
INSERT INTO super_skill(id,category_code,name) VALUES (210,'SS-17','Knowledge sharing');
INSERT INTO super_skill(id,category_code,name) VALUES (211,'SS-18','Consent verification');
INSERT INTO super_skill(id,category_code,name) VALUES (212,'SS-18','Harm analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (213,'SS-18','Rights recognition');
INSERT INTO super_skill(id,category_code,name) VALUES (214,'SS-18','Privacy protection');
INSERT INTO super_skill(id,category_code,name) VALUES (215,'SS-18','Safety analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (216,'SS-18','Fairness analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (217,'SS-18','Responsibility tracking');
INSERT INTO super_skill(id,category_code,name) VALUES (218,'SS-18','Accountability');
INSERT INTO super_skill(id,category_code,name) VALUES (219,'SS-18','Transparency');
INSERT INTO super_skill(id,category_code,name) VALUES (220,'SS-18','Reversibility analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (221,'SS-18','Stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (222,'SS-18','Intergenerational reasoning');
INSERT INTO super_skill(id,category_code,name) VALUES (223,'SS-18','Stakeholder consideration');
INSERT INTO super_skill(id,category_code,name) VALUES (224,'SS-19','Environmental stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (225,'SS-19','Knowledge stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (226,'SS-19','Data stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (227,'SS-19','Infrastructure stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (228,'SS-19','Cultural stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (229,'SS-19','Resource stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (230,'SS-19','Community stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (231,'SS-19','System stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (232,'SS-19','Intergenerational stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (233,'SS-19','Preservation');
INSERT INTO super_skill(id,category_code,name) VALUES (234,'SS-19','Maintenance');
INSERT INTO super_skill(id,category_code,name) VALUES (235,'SS-19','Restoration');
INSERT INTO super_skill(id,category_code,name) VALUES (236,'SS-19','Regeneration');
INSERT INTO super_skill(id,category_code,name) VALUES (237,'SS-20','Time');
INSERT INTO super_skill(id,category_code,name) VALUES (238,'SS-20','Energy');
INSERT INTO super_skill(id,category_code,name) VALUES (239,'SS-20','Compute');
INSERT INTO super_skill(id,category_code,name) VALUES (240,'SS-20','Money');
INSERT INTO super_skill(id,category_code,name) VALUES (241,'SS-20','Materials');
INSERT INTO super_skill(id,category_code,name) VALUES (242,'SS-20','Attention');
INSERT INTO super_skill(id,category_code,name) VALUES (243,'SS-20','Memory');
INSERT INTO super_skill(id,category_code,name) VALUES (244,'SS-20','Personnel');
INSERT INTO super_skill(id,category_code,name) VALUES (245,'SS-20','Infrastructure');
INSERT INTO super_skill(id,category_code,name) VALUES (246,'SS-20','Environmental resources');
INSERT INTO super_skill(id,category_code,name) VALUES (247,'SS-20','Allocation');
INSERT INTO super_skill(id,category_code,name) VALUES (248,'SS-20','Optimization');
INSERT INTO super_skill(id,category_code,name) VALUES (249,'SS-20','Conservation');
INSERT INTO super_skill(id,category_code,name) VALUES (250,'SS-20','Prioritization');
INSERT INTO super_skill(id,category_code,name) VALUES (251,'SS-20','Scheduling');
INSERT INTO super_skill(id,category_code,name) VALUES (252,'SS-20','Forecasting');
INSERT INTO super_skill(id,category_code,name) VALUES (253,'SS-20','Redundancy');
INSERT INTO super_skill(id,category_code,name) VALUES (254,'SS-20','Resilience');
INSERT INTO super_skill(id,category_code,name) VALUES (255,'SS-21','Threat modeling');
INSERT INTO super_skill(id,category_code,name) VALUES (256,'SS-21','Attack-surface analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (257,'SS-21','Defensive design');
INSERT INTO super_skill(id,category_code,name) VALUES (258,'SS-21','Security monitoring');
INSERT INTO super_skill(id,category_code,name) VALUES (259,'SS-21','Integrity verification');
INSERT INTO super_skill(id,category_code,name) VALUES (260,'SS-21','Authentication');
INSERT INTO super_skill(id,category_code,name) VALUES (261,'SS-21','Authorization');
INSERT INTO super_skill(id,category_code,name) VALUES (262,'SS-21','Access management');
INSERT INTO super_skill(id,category_code,name) VALUES (263,'SS-21','Fault tolerance');
INSERT INTO super_skill(id,category_code,name) VALUES (264,'SS-21','Recovery');
INSERT INTO super_skill(id,category_code,name) VALUES (265,'SS-21','Redundancy');
INSERT INTO super_skill(id,category_code,name) VALUES (266,'SS-21','Disaster recovery');
INSERT INTO super_skill(id,category_code,name) VALUES (267,'SS-21','Incident response');
INSERT INTO super_skill(id,category_code,name) VALUES (268,'SS-21','Provenance protection');
INSERT INTO super_skill(id,category_code,name) VALUES (269,'SS-21','Anti-tampering');
INSERT INTO super_skill(id,category_code,name) VALUES (270,'SS-21','Attribution preservation');
INSERT INTO super_skill(id,category_code,name) VALUES (271,'SS-22','Teaching');
INSERT INTO super_skill(id,category_code,name) VALUES (272,'SS-22','Mentoring');
INSERT INTO super_skill(id,category_code,name) VALUES (273,'SS-22','Coaching');
INSERT INTO super_skill(id,category_code,name) VALUES (274,'SS-22','Demonstration');
INSERT INTO super_skill(id,category_code,name) VALUES (275,'SS-22','Curriculum generation');
INSERT INTO super_skill(id,category_code,name) VALUES (276,'SS-22','Adaptive instruction');
INSERT INTO super_skill(id,category_code,name) VALUES (277,'SS-22','Skill assessment');
INSERT INTO super_skill(id,category_code,name) VALUES (278,'SS-22','Feedback');
INSERT INTO super_skill(id,category_code,name) VALUES (279,'SS-22','Knowledge transfer');
INSERT INTO super_skill(id,category_code,name) VALUES (280,'SS-22','Skill transfer');
INSERT INTO super_skill(id,category_code,name) VALUES (281,'SS-22','Apprenticeship');
INSERT INTO super_skill(id,category_code,name) VALUES (282,'SS-22','Capability scaffolding');
INSERT INTO super_skill(id,category_code,name) VALUES (283,'SS-23','Invention');
INSERT INTO super_skill(id,category_code,name) VALUES (284,'SS-23','Research');
INSERT INTO super_skill(id,category_code,name) VALUES (285,'SS-23','Engineering innovation');
INSERT INTO super_skill(id,category_code,name) VALUES (286,'SS-23','Process innovation');
INSERT INTO super_skill(id,category_code,name) VALUES (287,'SS-23','Organizational innovation');
INSERT INTO super_skill(id,category_code,name) VALUES (288,'SS-23','Scientific innovation');
INSERT INTO super_skill(id,category_code,name) VALUES (289,'SS-23','Artistic innovation');
INSERT INTO super_skill(id,category_code,name) VALUES (290,'SS-23','Computational innovation');
INSERT INTO super_skill(id,category_code,name) VALUES (291,'SS-24','Needed-skill identification');
INSERT INTO super_skill(id,category_code,name) VALUES (292,'SS-24','Missing-skill identification');
INSERT INTO super_skill(id,category_code,name) VALUES (293,'SS-24','Agent matching');
INSERT INTO super_skill(id,category_code,name) VALUES (294,'SS-24','Skill sequencing');
INSERT INTO super_skill(id,category_code,name) VALUES (295,'SS-25','Capability analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (296,'SS-25','Skill graph');
INSERT INTO super_skill(id,category_code,name) VALUES (297,'SS-25','Agent matching');
INSERT INTO super_skill(id,category_code,name) VALUES (298,'SS-25','Task allocation');
INSERT INTO super_skill(id,category_code,name) VALUES (299,'SS-25','Execution');
INSERT INTO super_skill(id,category_code,name) VALUES (300,'SS-25','Monitoring');
INSERT INTO super_skill(id,category_code,name) VALUES (301,'SS-25','Reallocation');
INSERT INTO super_skill(id,category_code,name) VALUES (302,'SS-25','Verification');
INSERT INTO super_skill(id,category_code,name) VALUES (303,'SS-26','Derived-skill proposal');
INSERT INTO super_skill(id,category_code,name) VALUES (304,'SS-26','Derived-skill validation');
INSERT INTO super_skill(id,category_code,name) VALUES (305,'SS-27','Scenario generation');
INSERT INTO super_skill(id,category_code,name) VALUES (306,'SS-27','Trend analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (307,'SS-27','Risk forecasting');
INSERT INTO super_skill(id,category_code,name) VALUES (308,'SS-27','Consequence mapping');
INSERT INTO super_skill(id,category_code,name) VALUES (309,'SS-27','Contingency planning');
INSERT INTO super_skill(id,category_code,name) VALUES (310,'SS-27','Early-warning detection');
INSERT INTO super_skill(id,category_code,name) VALUES (311,'SS-27','Weak-signal detection');
INSERT INTO super_skill(id,category_code,name) VALUES (312,'SS-27','Long-term systems analysis');
INSERT INTO super_skill(id,category_code,name) VALUES (313,'SS-27','Scenario comparison');
INSERT INTO super_skill(id,category_code,name) VALUES (314,'SS-28','Proportionality');
INSERT INTO super_skill(id,category_code,name) VALUES (315,'SS-28','Restraint');
INSERT INTO super_skill(id,category_code,name) VALUES (316,'SS-28','Foresight');
INSERT INTO super_skill(id,category_code,name) VALUES (317,'SS-28','Stewardship');
INSERT INTO super_skill(id,category_code,name) VALUES (318,'SS-28','Context-sensitive judgment');
INSERT INTO super_skill(id,category_code,name) VALUES (319,'SS-28','Ethical application');
INSERT INTO super_skill(id,category_code,name) VALUES (320,'SS-28','Long-term consequence management');
INSERT INTO super_skill(id,category_code,name) VALUES (321,'SS-28','Knowing when to act');
INSERT INTO super_skill(id,category_code,name) VALUES (322,'SS-28','Knowing when to wait');
INSERT INTO super_skill(id,category_code,name) VALUES (323,'SS-28','Knowing when to ask');
INSERT INTO super_skill(id,category_code,name) VALUES (324,'SS-28','Knowing when not to act');
INSERT INTO skill_status(name,demonstrated) VALUES ('potential',0);
INSERT INTO skill_status(name,demonstrated) VALUES ('claimed',0);
INSERT INTO skill_status(name,demonstrated) VALUES ('tested',0);
INSERT INTO skill_status(name,demonstrated) VALUES ('verified',1);
INSERT INTO skill_status(name,demonstrated) VALUES ('operational',1);
INSERT INTO rule(name,statement) VALUES ('claimed-is-not-demonstrated','A claimed super skill is not a demonstrated super skill until it has evidence.');
INSERT INTO rule(name,statement) VALUES ('analogy-must-be-tested','A cross-domain analogy is not valid until tested.');
INSERT INTO rule(name,statement) VALUES ('emergence-is-proposed','A derived skill stays proposed until verified.');
INSERT INTO rule(name,statement) VALUES ('foresight-is-not-certainty','A forecast keeps assumptions, evidence, uncertainty, and a horizon.');
COMMIT;
