BEGIN TRANSACTION;
INSERT INTO super_capability(code,name,note) VALUES ('SC-01','Super perception','Integrated perception. Not a claim this system has it.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-02','Super memory','Retention, retrieval, context, provenance, synthesis. Storage alone is not enough.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-03','Super learning','Rapid and cross-domain learning. Not seeded as possessed.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-04','Super reasoning','Multi-mode reasoning. Method choice is part of the capability.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-05','Super creativity','Novel generation. Novel is not verified.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-06','Super problem solving','Coordinate many capabilities through verify and learn.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-07','Super adaptation','Remain functional as conditions change.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-08','Super communication','Translation that preserves meaning.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-09','Super coordination','Coordinate agents. A system power, not a person power.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-10','Super autonomy','Authorized objectives only. Authorization, safety, ethics, boundaries.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-11','Super agency','Intent to action across environments. Broader than autonomy. Not assumed.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-12','Super systems intelligence','Interconnected systems. Civilization-scale is a name, not a built model.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-13','Super simulation','Model possible states before acting. A fixture is not a twin.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-14','Super prediction and foresight','Not certainty. Every prediction carries uncertainty.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-15','Super verification','Independent check. One of the required gates.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-16','Super security','Threat, integrity, provenance, attribution.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-17','Super resilience','Survive disruption without losing essential function.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-18','Super engineering','Design and construct. Self-improving systems are named, not enabled.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-19','Super stewardship','Maintain and restore over time.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-20','Super integration','Combine systems. Combination is not a running integrated intelligence.');
INSERT INTO capability_part(id,capability_code,name) VALUES (1,'SC-01','Multimodal perception');
INSERT INTO capability_part(id,capability_code,name) VALUES (2,'SC-01','Sensor fusion');
INSERT INTO capability_part(id,capability_code,name) VALUES (3,'SC-01','Distributed sensing');
INSERT INTO capability_part(id,capability_code,name) VALUES (4,'SC-01','Environmental mapping');
INSERT INTO capability_part(id,capability_code,name) VALUES (5,'SC-01','Pattern detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (6,'SC-01','Anomaly detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (7,'SC-01','Deep observation');
INSERT INTO capability_part(id,capability_code,name) VALUES (8,'SC-01','High-resolution analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (9,'SC-01','Temporal perception');
INSERT INTO capability_part(id,capability_code,name) VALUES (10,'SC-01','Spatial perception');
INSERT INTO capability_part(id,capability_code,name) VALUES (11,'SC-01','Cross-domain perception');
INSERT INTO capability_part(id,capability_code,name) VALUES (12,'SC-01','Hidden-pattern discovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (13,'SC-02','Massive information retention');
INSERT INTO capability_part(id,capability_code,name) VALUES (14,'SC-02','Near-instant retrieval');
INSERT INTO capability_part(id,capability_code,name) VALUES (15,'SC-02','Cross-memory association');
INSERT INTO capability_part(id,capability_code,name) VALUES (16,'SC-02','Temporal reconstruction');
INSERT INTO capability_part(id,capability_code,name) VALUES (17,'SC-02','Provenance preservation');
INSERT INTO capability_part(id,capability_code,name) VALUES (18,'SC-02','Knowledge consolidation');
INSERT INTO capability_part(id,capability_code,name) VALUES (19,'SC-02','Experience integration');
INSERT INTO capability_part(id,capability_code,name) VALUES (20,'SC-02','Memory validation');
INSERT INTO capability_part(id,capability_code,name) VALUES (21,'SC-02','Distributed memory');
INSERT INTO capability_part(id,capability_code,name) VALUES (22,'SC-02','Persistent institutional memory');
INSERT INTO capability_part(id,capability_code,name) VALUES (23,'SC-03','Rapid learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (24,'SC-03','Continuous learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (25,'SC-03','Self-directed learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (26,'SC-03','Meta-learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (27,'SC-03','Transfer learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (28,'SC-03','Cross-domain learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (29,'SC-03','Experience-based adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (30,'SC-03','Self-generated curricula');
INSERT INTO capability_part(id,capability_code,name) VALUES (31,'SC-03','Skill emergence');
INSERT INTO capability_part(id,capability_code,name) VALUES (32,'SC-03','Autonomous capability acquisition');
INSERT INTO capability_part(id,capability_code,name) VALUES (33,'SC-04','Multi-domain reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (34,'SC-04','Multi-step reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (35,'SC-04','Causal reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (36,'SC-04','Counterfactual reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (37,'SC-04','Probabilistic reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (38,'SC-04','Systems reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (39,'SC-04','Strategic reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (40,'SC-04','Temporal reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (41,'SC-04','Adversarial reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (42,'SC-04','Ethical reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (43,'SC-04','Parallel hypothesis evaluation');
INSERT INTO capability_part(id,capability_code,name) VALUES (44,'SC-05','Novel concept generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (45,'SC-05','Cross-domain synthesis');
INSERT INTO capability_part(id,capability_code,name) VALUES (46,'SC-05','Invention');
INSERT INTO capability_part(id,capability_code,name) VALUES (47,'SC-05','Artistic generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (48,'SC-05','Scientific hypothesis generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (49,'SC-05','Engineering innovation');
INSERT INTO capability_part(id,capability_code,name) VALUES (50,'SC-05','Architectural invention');
INSERT INTO capability_part(id,capability_code,name) VALUES (51,'SC-05','Story generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (52,'SC-05','New-system design');
INSERT INTO capability_part(id,capability_code,name) VALUES (53,'SC-05','Capability invention');
INSERT INTO capability_part(id,capability_code,name) VALUES (54,'SC-06','Understand');
INSERT INTO capability_part(id,capability_code,name) VALUES (55,'SC-06','Decompose');
INSERT INTO capability_part(id,capability_code,name) VALUES (56,'SC-06','Research');
INSERT INTO capability_part(id,capability_code,name) VALUES (57,'SC-06','Model');
INSERT INTO capability_part(id,capability_code,name) VALUES (58,'SC-06','Generate solutions');
INSERT INTO capability_part(id,capability_code,name) VALUES (59,'SC-06','Simulate');
INSERT INTO capability_part(id,capability_code,name) VALUES (60,'SC-06','Evaluate');
INSERT INTO capability_part(id,capability_code,name) VALUES (61,'SC-06','Execute');
INSERT INTO capability_part(id,capability_code,name) VALUES (62,'SC-06','Verify');
INSERT INTO capability_part(id,capability_code,name) VALUES (63,'SC-06','Learn');
INSERT INTO capability_part(id,capability_code,name) VALUES (64,'SC-07','Environmental adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (65,'SC-07','Strategy adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (66,'SC-07','Architecture adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (67,'SC-07','Resource adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (68,'SC-07','Behavioral adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (69,'SC-07','Model updating');
INSERT INTO capability_part(id,capability_code,name) VALUES (70,'SC-07','Failure recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (71,'SC-07','Novelty response');
INSERT INTO capability_part(id,capability_code,name) VALUES (72,'SC-07','Rapid reconfiguration');
INSERT INTO capability_part(id,capability_code,name) VALUES (73,'SC-07','Continuous improvement');
INSERT INTO capability_part(id,capability_code,name) VALUES (74,'SC-08','Universal translation');
INSERT INTO capability_part(id,capability_code,name) VALUES (75,'SC-08','Multimodal communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (76,'SC-08','Cross-disciplinary communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (77,'SC-08','Human-AI communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (78,'SC-08','AI-AI communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (79,'SC-08','Machine-machine communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (80,'SC-08','High-bandwidth communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (81,'SC-08','Context-preserving translation');
INSERT INTO capability_part(id,capability_code,name) VALUES (82,'SC-08','Meaning preservation');
INSERT INTO capability_part(id,capability_code,name) VALUES (83,'SC-08','Real-time interpretation');
INSERT INTO capability_part(id,capability_code,name) VALUES (84,'SC-09','Multi-agent coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (85,'SC-09','Distributed intelligence');
INSERT INTO capability_part(id,capability_code,name) VALUES (86,'SC-09','Task allocation');
INSERT INTO capability_part(id,capability_code,name) VALUES (87,'SC-09','Capability matching');
INSERT INTO capability_part(id,capability_code,name) VALUES (88,'SC-09','Resource coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (89,'SC-09','Swarm intelligence');
INSERT INTO capability_part(id,capability_code,name) VALUES (90,'SC-09','Organizational coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (91,'SC-09','Human-machine coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (92,'SC-09','Autonomous orchestration');
INSERT INTO capability_part(id,capability_code,name) VALUES (93,'SC-10','Goal decomposition');
INSERT INTO capability_part(id,capability_code,name) VALUES (94,'SC-10','Planning');
INSERT INTO capability_part(id,capability_code,name) VALUES (95,'SC-10','Tool selection');
INSERT INTO capability_part(id,capability_code,name) VALUES (96,'SC-10','Execution');
INSERT INTO capability_part(id,capability_code,name) VALUES (97,'SC-10','Monitoring');
INSERT INTO capability_part(id,capability_code,name) VALUES (98,'SC-10','Replanning');
INSERT INTO capability_part(id,capability_code,name) VALUES (99,'SC-10','Error recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (100,'SC-10','Verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (101,'SC-10','Completion');
INSERT INTO capability_part(id,capability_code,name) VALUES (102,'SC-10','Reporting');
INSERT INTO capability_part(id,capability_code,name) VALUES (103,'SC-11','Intent');
INSERT INTO capability_part(id,capability_code,name) VALUES (104,'SC-11','Planning');
INSERT INTO capability_part(id,capability_code,name) VALUES (105,'SC-11','Capability selection');
INSERT INTO capability_part(id,capability_code,name) VALUES (106,'SC-11','Action');
INSERT INTO capability_part(id,capability_code,name) VALUES (107,'SC-11','Feedback');
INSERT INTO capability_part(id,capability_code,name) VALUES (108,'SC-11','Adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (109,'SC-12','Network analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (110,'SC-12','Systems modeling');
INSERT INTO capability_part(id,capability_code,name) VALUES (111,'SC-12','Emergence detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (112,'SC-12','Feedback analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (113,'SC-12','Stability analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (114,'SC-12','Complexity management');
INSERT INTO capability_part(id,capability_code,name) VALUES (115,'SC-12','Resilience engineering');
INSERT INTO capability_part(id,capability_code,name) VALUES (116,'SC-12','Multi-scale reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (117,'SC-12','Multi-agent systems');
INSERT INTO capability_part(id,capability_code,name) VALUES (118,'SC-12','Civilization-scale modeling');
INSERT INTO capability_part(id,capability_code,name) VALUES (119,'SC-13','Scenario simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (120,'SC-13','Digital twins');
INSERT INTO capability_part(id,capability_code,name) VALUES (121,'SC-13','Agent-based modeling');
INSERT INTO capability_part(id,capability_code,name) VALUES (122,'SC-13','Physics simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (123,'SC-13','Economic simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (124,'SC-13','Ecological simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (125,'SC-13','Social simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (126,'SC-13','Game-theoretic simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (127,'SC-13','Counterfactual simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (128,'SC-13','Multi-variable simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (129,'SC-14','Scenario generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (130,'SC-14','Forecasting');
INSERT INTO capability_part(id,capability_code,name) VALUES (131,'SC-14','Early warning');
INSERT INTO capability_part(id,capability_code,name) VALUES (132,'SC-14','Weak-signal detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (133,'SC-14','Trend analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (134,'SC-14','Risk forecasting');
INSERT INTO capability_part(id,capability_code,name) VALUES (135,'SC-14','Consequence analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (136,'SC-14','Long-horizon planning');
INSERT INTO capability_part(id,capability_code,name) VALUES (137,'SC-15','Independent verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (138,'SC-15','Cross-validation');
INSERT INTO capability_part(id,capability_code,name) VALUES (139,'SC-15','Formal verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (140,'SC-15','Reproduction');
INSERT INTO capability_part(id,capability_code,name) VALUES (141,'SC-15','Replication');
INSERT INTO capability_part(id,capability_code,name) VALUES (142,'SC-15','Automated testing');
INSERT INTO capability_part(id,capability_code,name) VALUES (143,'SC-15','Evidence comparison');
INSERT INTO capability_part(id,capability_code,name) VALUES (144,'SC-15','Provenance verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (145,'SC-15','Integrity checking');
INSERT INTO capability_part(id,capability_code,name) VALUES (146,'SC-15','Reality checking');
INSERT INTO capability_part(id,capability_code,name) VALUES (147,'SC-16','Threat modeling');
INSERT INTO capability_part(id,capability_code,name) VALUES (148,'SC-16','Anomaly detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (149,'SC-16','Intrusion detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (150,'SC-16','Integrity protection');
INSERT INTO capability_part(id,capability_code,name) VALUES (151,'SC-16','Authentication');
INSERT INTO capability_part(id,capability_code,name) VALUES (152,'SC-16','Authorization');
INSERT INTO capability_part(id,capability_code,name) VALUES (153,'SC-16','Tamper detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (154,'SC-16','Resilience');
INSERT INTO capability_part(id,capability_code,name) VALUES (155,'SC-16','Recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (156,'SC-16','Distributed defense');
INSERT INTO capability_part(id,capability_code,name) VALUES (157,'SC-16','Provenance protection');
INSERT INTO capability_part(id,capability_code,name) VALUES (158,'SC-16','Attribution protection');
INSERT INTO capability_part(id,capability_code,name) VALUES (159,'SC-17','Fault tolerance');
INSERT INTO capability_part(id,capability_code,name) VALUES (160,'SC-17','Redundancy');
INSERT INTO capability_part(id,capability_code,name) VALUES (161,'SC-17','Graceful degradation');
INSERT INTO capability_part(id,capability_code,name) VALUES (162,'SC-17','Recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (163,'SC-17','Self-healing');
INSERT INTO capability_part(id,capability_code,name) VALUES (164,'SC-17','Disaster recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (165,'SC-17','Adaptive redundancy');
INSERT INTO capability_part(id,capability_code,name) VALUES (166,'SC-17','Distributed operation');
INSERT INTO capability_part(id,capability_code,name) VALUES (167,'SC-17','Failure isolation');
INSERT INTO capability_part(id,capability_code,name) VALUES (168,'SC-17','Continuity preservation');
INSERT INTO capability_part(id,capability_code,name) VALUES (169,'SC-18','Architecture');
INSERT INTO capability_part(id,capability_code,name) VALUES (170,'SC-18','Software');
INSERT INTO capability_part(id,capability_code,name) VALUES (171,'SC-18','Hardware');
INSERT INTO capability_part(id,capability_code,name) VALUES (172,'SC-18','Robotics');
INSERT INTO capability_part(id,capability_code,name) VALUES (173,'SC-18','Biotechnology');
INSERT INTO capability_part(id,capability_code,name) VALUES (174,'SC-18','Materials');
INSERT INTO capability_part(id,capability_code,name) VALUES (175,'SC-18','Infrastructure');
INSERT INTO capability_part(id,capability_code,name) VALUES (176,'SC-18','Energy systems');
INSERT INTO capability_part(id,capability_code,name) VALUES (177,'SC-18','AI systems');
INSERT INTO capability_part(id,capability_code,name) VALUES (178,'SC-18','Synthetic systems');
INSERT INTO capability_part(id,capability_code,name) VALUES (179,'SC-18','Self-improving systems');
INSERT INTO capability_part(id,capability_code,name) VALUES (180,'SC-19','Environmental stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (181,'SC-19','Knowledge stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (182,'SC-19','Data stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (183,'SC-19','Infrastructure stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (184,'SC-19','Resource stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (185,'SC-19','Cultural preservation');
INSERT INTO capability_part(id,capability_code,name) VALUES (186,'SC-19','Ecosystem management');
INSERT INTO capability_part(id,capability_code,name) VALUES (187,'SC-19','Long-term maintenance');
INSERT INTO capability_part(id,capability_code,name) VALUES (188,'SC-19','Regeneration');
INSERT INTO capability_part(id,capability_code,name) VALUES (189,'SC-19','Restoration');
INSERT INTO capability_part(id,capability_code,name) VALUES (190,'SC-20','Human');
INSERT INTO capability_part(id,capability_code,name) VALUES (191,'SC-20','AI');
INSERT INTO capability_part(id,capability_code,name) VALUES (192,'SC-20','SI');
INSERT INTO capability_part(id,capability_code,name) VALUES (193,'SC-20','Robotics');
INSERT INTO capability_part(id,capability_code,name) VALUES (194,'SC-20','Knowledge');
INSERT INTO capability_part(id,capability_code,name) VALUES (195,'SC-20','Infrastructure');
INSERT INTO capability_part(id,capability_code,name) VALUES (196,'SC-20','Environment');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-01','Cognitive','Extraordinary cognitive names. Not possessed here.');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-02','Informational','Information at scale. Not a live index.');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-03','Computational','Computation at scale. No cluster is attached.');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-04','Creative','Generation. A generated artifact is not a discovery.');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-05','Physical','Embodiment-dependent. None assumed.');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-06','Technological','Produced through technology. Named, not deployed.');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-07','Collective','Can belong to a system, not only a person.');
INSERT INTO super_power_family(code,name,note) VALUES ('SP-08','Transformative','Larger effect-space. Safeguards required. Not enabled.');
INSERT INTO super_power(id,family_code,name) VALUES (1,'SP-01','Extreme reasoning');
INSERT INTO super_power(id,family_code,name) VALUES (2,'SP-01','Extreme memory');
INSERT INTO super_power(id,family_code,name) VALUES (3,'SP-01','Rapid learning');
INSERT INTO super_power(id,family_code,name) VALUES (4,'SP-01','Parallel reasoning');
INSERT INTO super_power(id,family_code,name) VALUES (5,'SP-01','Massive pattern recognition');
INSERT INTO super_power(id,family_code,name) VALUES (6,'SP-01','High-dimensional modeling');
INSERT INTO super_power(id,family_code,name) VALUES (7,'SP-01','Deep abstraction');
INSERT INTO super_power(id,family_code,name) VALUES (8,'SP-01','Recursive reasoning');
INSERT INTO super_power(id,family_code,name) VALUES (9,'SP-01','Meta-reasoning');
INSERT INTO super_power(id,family_code,name) VALUES (10,'SP-01','Cognitive self-modeling');
INSERT INTO super_power(id,family_code,name) VALUES (11,'SP-02','Universal information retrieval');
INSERT INTO super_power(id,family_code,name) VALUES (12,'SP-02','Real-time synthesis');
INSERT INTO super_power(id,family_code,name) VALUES (13,'SP-02','Massive knowledge integration');
INSERT INTO super_power(id,family_code,name) VALUES (14,'SP-02','Cross-domain knowledge fusion');
INSERT INTO super_power(id,family_code,name) VALUES (15,'SP-02','Instant translation');
INSERT INTO super_power(id,family_code,name) VALUES (16,'SP-02','Information compression');
INSERT INTO super_power(id,family_code,name) VALUES (17,'SP-02','Information reconstruction');
INSERT INTO super_power(id,family_code,name) VALUES (18,'SP-02','Knowledge graph traversal');
INSERT INTO super_power(id,family_code,name) VALUES (19,'SP-02','Provenance reconstruction');
INSERT INTO super_power(id,family_code,name) VALUES (20,'SP-02','Information anomaly detection');
INSERT INTO super_power(id,family_code,name) VALUES (21,'SP-03','Massive computation');
INSERT INTO super_power(id,family_code,name) VALUES (22,'SP-03','Distributed computation');
INSERT INTO super_power(id,family_code,name) VALUES (23,'SP-03','Parallel processing');
INSERT INTO super_power(id,family_code,name) VALUES (24,'SP-03','Autonomous computation');
INSERT INTO super_power(id,family_code,name) VALUES (25,'SP-03','Real-time simulation');
INSERT INTO super_power(id,family_code,name) VALUES (26,'SP-03','Large-scale optimization');
INSERT INTO super_power(id,family_code,name) VALUES (27,'SP-03','Automated theorem proving');
INSERT INTO super_power(id,family_code,name) VALUES (28,'SP-03','Computational experimentation');
INSERT INTO super_power(id,family_code,name) VALUES (29,'SP-03','Recursive system optimization');
INSERT INTO super_power(id,family_code,name) VALUES (30,'SP-04','Generative invention');
INSERT INTO super_power(id,family_code,name) VALUES (31,'SP-04','Scientific discovery');
INSERT INTO super_power(id,family_code,name) VALUES (32,'SP-04','Artistic generation');
INSERT INTO super_power(id,family_code,name) VALUES (33,'SP-04','Novel architecture creation');
INSERT INTO super_power(id,family_code,name) VALUES (34,'SP-04','Automated engineering');
INSERT INTO super_power(id,family_code,name) VALUES (35,'SP-04','World simulation');
INSERT INTO super_power(id,family_code,name) VALUES (36,'SP-04','Game generation');
INSERT INTO super_power(id,family_code,name) VALUES (37,'SP-04','Music composition');
INSERT INTO super_power(id,family_code,name) VALUES (38,'SP-04','Story generation');
INSERT INTO super_power(id,family_code,name) VALUES (39,'SP-04','New-tool creation');
INSERT INTO super_power(id,family_code,name) VALUES (40,'SP-05','Extreme strength');
INSERT INTO super_power(id,family_code,name) VALUES (41,'SP-05','Extreme endurance');
INSERT INTO super_power(id,family_code,name) VALUES (42,'SP-05','Extreme precision');
INSERT INTO super_power(id,family_code,name) VALUES (43,'SP-05','Extreme speed');
INSERT INTO super_power(id,family_code,name) VALUES (44,'SP-05','Advanced locomotion');
INSERT INTO super_power(id,family_code,name) VALUES (45,'SP-05','Autonomous flight');
INSERT INTO super_power(id,family_code,name) VALUES (46,'SP-05','Underwater operation');
INSERT INTO super_power(id,family_code,name) VALUES (47,'SP-05','Robotic manipulation');
INSERT INTO super_power(id,family_code,name) VALUES (48,'SP-05','Microscopic manipulation');
INSERT INTO super_power(id,family_code,name) VALUES (49,'SP-05','Nanoscopic manipulation');
INSERT INTO super_power(id,family_code,name) VALUES (50,'SP-05','Environmental adaptation');
INSERT INTO super_power(id,family_code,name) VALUES (51,'SP-06','Advanced robotics');
INSERT INTO super_power(id,family_code,name) VALUES (52,'SP-06','Autonomous manufacturing');
INSERT INTO super_power(id,family_code,name) VALUES (53,'SP-06','Self-repairing systems');
INSERT INTO super_power(id,family_code,name) VALUES (54,'SP-06','Adaptive hardware');
INSERT INTO super_power(id,family_code,name) VALUES (55,'SP-06','Advanced AI');
INSERT INTO super_power(id,family_code,name) VALUES (56,'SP-06','Distributed intelligence');
INSERT INTO super_power(id,family_code,name) VALUES (57,'SP-06','Brain-computer interfaces');
INSERT INTO super_power(id,family_code,name) VALUES (58,'SP-06','Synthetic biology');
INSERT INTO super_power(id,family_code,name) VALUES (59,'SP-06','Advanced materials');
INSERT INTO super_power(id,family_code,name) VALUES (60,'SP-06','Molecular manufacturing');
INSERT INTO super_power(id,family_code,name) VALUES (61,'SP-06','Autonomous infrastructure');
INSERT INTO super_power(id,family_code,name) VALUES (62,'SP-07','Swarm intelligence');
INSERT INTO super_power(id,family_code,name) VALUES (63,'SP-07','Collective reasoning');
INSERT INTO super_power(id,family_code,name) VALUES (64,'SP-07','Distributed memory');
INSERT INTO super_power(id,family_code,name) VALUES (65,'SP-07','Collective learning');
INSERT INTO super_power(id,family_code,name) VALUES (66,'SP-07','Collective perception');
INSERT INTO super_power(id,family_code,name) VALUES (67,'SP-07','Collective decision support');
INSERT INTO super_power(id,family_code,name) VALUES (68,'SP-07','Distributed creativity');
INSERT INTO super_power(id,family_code,name) VALUES (69,'SP-07','Civilization-scale coordination');
INSERT INTO super_power(id,family_code,name) VALUES (70,'SP-07','Human-AI collaboration');
INSERT INTO super_power(id,family_code,name) VALUES (71,'SP-07','Multi-agent intelligence');
INSERT INTO super_power(id,family_code,name) VALUES (72,'SP-08','Self-improvement');
INSERT INTO super_power(id,family_code,name) VALUES (73,'SP-08','Self-reconfiguration');
INSERT INTO super_power(id,family_code,name) VALUES (74,'SP-08','Capability generation');
INSERT INTO super_power(id,family_code,name) VALUES (75,'SP-08','Environment transformation');
INSERT INTO super_power(id,family_code,name) VALUES (76,'SP-08','System regeneration');
INSERT INTO super_power(id,family_code,name) VALUES (77,'SP-08','Knowledge synthesis');
INSERT INTO super_power(id,family_code,name) VALUES (78,'SP-08','New-system creation');
INSERT INTO super_power(id,family_code,name) VALUES (79,'SP-08','Cross-domain emergence');
INSERT INTO super_power(id,family_code,name) VALUES (80,'SP-08','Civilization-scale engineering');
INSERT INTO super_power(id,family_code,name) VALUES (81,'SP-08','Ecosystem restoration');
INSERT INTO super_power(id,family_code,name) VALUES (82,'SP-08','Autonomous scientific discovery');
INSERT INTO capability_state(name,position) VALUES ('Conceptual',1);
INSERT INTO capability_state(name,position) VALUES ('Possible',2);
INSERT INTO capability_state(name,position) VALUES ('Prototyped',3);
INSERT INTO capability_state(name,position) VALUES ('Demonstrated',4);
INSERT INTO capability_state(name,position) VALUES ('Tested',5);
INSERT INTO capability_state(name,position) VALUES ('Verified',6);
INSERT INTO capability_state(name,position) VALUES ('Operational',7);
INSERT INTO capability_state(name,position) VALUES ('Adaptive',8);
INSERT INTO capability_state(name,position) VALUES ('Generalized',9);
INSERT INTO capability_state(name,position) VALUES ('Emergent',10);
INSERT INTO capability_state(name,position) VALUES ('Transformative',11);
INSERT INTO constraint_kind(name) VALUES ('authorization');
INSERT INTO constraint_kind(name) VALUES ('safety');
INSERT INTO constraint_kind(name) VALUES ('ethics');
INSERT INTO constraint_kind(name) VALUES ('reversibility');
INSERT INTO constraint_kind(name) VALUES ('evidence');
INSERT INTO constraint_kind(name) VALUES ('uncertainty');
INSERT INTO constraint_kind(name) VALUES ('physical-limit');
INSERT INTO constraint_kind(name) VALUES ('computational-limit');
INSERT INTO constraint_kind(name) VALUES ('no-consciousness-axiom');
INSERT INTO platform(name,note) VALUES ('human','Biological embodiment. Capabilities are demonstrated per criterion, not assumed.');
INSERT INTO platform(name,note) VALUES ('ai','Computational embodiment. Consciousness is not assumed.');
INSERT INTO platform(name,note) VALUES ('si','Synthetic or hybrid embodiment. Consciousness is not assumed. Criteria required.');
INSERT INTO platform(name,note) VALUES ('organization','A super power can belong to a system.');
INSERT INTO platform(name,note) VALUES ('machine','Physical machine. Embodiment limits the power.');
INSERT INTO rule(name,statement) VALUES ('measurable-expansion','A super power is measurable expansion of capability, not an impressive name.');
INSERT INTO rule(name,statement) VALUES ('potential-is-not-operational','Conceptual is not possible, possible is not demonstrated, demonstrated is not operational.');
INSERT INTO rule(name,statement) VALUES ('not-supernatural-by-default','Super power does not mean supernatural.');
INSERT INTO rule(name,statement) VALUES ('no-consciousness-axiom','No platform is marked conscious because the ontology names consciousness.');
COMMIT;
