BEGIN TRANSACTION;
INSERT INTO layer(code,name,question,position) VALUES ('SK-01','Information','What information exists?',1);
INSERT INTO layer(code,name,question,position) VALUES ('SK-02','Knowledge','What do we know?',2);
INSERT INTO layer(code,name,question,position) VALUES ('SK-03','Context','Under what conditions is this knowledge applicable?',3);
INSERT INTO layer(code,name,question,position) VALUES ('SK-04','Provenance','Where did this knowledge come from?',4);
INSERT INTO layer(code,name,question,position) VALUES ('SK-05','Evidence','Why should we believe this?',5);
INSERT INTO layer(code,name,question,position) VALUES ('SK-06','Uncertainty','How certain are we?',6);
INSERT INTO layer(code,name,question,position) VALUES ('SK-07','Relationships','How does this connect to everything else?',7);
INSERT INTO layer(code,name,question,position) VALUES ('SK-08','Causality','What produces what, under what conditions?',8);
INSERT INTO layer(code,name,question,position) VALUES ('SK-09','Systems knowledge','How does the whole system behave?',9);
INSERT INTO layer(code,name,question,position) VALUES ('SK-10','Cross-domain synthesis','What becomes visible when separate fields are considered together?',10);
INSERT INTO layer(code,name,question,position) VALUES ('SK-11','Emergent knowledge','What appears only after combination, and is not yet truth?',11);
INSERT INTO layer(code,name,question,position) VALUES ('SK-12','Wisdom','How is knowledge applied with uncertainty, consequences, values, and constraints?',12);
INSERT INTO layer_item(id,layer_code,name) VALUES (1,'SK-01','Observations');
INSERT INTO layer_item(id,layer_code,name) VALUES (2,'SK-01','Measurements');
INSERT INTO layer_item(id,layer_code,name) VALUES (3,'SK-01','Records');
INSERT INTO layer_item(id,layer_code,name) VALUES (4,'SK-01','Data');
INSERT INTO layer_item(id,layer_code,name) VALUES (5,'SK-01','Documents');
INSERT INTO layer_item(id,layer_code,name) VALUES (6,'SK-01','Signals');
INSERT INTO layer_item(id,layer_code,name) VALUES (7,'SK-01','Images');
INSERT INTO layer_item(id,layer_code,name) VALUES (8,'SK-01','Audio');
INSERT INTO layer_item(id,layer_code,name) VALUES (9,'SK-01','Video');
INSERT INTO layer_item(id,layer_code,name) VALUES (10,'SK-01','Sensor data');
INSERT INTO layer_item(id,layer_code,name) VALUES (11,'SK-01','Text');
INSERT INTO layer_item(id,layer_code,name) VALUES (12,'SK-01','Events');
INSERT INTO layer_item(id,layer_code,name) VALUES (13,'SK-02','Facts');
INSERT INTO layer_item(id,layer_code,name) VALUES (14,'SK-02','Concepts');
INSERT INTO layer_item(id,layer_code,name) VALUES (15,'SK-02','Definitions');
INSERT INTO layer_item(id,layer_code,name) VALUES (16,'SK-02','Rules');
INSERT INTO layer_item(id,layer_code,name) VALUES (17,'SK-02','Principles');
INSERT INTO layer_item(id,layer_code,name) VALUES (18,'SK-02','Models');
INSERT INTO layer_item(id,layer_code,name) VALUES (19,'SK-02','Theories');
INSERT INTO layer_item(id,layer_code,name) VALUES (20,'SK-02','Procedures');
INSERT INTO layer_item(id,layer_code,name) VALUES (21,'SK-02','Relationships');
INSERT INTO layer_item(id,layer_code,name) VALUES (22,'SK-02','Known constraints');
INSERT INTO layer_item(id,layer_code,name) VALUES (23,'SK-03','Time');
INSERT INTO layer_item(id,layer_code,name) VALUES (24,'SK-03','Place');
INSERT INTO layer_item(id,layer_code,name) VALUES (25,'SK-03','Environment');
INSERT INTO layer_item(id,layer_code,name) VALUES (26,'SK-03','Population');
INSERT INTO layer_item(id,layer_code,name) VALUES (27,'SK-03','Conditions');
INSERT INTO layer_item(id,layer_code,name) VALUES (28,'SK-03','Assumptions');
INSERT INTO layer_item(id,layer_code,name) VALUES (29,'SK-03','Scope');
INSERT INTO layer_item(id,layer_code,name) VALUES (30,'SK-03','Perspective');
INSERT INTO layer_item(id,layer_code,name) VALUES (31,'SK-03','Historical context');
INSERT INTO layer_item(id,layer_code,name) VALUES (32,'SK-03','Cultural context');
INSERT INTO layer_item(id,layer_code,name) VALUES (33,'SK-03','System state');
INSERT INTO layer_item(id,layer_code,name) VALUES (34,'SK-04','Source');
INSERT INTO layer_item(id,layer_code,name) VALUES (35,'SK-04','Author');
INSERT INTO layer_item(id,layer_code,name) VALUES (36,'SK-04','Origin');
INSERT INTO layer_item(id,layer_code,name) VALUES (37,'SK-04','Timestamp');
INSERT INTO layer_item(id,layer_code,name) VALUES (38,'SK-04','Transformation history');
INSERT INTO layer_item(id,layer_code,name) VALUES (39,'SK-04','Data lineage');
INSERT INTO layer_item(id,layer_code,name) VALUES (40,'SK-04','Citation');
INSERT INTO layer_item(id,layer_code,name) VALUES (41,'SK-04','Observation chain');
INSERT INTO layer_item(id,layer_code,name) VALUES (42,'SK-04','Computational derivation');
INSERT INTO layer_item(id,layer_code,name) VALUES (43,'SK-04','Model generation');
INSERT INTO layer_item(id,layer_code,name) VALUES (44,'SK-04','Human contribution');
INSERT INTO layer_item(id,layer_code,name) VALUES (45,'SK-04','AI contribution');
INSERT INTO layer_item(id,layer_code,name) VALUES (46,'SK-04','SI contribution');
INSERT INTO layer_item(id,layer_code,name) VALUES (47,'SK-05','Observation');
INSERT INTO layer_item(id,layer_code,name) VALUES (48,'SK-05','Measurement');
INSERT INTO layer_item(id,layer_code,name) VALUES (49,'SK-05','Experiment');
INSERT INTO layer_item(id,layer_code,name) VALUES (50,'SK-05','Reproduction');
INSERT INTO layer_item(id,layer_code,name) VALUES (51,'SK-05','Replication');
INSERT INTO layer_item(id,layer_code,name) VALUES (52,'SK-05','Mathematical proof');
INSERT INTO layer_item(id,layer_code,name) VALUES (53,'SK-05','Simulation');
INSERT INTO layer_item(id,layer_code,name) VALUES (54,'SK-05','Documentation');
INSERT INTO layer_item(id,layer_code,name) VALUES (55,'SK-05','Test result');
INSERT INTO layer_item(id,layer_code,name) VALUES (56,'SK-05','Expert testimony');
INSERT INTO layer_item(id,layer_code,name) VALUES (57,'SK-05','Historical evidence');
INSERT INTO layer_item(id,layer_code,name) VALUES (58,'SK-05','Corroboration');
INSERT INTO layer_item(id,layer_code,name) VALUES (59,'SK-05','Contradiction');
INSERT INTO layer_item(id,layer_code,name) VALUES (60,'SK-05','Evidence quality');
INSERT INTO layer_item(id,layer_code,name) VALUES (61,'SK-05','Evidence independence');
INSERT INTO layer_item(id,layer_code,name) VALUES (62,'SK-05','Evidence completeness');
INSERT INTO layer_item(id,layer_code,name) VALUES (63,'SK-05','Evidence age');
INSERT INTO layer_item(id,layer_code,name) VALUES (64,'SK-05','Evidence uncertainty');
INSERT INTO layer_item(id,layer_code,name) VALUES (65,'SK-06','Unknown');
INSERT INTO layer_item(id,layer_code,name) VALUES (66,'SK-06','Uncertain');
INSERT INTO layer_item(id,layer_code,name) VALUES (67,'SK-06','Ambiguous');
INSERT INTO layer_item(id,layer_code,name) VALUES (68,'SK-06','Incomplete');
INSERT INTO layer_item(id,layer_code,name) VALUES (69,'SK-06','Conflicting');
INSERT INTO layer_item(id,layer_code,name) VALUES (70,'SK-06','Unverified');
INSERT INTO layer_item(id,layer_code,name) VALUES (71,'SK-06','Probabilistic');
INSERT INTO layer_item(id,layer_code,name) VALUES (72,'SK-06','Speculative');
INSERT INTO layer_item(id,layer_code,name) VALUES (73,'SK-06','Hypothetical');
INSERT INTO layer_item(id,layer_code,name) VALUES (74,'SK-06','Contested');
INSERT INTO layer_item(id,layer_code,name) VALUES (75,'SK-06','Confidence');
INSERT INTO layer_item(id,layer_code,name) VALUES (76,'SK-06','Error bounds');
INSERT INTO layer_item(id,layer_code,name) VALUES (77,'SK-06','Epistemic uncertainty');
INSERT INTO layer_item(id,layer_code,name) VALUES (78,'SK-06','Aleatory uncertainty');
INSERT INTO layer_item(id,layer_code,name) VALUES (79,'SK-07','Association');
INSERT INTO layer_item(id,layer_code,name) VALUES (80,'SK-07','Similarity');
INSERT INTO layer_item(id,layer_code,name) VALUES (81,'SK-07','Difference');
INSERT INTO layer_item(id,layer_code,name) VALUES (82,'SK-07','Dependency');
INSERT INTO layer_item(id,layer_code,name) VALUES (83,'SK-07','Composition');
INSERT INTO layer_item(id,layer_code,name) VALUES (84,'SK-07','Correlation');
INSERT INTO layer_item(id,layer_code,name) VALUES (85,'SK-07','Causation');
INSERT INTO layer_item(id,layer_code,name) VALUES (86,'SK-07','Analogy');
INSERT INTO layer_item(id,layer_code,name) VALUES (87,'SK-07','Contradiction');
INSERT INTO layer_item(id,layer_code,name) VALUES (88,'SK-07','Complementarity');
INSERT INTO layer_item(id,layer_code,name) VALUES (89,'SK-07','Transformation');
INSERT INTO layer_item(id,layer_code,name) VALUES (90,'SK-07','Emergence');
INSERT INTO layer_item(id,layer_code,name) VALUES (91,'SK-07','Influence');
INSERT INTO layer_item(id,layer_code,name) VALUES (92,'SK-07','Feedback');
INSERT INTO layer_item(id,layer_code,name) VALUES (93,'SK-07','Interdependence');
INSERT INTO layer_item(id,layer_code,name) VALUES (94,'SK-08','Causal inference');
INSERT INTO layer_item(id,layer_code,name) VALUES (95,'SK-08','Counterfactual reasoning');
INSERT INTO layer_item(id,layer_code,name) VALUES (96,'SK-08','Intervention analysis');
INSERT INTO layer_item(id,layer_code,name) VALUES (97,'SK-08','Causal graphs');
INSERT INTO layer_item(id,layer_code,name) VALUES (98,'SK-08','Mechanism identification');
INSERT INTO layer_item(id,layer_code,name) VALUES (99,'SK-08','Necessary conditions');
INSERT INTO layer_item(id,layer_code,name) VALUES (100,'SK-08','Sufficient conditions');
INSERT INTO layer_item(id,layer_code,name) VALUES (101,'SK-08','Feedback loops');
INSERT INTO layer_item(id,layer_code,name) VALUES (102,'SK-08','Second-order effects');
INSERT INTO layer_item(id,layer_code,name) VALUES (103,'SK-08','Unintended consequences');
INSERT INTO layer_item(id,layer_code,name) VALUES (104,'SK-09','Components');
INSERT INTO layer_item(id,layer_code,name) VALUES (105,'SK-09','Boundaries');
INSERT INTO layer_item(id,layer_code,name) VALUES (106,'SK-09','Inputs');
INSERT INTO layer_item(id,layer_code,name) VALUES (107,'SK-09','Outputs');
INSERT INTO layer_item(id,layer_code,name) VALUES (108,'SK-09','Processes');
INSERT INTO layer_item(id,layer_code,name) VALUES (109,'SK-09','Feedback');
INSERT INTO layer_item(id,layer_code,name) VALUES (110,'SK-09','Dependencies');
INSERT INTO layer_item(id,layer_code,name) VALUES (111,'SK-09','Emergence');
INSERT INTO layer_item(id,layer_code,name) VALUES (112,'SK-09','Stability');
INSERT INTO layer_item(id,layer_code,name) VALUES (113,'SK-09','Instability');
INSERT INTO layer_item(id,layer_code,name) VALUES (114,'SK-09','Resilience');
INSERT INTO layer_item(id,layer_code,name) VALUES (115,'SK-09','Adaptation');
INSERT INTO layer_item(id,layer_code,name) VALUES (116,'SK-09','Equilibrium');
INSERT INTO layer_item(id,layer_code,name) VALUES (117,'SK-09','Phase transitions');
INSERT INTO layer_item(id,layer_code,name) VALUES (118,'SK-09','Complex systems');
INSERT INTO layer_item(id,layer_code,name) VALUES (119,'SK-09','Multi-agent systems');
INSERT INTO layer_item(id,layer_code,name) VALUES (120,'SK-10','Cross-domain analogy');
INSERT INTO layer_item(id,layer_code,name) VALUES (121,'SK-10','Concept transfer');
INSERT INTO layer_item(id,layer_code,name) VALUES (122,'SK-10','Knowledge fusion');
INSERT INTO layer_item(id,layer_code,name) VALUES (123,'SK-10','Interdisciplinary reasoning');
INSERT INTO layer_item(id,layer_code,name) VALUES (124,'SK-10','Pattern transfer');
INSERT INTO layer_item(id,layer_code,name) VALUES (125,'SK-10','Structural correspondence');
INSERT INTO layer_item(id,layer_code,name) VALUES (126,'SK-10','Conceptual synthesis');
INSERT INTO layer_item(id,layer_code,name) VALUES (127,'SK-10','Novel hypothesis generation');
INSERT INTO layer_item(id,layer_code,name) VALUES (128,'SK-11','Emergent patterns');
INSERT INTO layer_item(id,layer_code,name) VALUES (129,'SK-11','Unexpected correlations');
INSERT INTO layer_item(id,layer_code,name) VALUES (130,'SK-11','System-level behavior');
INSERT INTO layer_item(id,layer_code,name) VALUES (131,'SK-11','Novel hypotheses');
INSERT INTO layer_item(id,layer_code,name) VALUES (132,'SK-11','New categories');
INSERT INTO layer_item(id,layer_code,name) VALUES (133,'SK-11','New relationships');
INSERT INTO layer_item(id,layer_code,name) VALUES (134,'SK-11','New causal hypotheses');
INSERT INTO layer_item(id,layer_code,name) VALUES (135,'SK-11','New models');
INSERT INTO layer_item(id,layer_code,name) VALUES (136,'SK-11','New questions');
INSERT INTO layer_item(id,layer_code,name) VALUES (137,'SK-12','Judgment');
INSERT INTO layer_item(id,layer_code,name) VALUES (138,'SK-12','Proportionality');
INSERT INTO layer_item(id,layer_code,name) VALUES (139,'SK-12','Foresight');
INSERT INTO layer_item(id,layer_code,name) VALUES (140,'SK-12','Consequence analysis');
INSERT INTO layer_item(id,layer_code,name) VALUES (141,'SK-12','Ethical reasoning');
INSERT INTO layer_item(id,layer_code,name) VALUES (142,'SK-12','Stewardship');
INSERT INTO layer_item(id,layer_code,name) VALUES (143,'SK-12','Long-term thinking');
INSERT INTO layer_item(id,layer_code,name) VALUES (144,'SK-12','Harm minimization');
INSERT INTO layer_item(id,layer_code,name) VALUES (145,'SK-12','Reversibility assessment');
INSERT INTO layer_item(id,layer_code,name) VALUES (146,'SK-12','Contextual application');
INSERT INTO layer_item(id,layer_code,name) VALUES (147,'SK-12','Value-sensitive reasoning');
INSERT INTO layer_item(id,layer_code,name) VALUES (148,'SK-12','Knowing when not to act');
INSERT INTO layer_item(id,layer_code,name) VALUES (149,'SK-12','Knowing when more information is required');
INSERT INTO perspective(name,note) VALUES ('Human','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Scientific','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Historical','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Cultural','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Individual','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Institutional','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Machine-derived','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('AI-generated hypothesis','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('SI-derived','Standpoint, not truth. Not an axiom of consciousness.');
INSERT INTO perspective(name,note) VALUES ('First-person observation','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Third-person observation','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Local','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Global','Standpoint, not truth.');
INSERT INTO perspective(name,note) VALUES ('Temporal','Standpoint, not truth.');
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-but-searchable',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-because-no-data',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-because-conflicting-data',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-because-undecidable',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-because-unobservable',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-because-insufficient-model',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-because-computationally-intractable',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown-because-question-is-undefined',1);
INSERT INTO unknown_kind(name,known_unknown) VALUES ('Unknown unknown',0);
INSERT INTO claim_status(name) VALUES ('hypothesis');
INSERT INTO claim_status(name) VALUES ('supported');
INSERT INTO claim_status(name) VALUES ('contested');
INSERT INTO claim_status(name) VALUES ('revised');
INSERT INTO claim_status(name) VALUES ('verified');
INSERT INTO claim_status(name) VALUES ('refused');
INSERT INTO distinction(name,note) VALUES ('observed','What was recorded.');
INSERT INTO distinction(name,note) VALUES ('inferred','What was concluded from observations.');
INSERT INTO distinction(name,note) VALUES ('hypothesized','What is proposed and not yet tested.');
INSERT INTO distinction(name,note) VALUES ('believed','What is held, without that holding being proof.');
INSERT INTO distinction(name,note) VALUES ('unknown','What is not known, named as such.');
INSERT INTO distinction(name,note) VALUES ('verified','What passed a check.');
INSERT INTO causal_grade(name) VALUES ('co-occurs');
INSERT INTO causal_grade(name) VALUES ('contributes');
INSERT INTO causal_grade(name) VALUES ('causes');
INSERT INTO causal_grade(name) VALUES ('necessary');
INSERT INTO causal_grade(name) VALUES ('sufficient');
INSERT INTO causal_grade(name) VALUES ('conditional');
INSERT INTO super_skill(name,definition) VALUES ('integrate','Combine more than one skill across domains without erasing the source skill.');
INSERT INTO super_skill(name,definition) VALUES ('compose','Build a skill from other skills, with the parts named.');
INSERT INTO super_skill(name,definition) VALUES ('adapt','Change a skill for a new context, and record the context.');
INSERT INTO super_skill(name,definition) VALUES ('verify','Check the result against evidence. A pattern is not a pass.');
INSERT INTO super_skill(name,definition) VALUES ('improve','Update the skill from observation. Emergence is not automatically truth.');
INSERT INTO learning_step(position,name) VALUES (1,'subject');
INSERT INTO learning_step(position,name) VALUES (2,'knowledge');
INSERT INTO learning_step(position,name) VALUES (3,'super-knowledge');
INSERT INTO learning_step(position,name) VALUES (4,'skill');
INSERT INTO learning_step(position,name) VALUES (5,'action');
INSERT INTO learning_step(position,name) VALUES (6,'observation');
INSERT INTO learning_step(position,name) VALUES (7,'evidence');
INSERT INTO learning_step(position,name) VALUES (8,'updated-knowledge');
COMMIT;
