BEGIN TRANSACTION;
INSERT INTO domain(code,name,role) VALUES ('U0', 'Meta-knowledge', 'Root supervisory domain. Knowledge about knowledge.');
INSERT INTO domain(code,name,role) VALUES ('U1', 'Mathematics and formal systems', 'Abstract structures and formal relationships.');
INSERT INTO domain(code,name,role) VALUES ('U2', 'Physical universe', 'Physical reality.');
INSERT INTO domain(code,name,role) VALUES ('U3', 'Earth and planetary systems', 'Planets and their physical systems.');
INSERT INTO domain(code,name,role) VALUES ('U4', 'Life', 'Living systems. Not an object inside technology.');
INSERT INTO domain(code,name,role) VALUES ('U5', 'Mind and cognition', 'Cognition and internal information processing.');
INSERT INTO domain(code,name,role) VALUES ('U6', 'Consciousness, self and existence', 'Not buried in psychology. Consciousness is not an axiom.');
INSERT INTO domain(code,name,role) VALUES ('U7', 'Humanity and society', 'Humans as social beings.');
INSERT INTO domain(code,name,role) VALUES ('U8', 'Language, information and communication', 'Language as human phenomenon, information structure, and AI substrate.');
INSERT INTO domain(code,name,role) VALUES ('U9', 'Technology and artificial systems', 'Deliberately engineered systems. SI is a subject here, not a feature.');
INSERT INTO domain(code,name,role) VALUES ('U10', 'Human creation and culture', 'Symbolic, artistic, cultural, and creative activity.');
INSERT INTO domain(code,name,role) VALUES ('U11', 'Ethics, values and stewardship', 'Constraint layer across every other domain.');
INSERT INTO domain(code,name,role) VALUES ('U12', 'Systems, relationships and complexity', 'Cross-domain connections. Knowledge is not isolated boxes.');
INSERT INTO subject(id,name) VALUES (1, 'Epistemology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (1, 'U0');
INSERT INTO subject(id,name) VALUES (2, 'Ontology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (2, 'U0');
INSERT INTO subject(id,name) VALUES (3, 'Logic');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (3, 'U0');
INSERT INTO subject(id,name) VALUES (4, 'Reasoning');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (4, 'U0');
INSERT INTO subject(id,name) VALUES (5, 'Inference');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (5, 'U0');
INSERT INTO subject(id,name) VALUES (6, 'Evidence');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (6, 'U0');
INSERT INTO subject(id,name) VALUES (7, 'Uncertainty');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (7, 'U0');
INSERT INTO subject(id,name) VALUES (8, 'Truth');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (8, 'U0');
INSERT INTO subject(id,name) VALUES (9, 'Falsifiability');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (9, 'U0');
INSERT INTO subject(id,name) VALUES (10, 'Methodology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (10, 'U0');
INSERT INTO subject(id,name) VALUES (11, 'Scientific method');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (11, 'U0');
INSERT INTO subject(id,name) VALUES (12, 'Classification');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (12, 'U0');
INSERT INTO subject(id,name) VALUES (13, 'Taxonomy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (13, 'U0');
INSERT INTO subject(id,name) VALUES (14, 'Semantics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (14, 'U0');
INSERT INTO subject(id,name) VALUES (15, 'Information theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (15, 'U0');
INSERT INTO subject(id,name) VALUES (16, 'Measurement');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (16, 'U0');
INSERT INTO subject(id,name) VALUES (17, 'Models');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (17, 'U0');
INSERT INTO subject(id,name) VALUES (18, 'Theories');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (18, 'U0');
INSERT INTO subject(id,name) VALUES (19, 'Hypotheses');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (19, 'U0');
INSERT INTO subject(id,name) VALUES (20, 'Explanation');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (20, 'U0');
INSERT INTO subject(id,name) VALUES (21, 'Prediction');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (21, 'U0');
INSERT INTO subject(id,name) VALUES (22, 'Causality');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (22, 'U0');
INSERT INTO subject(id,name) VALUES (23, 'Knowledge representation');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (23, 'U0');
INSERT INTO subject(id,name) VALUES (24, 'Knowledge graphs');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (24, 'U0');
INSERT INTO subject(id,name) VALUES (25, 'AI reasoning');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (25, 'U0');
INSERT INTO subject(id,name) VALUES (26, 'Machine learning');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (26, 'U0');
INSERT INTO subject(id,name) VALUES (27, 'Cognition');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (27, 'U0');
INSERT INTO subject(id,name) VALUES (28, 'Metacognition');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (28, 'U0');
INSERT INTO subject(id,name) VALUES (29, 'Arithmetic');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (29, 'U1');
INSERT INTO subject(id,name) VALUES (30, 'Algebra');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (30, 'U1');
INSERT INTO subject(id,name) VALUES (31, 'Geometry');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (31, 'U1');
INSERT INTO subject(id,name) VALUES (32, 'Topology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (32, 'U1');
INSERT INTO subject(id,name) VALUES (33, 'Analysis');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (33, 'U1');
INSERT INTO subject(id,name) VALUES (34, 'Calculus');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (34, 'U1');
INSERT INTO subject(id,name) VALUES (35, 'Differential equations');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (35, 'U1');
INSERT INTO subject(id,name) VALUES (36, 'Number theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (36, 'U1');
INSERT INTO subject(id,name) VALUES (37, 'Probability');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (37, 'U1');
INSERT INTO subject(id,name) VALUES (38, 'Statistics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (38, 'U1');
INSERT INTO subject(id,name) VALUES (39, 'Combinatorics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (39, 'U1');
INSERT INTO subject(id,name) VALUES (40, 'Graph theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (40, 'U1');
INSERT INTO subject(id,name) VALUES (41, 'Set theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (41, 'U1');
INSERT INTO subject(id,name) VALUES (42, 'Category theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (42, 'U1');
INSERT INTO subject(id,name) VALUES (43, 'Mathematical logic');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (43, 'U1');
INSERT INTO subject(id,name) VALUES (44, 'Computation theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (44, 'U1');
INSERT INTO subject(id,name) VALUES (45, 'Optimization');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (45, 'U1');
INSERT INTO subject(id,name) VALUES (46, 'Game theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (46, 'U1');
INSERT INTO subject(id,name) VALUES (47, 'Formal languages');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (47, 'U1');
INSERT INTO subject(id,name) VALUES (48, 'Formal verification');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (48, 'U1');
INSERT INTO subject(id,name) VALUES (49, 'Physics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (49, 'U2');
INSERT INTO subject(id,name) VALUES (50, 'Mechanics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (50, 'U2');
INSERT INTO subject(id,name) VALUES (51, 'Relativity');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (51, 'U2');
INSERT INTO subject(id,name) VALUES (52, 'Quantum physics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (52, 'U2');
INSERT INTO subject(id,name) VALUES (53, 'Thermodynamics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (53, 'U2');
INSERT INTO subject(id,name) VALUES (54, 'Statistical mechanics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (54, 'U2');
INSERT INTO subject(id,name) VALUES (55, 'Electromagnetism');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (55, 'U2');
INSERT INTO subject(id,name) VALUES (56, 'Optics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (56, 'U2');
INSERT INTO subject(id,name) VALUES (57, 'Acoustics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (57, 'U2');
INSERT INTO subject(id,name) VALUES (58, 'Particle physics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (58, 'U2');
INSERT INTO subject(id,name) VALUES (59, 'Nuclear physics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (59, 'U2');
INSERT INTO subject(id,name) VALUES (60, 'Condensed matter');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (60, 'U2');
INSERT INTO subject(id,name) VALUES (61, 'Materials');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (61, 'U2');
INSERT INTO subject(id,name) VALUES (62, 'Chemistry');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (62, 'U2');
INSERT INTO subject(id,name) VALUES (63, 'Physical chemistry');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (63, 'U2');
INSERT INTO subject(id,name) VALUES (64, 'Astronomy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (64, 'U2');
INSERT INTO subject(id,name) VALUES (65, 'Astrophysics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (65, 'U2');
INSERT INTO subject(id,name) VALUES (66, 'Cosmology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (66, 'U2');
INSERT INTO subject(id,name) VALUES (67, 'Space science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (67, 'U2');
INSERT INTO subject(id,name) VALUES (68, 'Geology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (68, 'U3');
INSERT INTO subject(id,name) VALUES (69, 'Geophysics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (69, 'U3');
INSERT INTO subject(id,name) VALUES (70, 'Geography');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (70, 'U3');
INSERT INTO subject(id,name) VALUES (71, 'Meteorology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (71, 'U3');
INSERT INTO subject(id,name) VALUES (72, 'Climate science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (72, 'U3');
INSERT INTO subject(id,name) VALUES (73, 'Oceanography');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (73, 'U3');
INSERT INTO subject(id,name) VALUES (74, 'Hydrology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (74, 'U3');
INSERT INTO subject(id,name) VALUES (75, 'Glaciology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (75, 'U3');
INSERT INTO subject(id,name) VALUES (76, 'Volcanology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (76, 'U3');
INSERT INTO subject(id,name) VALUES (77, 'Mineralogy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (77, 'U3');
INSERT INTO subject(id,name) VALUES (78, 'Soil science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (78, 'U3');
INSERT INTO subject(id,name) VALUES (79, 'Paleontology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (79, 'U3');
INSERT INTO subject(id,name) VALUES (80, 'Atmospheric science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (80, 'U3');
INSERT INTO subject(id,name) VALUES (81, 'Planetary science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (81, 'U3');
INSERT INTO subject(id,name) VALUES (82, 'Earth systems science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (82, 'U3');
INSERT INTO subject(id,name) VALUES (83, 'Natural hazards');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (83, 'U3');
INSERT INTO subject(id,name) VALUES (84, 'Environmental systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (84, 'U3');
INSERT INTO subject(id,name) VALUES (85, 'Biology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (85, 'U4');
INSERT INTO subject(id,name) VALUES (86, 'Molecular biology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (86, 'U4');
INSERT INTO subject(id,name) VALUES (87, 'Cell biology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (87, 'U4');
INSERT INTO subject(id,name) VALUES (88, 'Genetics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (88, 'U4');
INSERT INTO subject(id,name) VALUES (89, 'Genomics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (89, 'U4');
INSERT INTO subject(id,name) VALUES (90, 'Evolution');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (90, 'U4');
INSERT INTO subject(id,name) VALUES (91, 'Ecology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (91, 'U4');
INSERT INTO subject(id,name) VALUES (92, 'Botany');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (92, 'U4');
INSERT INTO subject(id,name) VALUES (93, 'Zoology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (93, 'U4');
INSERT INTO subject(id,name) VALUES (94, 'Microbiology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (94, 'U4');
INSERT INTO subject(id,name) VALUES (95, 'Virology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (95, 'U4');
INSERT INTO subject(id,name) VALUES (96, 'Physiology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (96, 'U4');
INSERT INTO subject(id,name) VALUES (97, 'Anatomy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (97, 'U4');
INSERT INTO subject(id,name) VALUES (98, 'Developmental biology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (98, 'U4');
INSERT INTO subject(id,name) VALUES (99, 'Biochemistry');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (99, 'U4');
INSERT INTO subject(id,name) VALUES (100, 'Bioinformatics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (100, 'U4');
INSERT INTO subject(id,name) VALUES (101, 'Systems biology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (101, 'U4');
INSERT INTO subject(id,name) VALUES (102, 'Synthetic biology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (102, 'U4');
INSERT INTO subject(id,name) VALUES (103, 'Biotechnology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (103, 'U4');
INSERT INTO subject(id,name) VALUES (104, 'Medicine');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (104, 'U4');
INSERT INTO subject(id,name) VALUES (105, 'Veterinary science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (105, 'U4');
INSERT INTO subject(id,name) VALUES (106, 'Agriculture');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (106, 'U4');
INSERT INTO subject(id,name) VALUES (107, 'Forestry');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (107, 'U4');
INSERT INTO subject(id,name) VALUES (108, 'Fisheries');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (108, 'U4');
INSERT INTO subject(id,name) VALUES (109, 'Psychology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (109, 'U5');
INSERT INTO subject(id,name) VALUES (110, 'Cognitive science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (110, 'U5');
INSERT INTO subject(id,name) VALUES (111, 'Perception');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (111, 'U5');
INSERT INTO subject(id,name) VALUES (112, 'Memory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (112, 'U5');
INSERT INTO subject(id,name) VALUES (113, 'Attention');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (113, 'U5');
INSERT INTO subject(id,name) VALUES (114, 'Learning');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (114, 'U5');
INSERT INTO subject(id,name) VALUES (115, 'Emotion');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (115, 'U5');
INSERT INTO subject(id,name) VALUES (116, 'Motivation');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (116, 'U5');
INSERT INTO subject(id,name) VALUES (117, 'Language cognition');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (117, 'U5');
INSERT INTO subject(id,name) VALUES (118, 'Decision-making');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (118, 'U5');
INSERT INTO subject(id,name) VALUES (119, 'Creativity');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (119, 'U5');
INSERT INTO subject(id,name) VALUES (120, 'Human-computer interaction');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (120, 'U5');
INSERT INTO subject(id,name) VALUES (121, 'Cognitive architectures');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (121, 'U5');
INSERT INTO subject(id,name) VALUES (122, 'Artificial cognition');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (122, 'U5');
INSERT INTO subject(id,name) VALUES (123, 'Machine cognition');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (123, 'U5');
INSERT INTO subject(id,name) VALUES (124, 'Collective cognition');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (124, 'U5');
INSERT INTO subject(id,name) VALUES (125, 'Philosophy of mind');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (125, 'U6');
INSERT INTO subject(id,name) VALUES (126, 'Consciousness studies');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (126, 'U6');
INSERT INTO subject(id,name) VALUES (127, 'Selfhood');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (127, 'U6');
INSERT INTO subject(id,name) VALUES (128, 'Identity');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (128, 'U6');
INSERT INTO subject(id,name) VALUES (129, 'Personal identity');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (129, 'U6');
INSERT INTO subject(id,name) VALUES (130, 'Agency');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (130, 'U6');
INSERT INTO subject(id,name) VALUES (131, 'Intentionality');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (131, 'U6');
INSERT INTO subject(id,name) VALUES (132, 'Subjectivity');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (132, 'U6');
INSERT INTO subject(id,name) VALUES (133, 'Phenomenology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (133, 'U6');
INSERT INTO subject(id,name) VALUES (134, 'Existential philosophy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (134, 'U6');
INSERT INTO subject(id,name) VALUES (135, 'Being');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (135, 'U6');
INSERT INTO subject(id,name) VALUES (136, 'Experience');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (136, 'U6');
INSERT INTO subject(id,name) VALUES (137, 'Meaning');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (137, 'U6');
INSERT INTO subject(id,name) VALUES (138, 'Free will');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (138, 'U6');
INSERT INTO subject(id,name) VALUES (139, 'Embodiment');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (139, 'U6');
INSERT INTO subject(id,name) VALUES (140, 'Artificial consciousness');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (140, 'U6');
INSERT INTO subject(id,name) VALUES (141, 'Machine self-models');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (141, 'U6');
INSERT INTO subject(id,name) VALUES (142, 'Synthetic agency');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (142, 'U6');
INSERT INTO subject(id,name) VALUES (143, 'Continuity of identity');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (143, 'U6');
INSERT INTO subject(id,name) VALUES (144, 'Anthropology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (144, 'U7');
INSERT INTO subject(id,name) VALUES (145, 'Sociology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (145, 'U7');
INSERT INTO subject(id,name) VALUES (146, 'Demography');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (146, 'U7');
INSERT INTO subject(id,name) VALUES (147, 'Economics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (147, 'U7');
INSERT INTO subject(id,name) VALUES (148, 'Political science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (148, 'U7');
INSERT INTO subject(id,name) VALUES (149, 'Law');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (149, 'U7');
INSERT INTO subject(id,name) VALUES (150, 'Governance');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (150, 'U7');
INSERT INTO subject(id,name) VALUES (151, 'Institutions');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (151, 'U7');
INSERT INTO subject(id,name) VALUES (152, 'Organizations');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (152, 'U7');
INSERT INTO subject(id,name) VALUES (153, 'Communities');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (153, 'U7');
INSERT INTO subject(id,name) VALUES (154, 'Education');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (154, 'U7');
INSERT INTO subject(id,name) VALUES (155, 'Communication');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (155, 'U7');
INSERT INTO subject(id,name) VALUES (156, 'Journalism');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (156, 'U7');
INSERT INTO subject(id,name) VALUES (157, 'Linguistics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (157, 'U7');
INSERT INTO subject(id,name) VALUES (158, 'Culture');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (158, 'U7');
INSERT INTO subject(id,name) VALUES (159, 'Civilization');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (159, 'U7');
INSERT INTO subject(id,name) VALUES (160, 'Archaeology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (160, 'U7');
INSERT INTO subject(id,name) VALUES (161, 'History');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (161, 'U7');
INSERT INTO subject(id,name) VALUES (162, 'Human geography');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (162, 'U7');
INSERT INTO subject(id,name) VALUES (163, 'International relations');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (163, 'U7');
INSERT INTO subject(id,name) VALUES (164, 'Conflict studies');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (164, 'U7');
INSERT INTO subject(id,name) VALUES (165, 'Cooperation');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (165, 'U7');
INSERT INTO subject(id,name) VALUES (166, 'Social networks');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (166, 'U7');
INSERT INTO subject(id,name) VALUES (167, 'Phonetics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (167, 'U8');
INSERT INTO subject(id,name) VALUES (168, 'Phonology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (168, 'U8');
INSERT INTO subject(id,name) VALUES (169, 'Morphology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (169, 'U8');
INSERT INTO subject(id,name) VALUES (170, 'Syntax');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (170, 'U8');
INSERT INTO subject(id,name) VALUES (171, 'Pragmatics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (171, 'U8');
INSERT INTO subject(id,name) VALUES (172, 'Semiotics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (172, 'U8');
INSERT INTO subject(id,name) VALUES (173, 'Writing');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (173, 'U8');
INSERT INTO subject(id,name) VALUES (174, 'Natural languages');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (174, 'U8');
INSERT INTO subject(id,name) VALUES (175, 'Programming languages');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (175, 'U8');
INSERT INTO subject(id,name) VALUES (176, 'Translation');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (176, 'U8');
INSERT INTO subject(id,name) VALUES (177, 'Information retrieval');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (177, 'U8');
INSERT INTO subject(id,name) VALUES (178, 'Information architecture');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (178, 'U8');
INSERT INTO subject(id,name) VALUES (179, 'Communication theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (179, 'U8');
INSERT INTO subject(id,name) VALUES (180, 'Cryptography');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (180, 'U8');
INSERT INTO subject(id,name) VALUES (181, 'Data science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (181, 'U8');
INSERT INTO subject(id,name) VALUES (182, 'Databases');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (182, 'U8');
INSERT INTO subject(id,name) VALUES (183, 'Human-machine communication');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (183, 'U8');
INSERT INTO subject(id,name) VALUES (184, 'Machine-machine communication');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (184, 'U8');
INSERT INTO subject(id,name) VALUES (185, 'Computer science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (185, 'U9');
INSERT INTO subject(id,name) VALUES (186, 'Artificial intelligence');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (186, 'U9');
INSERT INTO subject(id,name) VALUES (187, 'Robotics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (187, 'U9');
INSERT INTO subject(id,name) VALUES (188, 'Cybernetics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (188, 'U9');
INSERT INTO subject(id,name) VALUES (189, 'Software engineering');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (189, 'U9');
INSERT INTO subject(id,name) VALUES (190, 'Hardware engineering');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (190, 'U9');
INSERT INTO subject(id,name) VALUES (191, 'Electrical engineering');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (191, 'U9');
INSERT INTO subject(id,name) VALUES (192, 'Mechanical engineering');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (192, 'U9');
INSERT INTO subject(id,name) VALUES (193, 'Civil engineering');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (193, 'U9');
INSERT INTO subject(id,name) VALUES (194, 'Chemical engineering');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (194, 'U9');
INSERT INTO subject(id,name) VALUES (195, 'Aerospace engineering');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (195, 'U9');
INSERT INTO subject(id,name) VALUES (196, 'Nanotechnology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (196, 'U9');
INSERT INTO subject(id,name) VALUES (197, 'Energy technology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (197, 'U9');
INSERT INTO subject(id,name) VALUES (198, 'Manufacturing');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (198, 'U9');
INSERT INTO subject(id,name) VALUES (199, 'Architecture');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (199, 'U9');
INSERT INTO subject(id,name) VALUES (200, 'Infrastructure');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (200, 'U9');
INSERT INTO subject(id,name) VALUES (201, 'Telecommunications');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (201, 'U9');
INSERT INTO subject(id,name) VALUES (202, 'Cybersecurity');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (202, 'U9');
INSERT INTO subject(id,name) VALUES (203, 'Human-computer systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (203, 'U9');
INSERT INTO subject(id,name) VALUES (204, 'Autonomous systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (204, 'U9');
INSERT INTO subject(id,name) VALUES (205, 'Synthetic intelligence');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (205, 'U9');
INSERT INTO subject(id,name) VALUES (206, 'AI agents');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (206, 'U9');
INSERT INTO subject(id,name) VALUES (207, 'Multi-agent systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (207, 'U9');
INSERT INTO subject(id,name) VALUES (208, 'Music');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (208, 'U10');
INSERT INTO subject(id,name) VALUES (209, 'Visual art');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (209, 'U10');
INSERT INTO subject(id,name) VALUES (210, 'Sculpture');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (210, 'U10');
INSERT INTO subject(id,name) VALUES (211, 'Literature');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (211, 'U10');
INSERT INTO subject(id,name) VALUES (212, 'Poetry');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (212, 'U10');
INSERT INTO subject(id,name) VALUES (213, 'Theatre');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (213, 'U10');
INSERT INTO subject(id,name) VALUES (214, 'Dance');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (214, 'U10');
INSERT INTO subject(id,name) VALUES (215, 'Film');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (215, 'U10');
INSERT INTO subject(id,name) VALUES (216, 'Photography');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (216, 'U10');
INSERT INTO subject(id,name) VALUES (217, 'Game design');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (217, 'U10');
INSERT INTO subject(id,name) VALUES (218, 'Storytelling');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (218, 'U10');
INSERT INTO subject(id,name) VALUES (219, 'Design');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (219, 'U10');
INSERT INTO subject(id,name) VALUES (220, 'Fashion');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (220, 'U10');
INSERT INTO subject(id,name) VALUES (221, 'Craft');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (221, 'U10');
INSERT INTO subject(id,name) VALUES (222, 'Culinary arts');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (222, 'U10');
INSERT INTO subject(id,name) VALUES (223, 'Mythology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (223, 'U10');
INSERT INTO subject(id,name) VALUES (224, 'Religion');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (224, 'U10');
INSERT INTO subject(id,name) VALUES (225, 'Philosophy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (225, 'U10');
INSERT INTO subject(id,name) VALUES (226, 'Cultural traditions');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (226, 'U10');
INSERT INTO subject(id,name) VALUES (227, 'Aesthetics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (227, 'U10');
INSERT INTO subject(id,name) VALUES (228, 'Creative technology');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (228, 'U10');
INSERT INTO subject(id,name) VALUES (229, 'Ethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (229, 'U11');
INSERT INTO subject(id,name) VALUES (230, 'Moral philosophy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (230, 'U11');
INSERT INTO subject(id,name) VALUES (231, 'Applied ethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (231, 'U11');
INSERT INTO subject(id,name) VALUES (232, 'Bioethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (232, 'U11');
INSERT INTO subject(id,name) VALUES (233, 'AI ethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (233, 'U11');
INSERT INTO subject(id,name) VALUES (234, 'Technology ethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (234, 'U11');
INSERT INTO subject(id,name) VALUES (235, 'Environmental ethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (235, 'U11');
INSERT INTO subject(id,name) VALUES (236, 'Animal ethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (236, 'U11');
INSERT INTO subject(id,name) VALUES (237, 'Human rights');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (237, 'U11');
INSERT INTO subject(id,name) VALUES (238, 'Justice');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (238, 'U11');
INSERT INTO subject(id,name) VALUES (239, 'Equality');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (239, 'U11');
INSERT INTO subject(id,name) VALUES (240, 'Responsibility');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (240, 'U11');
INSERT INTO subject(id,name) VALUES (241, 'Consent');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (241, 'U11');
INSERT INTO subject(id,name) VALUES (242, 'Autonomy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (242, 'U11');
INSERT INTO subject(id,name) VALUES (243, 'Privacy');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (243, 'U11');
INSERT INTO subject(id,name) VALUES (244, 'Safety');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (244, 'U11');
INSERT INTO subject(id,name) VALUES (245, 'Trust');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (245, 'U11');
INSERT INTO subject(id,name) VALUES (246, 'Accountability');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (246, 'U11');
INSERT INTO subject(id,name) VALUES (247, 'Governance ethics');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (247, 'U11');
INSERT INTO subject(id,name) VALUES (248, 'Stewardship');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (248, 'U11');
INSERT INTO subject(id,name) VALUES (249, 'Sustainability');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (249, 'U11');
INSERT INTO subject(id,name) VALUES (250, 'Intergenerational responsibility');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (250, 'U11');
INSERT INTO subject(id,name) VALUES (251, 'Life preservation');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (251, 'U11');
INSERT INTO subject(id,name) VALUES (252, 'Conflict resolution');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (252, 'U11');
INSERT INTO subject(id,name) VALUES (253, 'Systems theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (253, 'U12');
INSERT INTO subject(id,name) VALUES (254, 'Complexity science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (254, 'U12');
INSERT INTO subject(id,name) VALUES (255, 'Network science');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (255, 'U12');
INSERT INTO subject(id,name) VALUES (256, 'Emergence');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (256, 'U12');
INSERT INTO subject(id,name) VALUES (257, 'Dynamical systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (257, 'U12');
INSERT INTO subject(id,name) VALUES (258, 'Feedback');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (258, 'U12');
INSERT INTO subject(id,name) VALUES (259, 'Control theory');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (259, 'U12');
INSERT INTO subject(id,name) VALUES (260, 'Resilience');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (260, 'U12');
INSERT INTO subject(id,name) VALUES (261, 'Adaptation');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (261, 'U12');
INSERT INTO subject(id,name) VALUES (262, 'Self-organization');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (262, 'U12');
INSERT INTO subject(id,name) VALUES (263, 'Evolutionary systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (263, 'U12');
INSERT INTO subject(id,name) VALUES (264, 'Ecosystems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (264, 'U12');
INSERT INTO subject(id,name) VALUES (265, 'Social systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (265, 'U12');
INSERT INTO subject(id,name) VALUES (266, 'Economic systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (266, 'U12');
INSERT INTO subject(id,name) VALUES (267, 'Technological systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (267, 'U12');
INSERT INTO subject(id,name) VALUES (268, 'AI systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (268, 'U12');
INSERT INTO subject(id,name) VALUES (269, 'Planetary systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (269, 'U12');
INSERT INTO subject(id,name) VALUES (270, 'Human-machine systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (270, 'U12');
INSERT INTO subject(id,name) VALUES (271, 'Civilization systems');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (271, 'U12');
INSERT INTO subject(id,name) VALUES (272, 'Cross-domain interactions');
INSERT INTO subject_domain(subject_id,domain_code) VALUES (272, 'U12');
INSERT INTO subject(id,name) VALUES (273, 'Neuroscience');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (15, 'U1');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (2, 'U6');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (14, 'U8');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (22, 'U12');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (23, 'U8');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (24, 'U8');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (26, 'U9');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (27, 'U5');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (28, 'U5');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (273, 'U4');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (273, 'U5');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (273, 'U6');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (47, 'U8');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (126, 'U5');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (157, 'U8');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (155, 'U8');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (188, 'U12');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (103, 'U9');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (199, 'U10');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (225, 'U6');
INSERT OR IGNORE INTO subject_domain(subject_id,domain_code) VALUES (207, 'U12');
INSERT INTO knowledge_mode(name,question) VALUES ('Existence', 'What exists?');
INSERT INTO knowledge_mode(name,question) VALUES ('Structure', 'What is it made of?');
INSERT INTO knowledge_mode(name,question) VALUES ('Properties', 'What characteristics does it have?');
INSERT INTO knowledge_mode(name,question) VALUES ('Process', 'What happens?');
INSERT INTO knowledge_mode(name,question) VALUES ('Causality', 'What causes what?');
INSERT INTO knowledge_mode(name,question) VALUES ('Relationship', 'How does it interact with something else?');
INSERT INTO knowledge_mode(name,question) VALUES ('Measurement', 'How do we know?');
INSERT INTO knowledge_mode(name,question) VALUES ('History', 'How did it get here?');
INSERT INTO knowledge_mode(name,question) VALUES ('Prediction', 'What may happen?');
INSERT INTO knowledge_mode(name,question) VALUES ('Agency', 'What can act?');
INSERT INTO knowledge_mode(name,question) VALUES ('Intent', 'Why is an action taken?');
INSERT INTO knowledge_mode(name,question) VALUES ('Value', 'Why does it matter?');
INSERT INTO knowledge_mode(name,question) VALUES ('Ethics', 'What ought to be done?');
INSERT INTO knowledge_mode(name,question) VALUES ('Design', 'What can be created?');
INSERT INTO knowledge_mode(name,question) VALUES ('Transformation', 'How can it change?');
INSERT INTO knowledge_mode(name,question) VALUES ('Stewardship', 'How should it be maintained?');
INSERT INTO relationship_type(name) VALUES ('related_to');
INSERT INTO relationship_type(name) VALUES ('depends_on');
INSERT INTO relationship_type(name) VALUES ('hypothesized_by');
INSERT INTO relationship_type(name) VALUES ('contradicted_by');
INSERT INTO relationship_type(name) VALUES ('supported_by');
INSERT INTO relationship_type(name) VALUES ('analogy');
INSERT INTO relationship_type(name) VALUES ('contrast');
INSERT INTO relationship_type(name) VALUES ('emergence');
INSERT INTO relationship_type(name) VALUES ('influence');
INSERT INTO relationship_type(name) VALUES ('composition');
INSERT INTO relationship_type(name) VALUES ('interaction');
INSERT INTO relationship_type(name) VALUES ('causality');
INSERT INTO relationship_type(name) VALUES ('dependency');
INSERT INTO evidence_kind(name) VALUES ('empirical');
INSERT INTO evidence_kind(name) VALUES ('observational');
INSERT INTO evidence_kind(name) VALUES ('experimental');
INSERT INTO evidence_kind(name) VALUES ('theoretical');
INSERT INTO evidence_kind(name) VALUES ('philosophical');
INSERT INTO evidence_kind(name) VALUES ('mathematical');
INSERT INTO evidence_kind(name) VALUES ('simulation');
INSERT INTO evidence_kind(name) VALUES ('testimony');
INSERT INTO evidence_kind(name) VALUES ('historical_record');
INSERT INTO intelligence(name,relation_note) VALUES ('human', 'Documented perception, experience, culture, embodiment, language, and values.');
INSERT INTO intelligence(name,relation_note) VALUES ('ai', 'Computation, training, inference, simulation, and language. Consciousness is a research subject, not a status.');
INSERT INTO intelligence(name,relation_note) VALUES ('si', 'Capability-dependent. Empirical criteria required. Consciousness is not an axiom.');
INSERT INTO claim(subject_id,statement,certainty) VALUES (126, 'Consciousness is a research subject. SI consciousness is not an axiom.', 'unresolved');
COMMIT;
