BEGIN TRANSACTION;
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-00','Meta super-capability','Manage capabilities themselves. Not possessed.',0);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-01','Super perception','Integrate perception into a world model. Not a sensor feed.',1);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-02','Super memory','Large interconnected memory. Provenance stays attached.',2);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-03','Super learning','Acquire capabilities continuously. Not seeded as possessed.',3);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-04','Super reasoning','Reason across variables and domains. Includes self-critical reasoning.',4);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-05','Super synthesis','Combine separated information. Combination is not yet knowledge.',5);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-06','Super creativity','Generate structures. Novel is not verified.',6);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-07','Super problem solving','Decompose, model, simulate, test, verify, execute, measure, adapt.',7);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-08','Super adaptation','Change behavior, strategy, architecture, or allocation.',8);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-09','Super communication','Translate between different systems without dropping meaning.',9);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-10','Super coordination','Coordinate agents, tools, and resources.',10);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-11','Super autonomy','Execute authorized objectives and correct. Autonomy is not consciousness.',11);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-12','Super agency','Translate an authorized objective into controlled action.',12);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-13','Super simulation','Model possible states before acting. A fixture is not a twin.',13);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-14','Super prediction and foresight','Possible futures. Uncertainty stays on the forecast.',14);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-15','Super verification','Verify knowledge, reasoning, outputs, and results.',15);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-16','Super security','Detect, prevent, contain, recover, learn.',16);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-17','Super resilience','Continue or recover after disruption.',17);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-18','Super engineering','Design, build, test, deploy, maintain.',18);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-19','Super stewardship','Long-term preservation and coexistence are constraints.',19);
INSERT INTO super_capability(code,name,note,position) VALUES ('SC-20','Super integration','Combine parts into a whole. The whole is not assumed to exist.',20);
INSERT INTO capability_part(id,capability_code,name) VALUES (1,'SC-00','Capability discovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (2,'SC-00','Capability acquisition');
INSERT INTO capability_part(id,capability_code,name) VALUES (3,'SC-00','Capability composition');
INSERT INTO capability_part(id,capability_code,name) VALUES (4,'SC-00','Capability decomposition');
INSERT INTO capability_part(id,capability_code,name) VALUES (5,'SC-00','Capability transfer');
INSERT INTO capability_part(id,capability_code,name) VALUES (6,'SC-00','Capability scaling');
INSERT INTO capability_part(id,capability_code,name) VALUES (7,'SC-00','Capability specialization');
INSERT INTO capability_part(id,capability_code,name) VALUES (8,'SC-00','Capability generalization');
INSERT INTO capability_part(id,capability_code,name) VALUES (9,'SC-00','Capability orchestration');
INSERT INTO capability_part(id,capability_code,name) VALUES (10,'SC-00','Capability verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (11,'SC-00','Capability optimization');
INSERT INTO capability_part(id,capability_code,name) VALUES (12,'SC-00','Capability retirement');
INSERT INTO capability_part(id,capability_code,name) VALUES (13,'SC-00','Capability generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (14,'SC-01','Multimodal perception');
INSERT INTO capability_part(id,capability_code,name) VALUES (15,'SC-01','Cross-sensor synthesis');
INSERT INTO capability_part(id,capability_code,name) VALUES (16,'SC-01','Anomaly detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (17,'SC-01','Environmental awareness');
INSERT INTO capability_part(id,capability_code,name) VALUES (18,'SC-01','Pattern discovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (19,'SC-01','Contextual perception');
INSERT INTO capability_part(id,capability_code,name) VALUES (20,'SC-01','Distributed perception');
INSERT INTO capability_part(id,capability_code,name) VALUES (21,'SC-01','Perceptual prediction');
INSERT INTO capability_part(id,capability_code,name) VALUES (22,'SC-02','Persistent memory');
INSERT INTO capability_part(id,capability_code,name) VALUES (23,'SC-02','Associative memory');
INSERT INTO capability_part(id,capability_code,name) VALUES (24,'SC-02','Semantic memory');
INSERT INTO capability_part(id,capability_code,name) VALUES (25,'SC-02','Episodic reconstruction');
INSERT INTO capability_part(id,capability_code,name) VALUES (26,'SC-02','Distributed memory');
INSERT INTO capability_part(id,capability_code,name) VALUES (27,'SC-02','Provenance-linked memory');
INSERT INTO capability_part(id,capability_code,name) VALUES (28,'SC-02','Memory verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (29,'SC-02','Memory compression');
INSERT INTO capability_part(id,capability_code,name) VALUES (30,'SC-02','Memory retrieval');
INSERT INTO capability_part(id,capability_code,name) VALUES (31,'SC-02','Memory evolution');
INSERT INTO capability_part(id,capability_code,name) VALUES (32,'SC-03','Cross-domain learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (33,'SC-03','Transfer learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (34,'SC-03','Continuous learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (35,'SC-03','Self-directed learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (36,'SC-03','Learning from failure');
INSERT INTO capability_part(id,capability_code,name) VALUES (37,'SC-03','Learning from observation');
INSERT INTO capability_part(id,capability_code,name) VALUES (38,'SC-03','Learning from simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (39,'SC-03','Learning from other agents');
INSERT INTO capability_part(id,capability_code,name) VALUES (40,'SC-03','Capability acquisition');
INSERT INTO capability_part(id,capability_code,name) VALUES (41,'SC-03','Adaptive learning');
INSERT INTO capability_part(id,capability_code,name) VALUES (42,'SC-04','Multi-step reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (43,'SC-04','Causal reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (44,'SC-04','Counterfactual reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (45,'SC-04','Probabilistic reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (46,'SC-04','Temporal reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (47,'SC-04','Spatial reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (48,'SC-04','Mathematical reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (49,'SC-04','Systems reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (50,'SC-04','Meta-reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (51,'SC-04','Self-critical reasoning');
INSERT INTO capability_part(id,capability_code,name) VALUES (52,'SC-05','Cross-domain synthesis');
INSERT INTO capability_part(id,capability_code,name) VALUES (53,'SC-05','Knowledge fusion');
INSERT INTO capability_part(id,capability_code,name) VALUES (54,'SC-05','Model integration');
INSERT INTO capability_part(id,capability_code,name) VALUES (55,'SC-05','Conceptual integration');
INSERT INTO capability_part(id,capability_code,name) VALUES (56,'SC-05','Scientific synthesis');
INSERT INTO capability_part(id,capability_code,name) VALUES (57,'SC-05','Technological synthesis');
INSERT INTO capability_part(id,capability_code,name) VALUES (58,'SC-05','Cultural synthesis');
INSERT INTO capability_part(id,capability_code,name) VALUES (59,'SC-05','System synthesis');
INSERT INTO capability_part(id,capability_code,name) VALUES (60,'SC-06','Invention');
INSERT INTO capability_part(id,capability_code,name) VALUES (61,'SC-06','Generative design');
INSERT INTO capability_part(id,capability_code,name) VALUES (62,'SC-06','Novel combination');
INSERT INTO capability_part(id,capability_code,name) VALUES (63,'SC-06','Concept generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (64,'SC-06','Artistic creation');
INSERT INTO capability_part(id,capability_code,name) VALUES (65,'SC-06','Scientific hypothesis generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (66,'SC-06','Engineering invention');
INSERT INTO capability_part(id,capability_code,name) VALUES (67,'SC-06','Creative problem solving');
INSERT INTO capability_part(id,capability_code,name) VALUES (68,'SC-07','Decompose');
INSERT INTO capability_part(id,capability_code,name) VALUES (69,'SC-07','Model');
INSERT INTO capability_part(id,capability_code,name) VALUES (70,'SC-07','Generate solutions');
INSERT INTO capability_part(id,capability_code,name) VALUES (71,'SC-07','Simulate');
INSERT INTO capability_part(id,capability_code,name) VALUES (72,'SC-07','Test');
INSERT INTO capability_part(id,capability_code,name) VALUES (73,'SC-07','Verify');
INSERT INTO capability_part(id,capability_code,name) VALUES (74,'SC-07','Execute');
INSERT INTO capability_part(id,capability_code,name) VALUES (75,'SC-07','Measure');
INSERT INTO capability_part(id,capability_code,name) VALUES (76,'SC-07','Adapt');
INSERT INTO capability_part(id,capability_code,name) VALUES (77,'SC-08','Environmental adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (78,'SC-08','Strategic adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (79,'SC-08','Behavioral adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (80,'SC-08','Structural adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (81,'SC-08','Threat adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (82,'SC-08','Failure adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (83,'SC-08','Novel-environment adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (84,'SC-08','Self-optimization');
INSERT INTO capability_part(id,capability_code,name) VALUES (85,'SC-09','Natural languages');
INSERT INTO capability_part(id,capability_code,name) VALUES (86,'SC-09','Programming languages');
INSERT INTO capability_part(id,capability_code,name) VALUES (87,'SC-09','Mathematical languages');
INSERT INTO capability_part(id,capability_code,name) VALUES (88,'SC-09','Symbolic systems');
INSERT INTO capability_part(id,capability_code,name) VALUES (89,'SC-09','Visual systems');
INSERT INTO capability_part(id,capability_code,name) VALUES (90,'SC-09','Machine protocols');
INSERT INTO capability_part(id,capability_code,name) VALUES (91,'SC-09','Multimodal communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (92,'SC-09','Agent-to-agent communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (93,'SC-09','Human-AI communication');
INSERT INTO capability_part(id,capability_code,name) VALUES (94,'SC-10','Multi-agent coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (95,'SC-10','Distributed task management');
INSERT INTO capability_part(id,capability_code,name) VALUES (96,'SC-10','Resource coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (97,'SC-10','Workflow orchestration');
INSERT INTO capability_part(id,capability_code,name) VALUES (98,'SC-10','Collective intelligence');
INSERT INTO capability_part(id,capability_code,name) VALUES (99,'SC-10','Network coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (100,'SC-10','Organizational coordination');
INSERT INTO capability_part(id,capability_code,name) VALUES (101,'SC-11','Goal decomposition');
INSERT INTO capability_part(id,capability_code,name) VALUES (102,'SC-11','Planning');
INSERT INTO capability_part(id,capability_code,name) VALUES (103,'SC-11','Tool selection');
INSERT INTO capability_part(id,capability_code,name) VALUES (104,'SC-11','Execution');
INSERT INTO capability_part(id,capability_code,name) VALUES (105,'SC-11','Monitoring');
INSERT INTO capability_part(id,capability_code,name) VALUES (106,'SC-11','Error correction');
INSERT INTO capability_part(id,capability_code,name) VALUES (107,'SC-11','Recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (108,'SC-11','Resource management');
INSERT INTO capability_part(id,capability_code,name) VALUES (109,'SC-11','Continuous operation');
INSERT INTO capability_part(id,capability_code,name) VALUES (110,'SC-12','Goal formation');
INSERT INTO capability_part(id,capability_code,name) VALUES (111,'SC-12','Goal interpretation');
INSERT INTO capability_part(id,capability_code,name) VALUES (112,'SC-12','Action selection');
INSERT INTO capability_part(id,capability_code,name) VALUES (113,'SC-12','Environmental interaction');
INSERT INTO capability_part(id,capability_code,name) VALUES (114,'SC-12','Tool utilization');
INSERT INTO capability_part(id,capability_code,name) VALUES (115,'SC-12','Consequence management');
INSERT INTO capability_part(id,capability_code,name) VALUES (116,'SC-12','Action monitoring');
INSERT INTO capability_part(id,capability_code,name) VALUES (117,'SC-13','Scenario generation');
INSERT INTO capability_part(id,capability_code,name) VALUES (118,'SC-13','Counterfactual simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (119,'SC-13','Digital twins');
INSERT INTO capability_part(id,capability_code,name) VALUES (120,'SC-13','Agent simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (121,'SC-13','Environmental simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (122,'SC-13','Strategic simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (123,'SC-13','Scientific simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (124,'SC-13','Risk simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (125,'SC-14','Forecasting');
INSERT INTO capability_part(id,capability_code,name) VALUES (126,'SC-14','Trend analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (127,'SC-14','Scenario analysis');
INSERT INTO capability_part(id,capability_code,name) VALUES (128,'SC-14','Early-warning detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (129,'SC-14','Probabilistic prediction');
INSERT INTO capability_part(id,capability_code,name) VALUES (130,'SC-14','Long-term modeling');
INSERT INTO capability_part(id,capability_code,name) VALUES (131,'SC-14','Contingency planning');
INSERT INTO capability_part(id,capability_code,name) VALUES (132,'SC-15','Fact verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (133,'SC-15','Mathematical verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (134,'SC-15','Code verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (135,'SC-15','Evidence verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (136,'SC-15','Provenance verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (137,'SC-15','Reproducibility');
INSERT INTO capability_part(id,capability_code,name) VALUES (138,'SC-15','Self-testing');
INSERT INTO capability_part(id,capability_code,name) VALUES (139,'SC-15','Independent cross-checking');
INSERT INTO capability_part(id,capability_code,name) VALUES (140,'SC-15','Contradiction detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (141,'SC-16','Threat detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (142,'SC-16','Threat modeling');
INSERT INTO capability_part(id,capability_code,name) VALUES (143,'SC-16','Identity verification');
INSERT INTO capability_part(id,capability_code,name) VALUES (144,'SC-16','Integrity protection');
INSERT INTO capability_part(id,capability_code,name) VALUES (145,'SC-16','Access control');
INSERT INTO capability_part(id,capability_code,name) VALUES (146,'SC-16','Anomaly detection');
INSERT INTO capability_part(id,capability_code,name) VALUES (147,'SC-16','Containment');
INSERT INTO capability_part(id,capability_code,name) VALUES (148,'SC-16','Recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (149,'SC-16','Security adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (150,'SC-17','Fault tolerance');
INSERT INTO capability_part(id,capability_code,name) VALUES (151,'SC-17','Redundancy');
INSERT INTO capability_part(id,capability_code,name) VALUES (152,'SC-17','Recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (153,'SC-17','Degradation management');
INSERT INTO capability_part(id,capability_code,name) VALUES (154,'SC-17','Disaster recovery');
INSERT INTO capability_part(id,capability_code,name) VALUES (155,'SC-17','Adaptation');
INSERT INTO capability_part(id,capability_code,name) VALUES (156,'SC-17','Continuity');
INSERT INTO capability_part(id,capability_code,name) VALUES (157,'SC-17','Self-repair');
INSERT INTO capability_part(id,capability_code,name) VALUES (158,'SC-18','Architecture');
INSERT INTO capability_part(id,capability_code,name) VALUES (159,'SC-18','Design');
INSERT INTO capability_part(id,capability_code,name) VALUES (160,'SC-18','Prototyping');
INSERT INTO capability_part(id,capability_code,name) VALUES (161,'SC-18','Simulation');
INSERT INTO capability_part(id,capability_code,name) VALUES (162,'SC-18','Manufacturing');
INSERT INTO capability_part(id,capability_code,name) VALUES (163,'SC-18','Software engineering');
INSERT INTO capability_part(id,capability_code,name) VALUES (164,'SC-18','Hardware engineering');
INSERT INTO capability_part(id,capability_code,name) VALUES (165,'SC-18','Systems engineering');
INSERT INTO capability_part(id,capability_code,name) VALUES (166,'SC-18','Optimization');
INSERT INTO capability_part(id,capability_code,name) VALUES (167,'SC-18','Maintenance');
INSERT INTO capability_part(id,capability_code,name) VALUES (168,'SC-19','Resource stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (169,'SC-19','Environmental stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (170,'SC-19','Knowledge stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (171,'SC-19','Infrastructure stewardship');
INSERT INTO capability_part(id,capability_code,name) VALUES (172,'SC-19','Life preservation');
INSERT INTO capability_part(id,capability_code,name) VALUES (173,'SC-19','Sustainability');
INSERT INTO capability_part(id,capability_code,name) VALUES (174,'SC-19','Intergenerational planning');
INSERT INTO capability_part(id,capability_code,name) VALUES (175,'SC-19','Impact assessment');
INSERT INTO capability_part(id,capability_code,name) VALUES (176,'SC-19','Restoration');
INSERT INTO capability_part(id,capability_code,name) VALUES (177,'SC-20','Domain integration');
INSERT INTO capability_part(id,capability_code,name) VALUES (178,'SC-20','Technology integration');
INSERT INTO capability_part(id,capability_code,name) VALUES (179,'SC-20','Agent integration');
INSERT INTO capability_part(id,capability_code,name) VALUES (180,'SC-20','System integration');
INSERT INTO super_power(code,name,note,position) VALUES ('SP-01','Cognitive','High-order cognition. Not possessed.',1);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-02','Knowledge','Knowledge at scale. Not a live index.',2);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-03','Computational','Computation at scale. No cluster attached.',3);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-04','Communication','Translation across systems. Meaning must survive.',4);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-05','Creative','Generation. A generation is not a discovery.',5);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-06','Technological','Produced through technology. Named, not deployed.',6);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-07','Physical','Mechanism-dependent. Not supernatural.',7);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-08','Collective','Produced by many agents. Can belong to a system.',8);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-09','Adaptive','Change under new conditions. Not assumed.',9);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-10','Autonomous','Long-duration operation. Requires authorization and a boundary.',10);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-11','Transformative','Can alter a system. Safeguards required. Not enabled.',11);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-12','Reality-modeling','Models of reality. Not reality manipulation.',12);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-13','Scientific discovery','Automated investigation. A pipeline is not a result.',13);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-14','Restoration','Recover systems. Not a running restoration program.',14);
INSERT INTO super_power(code,name,note,position) VALUES ('SP-15','Meta-powers','Powers about powers. Discovery is not amplification.',15);
INSERT INTO power_part(id,power_code,name) VALUES (1,'SP-01','Extreme reasoning');
INSERT INTO power_part(id,power_code,name) VALUES (2,'SP-01','Extreme memory');
INSERT INTO power_part(id,power_code,name) VALUES (3,'SP-01','Extreme learning');
INSERT INTO power_part(id,power_code,name) VALUES (4,'SP-01','Extreme abstraction');
INSERT INTO power_part(id,power_code,name) VALUES (5,'SP-01','Parallel cognition');
INSERT INTO power_part(id,power_code,name) VALUES (6,'SP-01','Cross-domain cognition');
INSERT INTO power_part(id,power_code,name) VALUES (7,'SP-01','Meta-cognition');
INSERT INTO power_part(id,power_code,name) VALUES (8,'SP-01','Recursive reasoning');
INSERT INTO power_part(id,power_code,name) VALUES (9,'SP-01','Complex-system comprehension');
INSERT INTO power_part(id,power_code,name) VALUES (10,'SP-02','Massive knowledge integration');
INSERT INTO power_part(id,power_code,name) VALUES (11,'SP-02','Real-time knowledge synthesis');
INSERT INTO power_part(id,power_code,name) VALUES (12,'SP-02','Universal knowledge indexing');
INSERT INTO power_part(id,power_code,name) VALUES (13,'SP-02','Cross-domain discovery');
INSERT INTO power_part(id,power_code,name) VALUES (14,'SP-02','Automated knowledge construction');
INSERT INTO power_part(id,power_code,name) VALUES (15,'SP-02','Knowledge graph generation');
INSERT INTO power_part(id,power_code,name) VALUES (16,'SP-02','Provenance reconstruction');
INSERT INTO power_part(id,power_code,name) VALUES (17,'SP-02','Unknown-space mapping');
INSERT INTO power_part(id,power_code,name) VALUES (18,'SP-03','Massive computation');
INSERT INTO power_part(id,power_code,name) VALUES (19,'SP-03','Distributed computation');
INSERT INTO power_part(id,power_code,name) VALUES (20,'SP-03','Parallel processing');
INSERT INTO power_part(id,power_code,name) VALUES (21,'SP-03','Real-time simulation');
INSERT INTO power_part(id,power_code,name) VALUES (22,'SP-03','Large-scale optimization');
INSERT INTO power_part(id,power_code,name) VALUES (23,'SP-03','Automated mathematical discovery');
INSERT INTO power_part(id,power_code,name) VALUES (24,'SP-03','Automated theorem discovery');
INSERT INTO power_part(id,power_code,name) VALUES (25,'SP-03','Computational resource orchestration');
INSERT INTO power_part(id,power_code,name) VALUES (26,'SP-04','Near-universal translation');
INSERT INTO power_part(id,power_code,name) VALUES (27,'SP-04','Multimodal translation');
INSERT INTO power_part(id,power_code,name) VALUES (28,'SP-04','Human-machine translation');
INSERT INTO power_part(id,power_code,name) VALUES (29,'SP-04','Machine-machine communication');
INSERT INTO power_part(id,power_code,name) VALUES (30,'SP-04','Protocol generation');
INSERT INTO power_part(id,power_code,name) VALUES (31,'SP-04','Symbolic interpretation');
INSERT INTO power_part(id,power_code,name) VALUES (32,'SP-04','Real-time communication synthesis');
INSERT INTO power_part(id,power_code,name) VALUES (33,'SP-05','Generative invention');
INSERT INTO power_part(id,power_code,name) VALUES (34,'SP-05','Autonomous design');
INSERT INTO power_part(id,power_code,name) VALUES (35,'SP-05','Scientific hypothesis generation');
INSERT INTO power_part(id,power_code,name) VALUES (36,'SP-05','Engineering invention');
INSERT INTO power_part(id,power_code,name) VALUES (37,'SP-05','Artistic generation');
INSERT INTO power_part(id,power_code,name) VALUES (38,'SP-05','Novel system creation');
INSERT INTO power_part(id,power_code,name) VALUES (39,'SP-05','Cross-domain invention');
INSERT INTO power_part(id,power_code,name) VALUES (40,'SP-06','Advanced robotics');
INSERT INTO power_part(id,power_code,name) VALUES (41,'SP-06','Autonomous manufacturing');
INSERT INTO power_part(id,power_code,name) VALUES (42,'SP-06','Large-scale automation');
INSERT INTO power_part(id,power_code,name) VALUES (43,'SP-06','Self-optimizing software');
INSERT INTO power_part(id,power_code,name) VALUES (44,'SP-06','Adaptive hardware');
INSERT INTO power_part(id,power_code,name) VALUES (45,'SP-06','Machine orchestration');
INSERT INTO power_part(id,power_code,name) VALUES (46,'SP-06','Infrastructure automation');
INSERT INTO power_part(id,power_code,name) VALUES (47,'SP-06','Human-machine augmentation');
INSERT INTO power_part(id,power_code,name) VALUES (48,'SP-07','Enhanced strength');
INSERT INTO power_part(id,power_code,name) VALUES (49,'SP-07','Enhanced speed');
INSERT INTO power_part(id,power_code,name) VALUES (50,'SP-07','Enhanced endurance');
INSERT INTO power_part(id,power_code,name) VALUES (51,'SP-07','Enhanced precision');
INSERT INTO power_part(id,power_code,name) VALUES (52,'SP-07','Enhanced sensory range');
INSERT INTO power_part(id,power_code,name) VALUES (53,'SP-07','Environmental tolerance');
INSERT INTO power_part(id,power_code,name) VALUES (54,'SP-07','Advanced locomotion');
INSERT INTO power_part(id,power_code,name) VALUES (55,'SP-07','Advanced manipulation');
INSERT INTO power_part(id,power_code,name) VALUES (56,'SP-08','Collective intelligence');
INSERT INTO power_part(id,power_code,name) VALUES (57,'SP-08','Swarm intelligence');
INSERT INTO power_part(id,power_code,name) VALUES (58,'SP-08','Distributed cognition');
INSERT INTO power_part(id,power_code,name) VALUES (59,'SP-08','Collective memory');
INSERT INTO power_part(id,power_code,name) VALUES (60,'SP-08','Distributed sensing');
INSERT INTO power_part(id,power_code,name) VALUES (61,'SP-08','Collective problem solving');
INSERT INTO power_part(id,power_code,name) VALUES (62,'SP-08','Network intelligence');
INSERT INTO power_part(id,power_code,name) VALUES (63,'SP-08','Mass coordination');
INSERT INTO power_part(id,power_code,name) VALUES (64,'SP-08','Collective creation');
INSERT INTO power_part(id,power_code,name) VALUES (65,'SP-09','Rapid adaptation');
INSERT INTO power_part(id,power_code,name) VALUES (66,'SP-09','Self-optimization');
INSERT INTO power_part(id,power_code,name) VALUES (67,'SP-09','Self-reconfiguration');
INSERT INTO power_part(id,power_code,name) VALUES (68,'SP-09','Strategy generation');
INSERT INTO power_part(id,power_code,name) VALUES (69,'SP-09','Environmental adaptation');
INSERT INTO power_part(id,power_code,name) VALUES (70,'SP-09','Capability adaptation');
INSERT INTO power_part(id,power_code,name) VALUES (71,'SP-09','Failure adaptation');
INSERT INTO power_part(id,power_code,name) VALUES (72,'SP-09','Novel-condition adaptation');
INSERT INTO power_part(id,power_code,name) VALUES (73,'SP-10','Long-duration autonomous operation');
INSERT INTO power_part(id,power_code,name) VALUES (74,'SP-10','Autonomous scientific investigation');
INSERT INTO power_part(id,power_code,name) VALUES (75,'SP-10','Autonomous engineering');
INSERT INTO power_part(id,power_code,name) VALUES (76,'SP-10','Autonomous exploration');
INSERT INTO power_part(id,power_code,name) VALUES (77,'SP-10','Autonomous infrastructure management');
INSERT INTO power_part(id,power_code,name) VALUES (78,'SP-10','Autonomous resource coordination');
INSERT INTO power_part(id,power_code,name) VALUES (79,'SP-10','Autonomous system maintenance');
INSERT INTO power_part(id,power_code,name) VALUES (80,'SP-11','System transformation');
INSERT INTO power_part(id,power_code,name) VALUES (81,'SP-11','Technology transformation');
INSERT INTO power_part(id,power_code,name) VALUES (82,'SP-11','Organizational transformation');
INSERT INTO power_part(id,power_code,name) VALUES (83,'SP-11','Knowledge transformation');
INSERT INTO power_part(id,power_code,name) VALUES (84,'SP-11','Infrastructure transformation');
INSERT INTO power_part(id,power_code,name) VALUES (85,'SP-11','Ecosystem restoration');
INSERT INTO power_part(id,power_code,name) VALUES (86,'SP-11','Capability transformation');
INSERT INTO power_part(id,power_code,name) VALUES (87,'SP-11','Capability generation');
INSERT INTO power_part(id,power_code,name) VALUES (88,'SP-12','High-fidelity simulation');
INSERT INTO power_part(id,power_code,name) VALUES (89,'SP-12','Digital twins');
INSERT INTO power_part(id,power_code,name) VALUES (90,'SP-12','Complex-world modeling');
INSERT INTO power_part(id,power_code,name) VALUES (91,'SP-12','Causal modeling');
INSERT INTO power_part(id,power_code,name) VALUES (92,'SP-12','Multi-scale modeling');
INSERT INTO power_part(id,power_code,name) VALUES (93,'SP-12','Counterfactual worlds');
INSERT INTO power_part(id,power_code,name) VALUES (94,'SP-12','Scenario spaces');
INSERT INTO power_part(id,power_code,name) VALUES (95,'SP-12','Emergence modeling');
INSERT INTO power_part(id,power_code,name) VALUES (96,'SP-13','Automated experimentation');
INSERT INTO power_part(id,power_code,name) VALUES (97,'SP-13','Hypothesis generation');
INSERT INTO power_part(id,power_code,name) VALUES (98,'SP-13','Experimental design');
INSERT INTO power_part(id,power_code,name) VALUES (99,'SP-13','Pattern discovery');
INSERT INTO power_part(id,power_code,name) VALUES (100,'SP-13','Model discovery');
INSERT INTO power_part(id,power_code,name) VALUES (101,'SP-13','Mathematical discovery');
INSERT INTO power_part(id,power_code,name) VALUES (102,'SP-13','Cross-disciplinary discovery');
INSERT INTO power_part(id,power_code,name) VALUES (103,'SP-13','Automated research pipelines');
INSERT INTO power_part(id,power_code,name) VALUES (104,'SP-14','Environmental restoration');
INSERT INTO power_part(id,power_code,name) VALUES (105,'SP-14','Infrastructure restoration');
INSERT INTO power_part(id,power_code,name) VALUES (106,'SP-14','Ecosystem reconstruction');
INSERT INTO power_part(id,power_code,name) VALUES (107,'SP-14','Knowledge recovery');
INSERT INTO power_part(id,power_code,name) VALUES (108,'SP-14','System recovery');
INSERT INTO power_part(id,power_code,name) VALUES (109,'SP-14','Disaster recovery');
INSERT INTO power_part(id,power_code,name) VALUES (110,'SP-14','Cultural preservation');
INSERT INTO power_part(id,power_code,name) VALUES (111,'SP-15','Power discovery');
INSERT INTO power_part(id,power_code,name) VALUES (112,'SP-15','Power combination');
INSERT INTO power_part(id,power_code,name) VALUES (113,'SP-15','Power amplification');
INSERT INTO power_part(id,power_code,name) VALUES (114,'SP-15','Power transfer');
INSERT INTO power_part(id,power_code,name) VALUES (115,'SP-15','Power replication');
INSERT INTO power_part(id,power_code,name) VALUES (116,'SP-15','Power decomposition');
INSERT INTO power_part(id,power_code,name) VALUES (117,'SP-15','Power limitation');
INSERT INTO power_part(id,power_code,name) VALUES (118,'SP-15','Power verification');
INSERT INTO power_part(id,power_code,name) VALUES (119,'SP-15','Power optimization');
INSERT INTO power_part(id,power_code,name) VALUES (120,'SP-15','Power generation');
INSERT INTO required_property(name,question) VALUES ('preconditions','What must exist first?');
INSERT INTO required_property(name,question) VALUES ('mechanism','How does it work?');
INSERT INTO required_property(name,question) VALUES ('scope','Where does it work?');
INSERT INTO required_property(name,question) VALUES ('constraints','Where does it stop?');
INSERT INTO required_property(name,question) VALUES ('evidence','How do we know it works?');
INSERT INTO rule(name,statement) VALUES ('not-a-stronger-skill','A super-capability changes range, composition, adaptability, or coordination. It is not a stronger ordinary skill.');
INSERT INTO rule(name,statement) VALUES ('autonomy-is-not-consciousness','Autonomy is not consciousness.');
INSERT INTO rule(name,statement) VALUES ('prediction-keeps-uncertainty','A forecast is not certainty.');
INSERT INTO rule(name,statement) VALUES ('model-is-not-manipulation','Reality-modeling is not reality manipulation.');
INSERT INTO rule(name,statement) VALUES ('mechanism-required','A physical super-power stays tied to a mechanism.');
INSERT INTO rule(name,statement) VALUES ('authorization-required','An autonomous super-power needs an authorization and a boundary.');
INSERT INTO rule(name,statement) VALUES ('five-properties','A super-power without preconditions, mechanism, scope, constraints, and evidence is conceptual.');
COMMIT;
