BEGIN TRANSACTION;
INSERT INTO magic_layer(code,name,note,position) VALUES ('M0','Magic meta-structure','Define and reason about a magical system. Not a claim the system is real.',0);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M1','Source','Claimed origin of an effect. Claimed is not verified.',1);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M2','Resource','A resource alleged or fictional. Not assumed physically real.',2);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M3','Intent','Intent is part of the represented mechanism. Authorization still applies.',3);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M4','Focus','How intent is directed in the representation.',4);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M5','Operation','A discrete represented operation. Intent, focus, method, resource, target, transformation, effect.',5);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M6','Domain','Elemental, life, mind, spatial, temporal, transformation, information, reality-model.',6);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M7','Structure','Circles, runes, rituals, networks. A named circle is a representation.',7);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M8','Rule','Conservation, cost, range, duration, precision, reversibility, failure.',8);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M9','Magical capability','A class of operations inside a defined system. Not possessed.',9);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M10','Magical super-capability','Combined operations. Not demonstrated.',10);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M11','Magical power','An effect through a magical framework. Not a physical measurement.',11);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M12','Magical super-power','System-level names. Infinite means unbounded in a fiction, bound unknown here.',12);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M13','Mechanism hybrid','Magic with technology, computation, biology, information, or a consciousness model.',13);
INSERT INTO magic_layer(code,name,note,position) VALUES ('M14','Evidence boundary','Representation is not proof.',14);
INSERT INTO magic_item(id,layer_code,name) VALUES (1,'M0','Magic classification');
INSERT INTO magic_item(id,layer_code,name) VALUES (2,'M0','Magic-system construction');
INSERT INTO magic_item(id,layer_code,name) VALUES (3,'M0','Rule definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (4,'M0','Mechanism definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (5,'M0','Spell definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (6,'M0','Effect definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (7,'M0','Cost definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (8,'M0','Limitation definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (9,'M0','Symbol definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (10,'M0','Ritual definition');
INSERT INTO magic_item(id,layer_code,name) VALUES (11,'M0','Verification');
INSERT INTO magic_item(id,layer_code,name) VALUES (12,'M0','Provenance');
INSERT INTO magic_item(id,layer_code,name) VALUES (13,'M1','Self');
INSERT INTO magic_item(id,layer_code,name) VALUES (14,'M1','Biological');
INSERT INTO magic_item(id,layer_code,name) VALUES (15,'M1','Environmental');
INSERT INTO magic_item(id,layer_code,name) VALUES (16,'M1','Elemental');
INSERT INTO magic_item(id,layer_code,name) VALUES (17,'M1','Spiritual');
INSERT INTO magic_item(id,layer_code,name) VALUES (18,'M1','Divine');
INSERT INTO magic_item(id,layer_code,name) VALUES (19,'M1','Cosmic');
INSERT INTO magic_item(id,layer_code,name) VALUES (20,'M1','Dimensional');
INSERT INTO magic_item(id,layer_code,name) VALUES (21,'M1','Relational');
INSERT INTO magic_item(id,layer_code,name) VALUES (22,'M1','Collective');
INSERT INTO magic_item(id,layer_code,name) VALUES (23,'M1','Artifact');
INSERT INTO magic_item(id,layer_code,name) VALUES (24,'M1','Technological');
INSERT INTO magic_item(id,layer_code,name) VALUES (25,'M1','Unknown');
INSERT INTO magic_item(id,layer_code,name) VALUES (26,'M2','Mana');
INSERT INTO magic_item(id,layer_code,name) VALUES (27,'M2','Life force');
INSERT INTO magic_item(id,layer_code,name) VALUES (28,'M2','Energy');
INSERT INTO magic_item(id,layer_code,name) VALUES (29,'M2','Spirit');
INSERT INTO magic_item(id,layer_code,name) VALUES (30,'M2','Resonance');
INSERT INTO magic_item(id,layer_code,name) VALUES (31,'M2','Will');
INSERT INTO magic_item(id,layer_code,name) VALUES (32,'M2','Emotion');
INSERT INTO magic_item(id,layer_code,name) VALUES (33,'M2','Knowledge');
INSERT INTO magic_item(id,layer_code,name) VALUES (34,'M2','Time');
INSERT INTO magic_item(id,layer_code,name) VALUES (35,'M2','Matter');
INSERT INTO magic_item(id,layer_code,name) VALUES (36,'M2','Information');
INSERT INTO magic_item(id,layer_code,name) VALUES (37,'M2','Attention');
INSERT INTO magic_item(id,layer_code,name) VALUES (38,'M2','Environmental energy');
INSERT INTO magic_item(id,layer_code,name) VALUES (39,'M2','Artifact charge');
INSERT INTO magic_item(id,layer_code,name) VALUES (40,'M3','Goal');
INSERT INTO magic_item(id,layer_code,name) VALUES (41,'M3','Desired outcome');
INSERT INTO magic_item(id,layer_code,name) VALUES (42,'M3','Target');
INSERT INTO magic_item(id,layer_code,name) VALUES (43,'M3','Scope');
INSERT INTO magic_item(id,layer_code,name) VALUES (44,'M3','Conditions');
INSERT INTO magic_item(id,layer_code,name) VALUES (45,'M3','User intent');
INSERT INTO magic_item(id,layer_code,name) VALUES (46,'M3','Symbolic intent');
INSERT INTO magic_item(id,layer_code,name) VALUES (47,'M3','Emotional state');
INSERT INTO magic_item(id,layer_code,name) VALUES (48,'M3','Authorization');
INSERT INTO magic_item(id,layer_code,name) VALUES (49,'M3','Constraints');
INSERT INTO magic_item(id,layer_code,name) VALUES (50,'M4','Mind');
INSERT INTO magic_item(id,layer_code,name) VALUES (51,'M4','Voice');
INSERT INTO magic_item(id,layer_code,name) VALUES (52,'M4','Gesture');
INSERT INTO magic_item(id,layer_code,name) VALUES (53,'M4','Symbol');
INSERT INTO magic_item(id,layer_code,name) VALUES (54,'M4','Rune');
INSERT INTO magic_item(id,layer_code,name) VALUES (55,'M4','Circle');
INSERT INTO magic_item(id,layer_code,name) VALUES (56,'M4','Artifact');
INSERT INTO magic_item(id,layer_code,name) VALUES (57,'M4','Weapon');
INSERT INTO magic_item(id,layer_code,name) VALUES (58,'M4','Crystal');
INSERT INTO magic_item(id,layer_code,name) VALUES (59,'M4','Technology');
INSERT INTO magic_item(id,layer_code,name) VALUES (60,'M4','Location');
INSERT INTO magic_item(id,layer_code,name) VALUES (61,'M4','Ritual');
INSERT INTO magic_item(id,layer_code,name) VALUES (62,'M4','Music');
INSERT INTO magic_item(id,layer_code,name) VALUES (63,'M4','Movement');
INSERT INTO magic_item(id,layer_code,name) VALUES (64,'M4','Collective action');
INSERT INTO magic_item(id,layer_code,name) VALUES (65,'M5','Creation');
INSERT INTO magic_item(id,layer_code,name) VALUES (66,'M5','Destruction');
INSERT INTO magic_item(id,layer_code,name) VALUES (67,'M5','Transformation');
INSERT INTO magic_item(id,layer_code,name) VALUES (68,'M5','Protection');
INSERT INTO magic_item(id,layer_code,name) VALUES (69,'M5','Healing');
INSERT INTO magic_item(id,layer_code,name) VALUES (70,'M5','Movement');
INSERT INTO magic_item(id,layer_code,name) VALUES (71,'M5','Perception');
INSERT INTO magic_item(id,layer_code,name) VALUES (72,'M5','Communication');
INSERT INTO magic_item(id,layer_code,name) VALUES (73,'M5','Summoning');
INSERT INTO magic_item(id,layer_code,name) VALUES (74,'M5','Binding');
INSERT INTO magic_item(id,layer_code,name) VALUES (75,'M5','Concealment');
INSERT INTO magic_item(id,layer_code,name) VALUES (76,'M5','Revelation');
INSERT INTO magic_item(id,layer_code,name) VALUES (77,'M5','Manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (78,'M5','Restoration');
INSERT INTO magic_item(id,layer_code,name) VALUES (79,'M6','Fire');
INSERT INTO magic_item(id,layer_code,name) VALUES (80,'M6','Water');
INSERT INTO magic_item(id,layer_code,name) VALUES (81,'M6','Earth');
INSERT INTO magic_item(id,layer_code,name) VALUES (82,'M6','Air');
INSERT INTO magic_item(id,layer_code,name) VALUES (83,'M6','Lightning');
INSERT INTO magic_item(id,layer_code,name) VALUES (84,'M6','Ice');
INSERT INTO magic_item(id,layer_code,name) VALUES (85,'M6','Metal');
INSERT INTO magic_item(id,layer_code,name) VALUES (86,'M6','Wood');
INSERT INTO magic_item(id,layer_code,name) VALUES (87,'M6','Nature');
INSERT INTO magic_item(id,layer_code,name) VALUES (88,'M6','Spirit');
INSERT INTO magic_item(id,layer_code,name) VALUES (89,'M6','Growth');
INSERT INTO magic_item(id,layer_code,name) VALUES (90,'M6','Regeneration');
INSERT INTO magic_item(id,layer_code,name) VALUES (91,'M6','Vitality');
INSERT INTO magic_item(id,layer_code,name) VALUES (92,'M6','Preservation');
INSERT INTO magic_item(id,layer_code,name) VALUES (93,'M6','Dream');
INSERT INTO magic_item(id,layer_code,name) VALUES (94,'M6','Illusion');
INSERT INTO magic_item(id,layer_code,name) VALUES (95,'M6','Attention');
INSERT INTO magic_item(id,layer_code,name) VALUES (96,'M6','Emotion');
INSERT INTO magic_item(id,layer_code,name) VALUES (97,'M6','Cognition');
INSERT INTO magic_item(id,layer_code,name) VALUES (98,'M6','Teleportation');
INSERT INTO magic_item(id,layer_code,name) VALUES (99,'M6','Spatial folding');
INSERT INTO magic_item(id,layer_code,name) VALUES (100,'M6','Portals');
INSERT INTO magic_item(id,layer_code,name) VALUES (101,'M6','Dimensional movement');
INSERT INTO magic_item(id,layer_code,name) VALUES (102,'M6','Containment');
INSERT INTO magic_item(id,layer_code,name) VALUES (103,'M6','Time perception');
INSERT INTO magic_item(id,layer_code,name) VALUES (104,'M6','Temporal manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (105,'M6','Time acceleration');
INSERT INTO magic_item(id,layer_code,name) VALUES (106,'M6','Time slowing');
INSERT INTO magic_item(id,layer_code,name) VALUES (107,'M6','Temporal displacement');
INSERT INTO magic_item(id,layer_code,name) VALUES (108,'M6','Transmutation');
INSERT INTO magic_item(id,layer_code,name) VALUES (109,'M6','Shape change');
INSERT INTO magic_item(id,layer_code,name) VALUES (110,'M6','Material transformation');
INSERT INTO magic_item(id,layer_code,name) VALUES (111,'M6','Energy transformation');
INSERT INTO magic_item(id,layer_code,name) VALUES (112,'M6','State transformation');
INSERT INTO magic_item(id,layer_code,name) VALUES (113,'M6','Knowledge revelation');
INSERT INTO magic_item(id,layer_code,name) VALUES (114,'M6','Information encoding');
INSERT INTO magic_item(id,layer_code,name) VALUES (115,'M6','Information transfer');
INSERT INTO magic_item(id,layer_code,name) VALUES (116,'M6','Information concealment');
INSERT INTO magic_item(id,layer_code,name) VALUES (117,'M6','Pattern revelation');
INSERT INTO magic_item(id,layer_code,name) VALUES (118,'M6','Symbolic transformation');
INSERT INTO magic_item(id,layer_code,name) VALUES (119,'M6','Manifestation');
INSERT INTO magic_item(id,layer_code,name) VALUES (120,'M6','Reality alteration');
INSERT INTO magic_item(id,layer_code,name) VALUES (121,'M6','Probability manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (122,'M6','Causality manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (123,'M6','World generation');
INSERT INTO magic_item(id,layer_code,name) VALUES (124,'M7','Circle');
INSERT INTO magic_item(id,layer_code,name) VALUES (125,'M7','Rune system');
INSERT INTO magic_item(id,layer_code,name) VALUES (126,'M7','Grimoire');
INSERT INTO magic_item(id,layer_code,name) VALUES (127,'M7','Ritual');
INSERT INTO magic_item(id,layer_code,name) VALUES (128,'M7','Spellbook');
INSERT INTO magic_item(id,layer_code,name) VALUES (129,'M7','Magical language');
INSERT INTO magic_item(id,layer_code,name) VALUES (130,'M7','Symbolic grammar');
INSERT INTO magic_item(id,layer_code,name) VALUES (131,'M7','Artifact system');
INSERT INTO magic_item(id,layer_code,name) VALUES (132,'M7','Magical network');
INSERT INTO magic_item(id,layer_code,name) VALUES (133,'M7','Leyline model');
INSERT INTO magic_item(id,layer_code,name) VALUES (134,'M7','Portal network');
INSERT INTO magic_item(id,layer_code,name) VALUES (135,'M7','Domain');
INSERT INTO magic_item(id,layer_code,name) VALUES (136,'M7','Realm');
INSERT INTO magic_item(id,layer_code,name) VALUES (137,'M8','Conservation');
INSERT INTO magic_item(id,layer_code,name) VALUES (138,'M8','Compatibility');
INSERT INTO magic_item(id,layer_code,name) VALUES (139,'M8','Limitation');
INSERT INTO magic_item(id,layer_code,name) VALUES (140,'M8','Cost');
INSERT INTO magic_item(id,layer_code,name) VALUES (141,'M8','Range');
INSERT INTO magic_item(id,layer_code,name) VALUES (142,'M8','Duration');
INSERT INTO magic_item(id,layer_code,name) VALUES (143,'M8','Precision');
INSERT INTO magic_item(id,layer_code,name) VALUES (144,'M8','Reversibility');
INSERT INTO magic_item(id,layer_code,name) VALUES (145,'M8','Failure');
INSERT INTO magic_item(id,layer_code,name) VALUES (146,'M8','Interaction');
INSERT INTO magic_item(id,layer_code,name) VALUES (147,'M9','Fire generation');
INSERT INTO magic_item(id,layer_code,name) VALUES (148,'M9','Healing');
INSERT INTO magic_item(id,layer_code,name) VALUES (149,'M9','Teleportation');
INSERT INTO magic_item(id,layer_code,name) VALUES (150,'M9','Illusion creation');
INSERT INTO magic_item(id,layer_code,name) VALUES (151,'M9','Portal creation');
INSERT INTO magic_item(id,layer_code,name) VALUES (152,'M9','Transformation');
INSERT INTO magic_item(id,layer_code,name) VALUES (153,'M9','Divination');
INSERT INTO magic_item(id,layer_code,name) VALUES (154,'M9','Summoning');
INSERT INTO magic_item(id,layer_code,name) VALUES (155,'M9','Protection');
INSERT INTO magic_item(id,layer_code,name) VALUES (156,'M9','Energy manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (157,'M10','Arcane synthesis');
INSERT INTO magic_item(id,layer_code,name) VALUES (158,'M10','Reality modeling');
INSERT INTO magic_item(id,layer_code,name) VALUES (159,'M10','Dimensional navigation');
INSERT INTO magic_item(id,layer_code,name) VALUES (160,'M10','Transmutation mastery');
INSERT INTO magic_item(id,layer_code,name) VALUES (161,'M10','Universal spellcraft');
INSERT INTO magic_item(id,layer_code,name) VALUES (162,'M10','Magical adaptation');
INSERT INTO magic_item(id,layer_code,name) VALUES (163,'M10','Magical automation');
INSERT INTO magic_item(id,layer_code,name) VALUES (164,'M10','Magical integration');
INSERT INTO magic_item(id,layer_code,name) VALUES (165,'M11','Telekinesis');
INSERT INTO magic_item(id,layer_code,name) VALUES (166,'M11','Telepathy');
INSERT INTO magic_item(id,layer_code,name) VALUES (167,'M11','Teleportation');
INSERT INTO magic_item(id,layer_code,name) VALUES (168,'M11','Clairvoyance');
INSERT INTO magic_item(id,layer_code,name) VALUES (169,'M11','Precognition');
INSERT INTO magic_item(id,layer_code,name) VALUES (170,'M11','Shapeshifting');
INSERT INTO magic_item(id,layer_code,name) VALUES (171,'M11','Elemental manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (172,'M11','Healing');
INSERT INTO magic_item(id,layer_code,name) VALUES (173,'M11','Regeneration');
INSERT INTO magic_item(id,layer_code,name) VALUES (174,'M11','Summoning');
INSERT INTO magic_item(id,layer_code,name) VALUES (175,'M11','Dimensional travel');
INSERT INTO magic_item(id,layer_code,name) VALUES (176,'M11','Time manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (177,'M11','Illusion');
INSERT INTO magic_item(id,layer_code,name) VALUES (178,'M11','Transmutation');
INSERT INTO magic_item(id,layer_code,name) VALUES (179,'M11','Energy manipulation');
INSERT INTO magic_item(id,layer_code,name) VALUES (180,'M11','Reality alteration');
INSERT INTO magic_item(id,layer_code,name) VALUES (181,'M12','Reality transformation');
INSERT INTO magic_item(id,layer_code,name) VALUES (182,'M12','Dimensional creation');
INSERT INTO magic_item(id,layer_code,name) VALUES (183,'M12','Universal transmutation');
INSERT INTO magic_item(id,layer_code,name) VALUES (184,'M12','Temporal dominion');
INSERT INTO magic_item(id,layer_code,name) VALUES (185,'M12','Universal communication');
INSERT INTO magic_item(id,layer_code,name) VALUES (186,'M12','Life restoration');
INSERT INTO magic_item(id,layer_code,name) VALUES (187,'M12','Autonomous spell generation');
INSERT INTO magic_item(id,layer_code,name) VALUES (188,'M12','Magical reality engineering');
INSERT INTO magic_item(id,layer_code,name) VALUES (189,'M12','Unbounded magic');
INSERT INTO magic_item(id,layer_code,name) VALUES (190,'M13','Technomagic');
INSERT INTO magic_item(id,layer_code,name) VALUES (191,'M13','Computational magic');
INSERT INTO magic_item(id,layer_code,name) VALUES (192,'M13','Biomagic');
INSERT INTO magic_item(id,layer_code,name) VALUES (193,'M13','Information magic');
INSERT INTO magic_item(id,layer_code,name) VALUES (194,'M13','Consciousness-model magic');
INSERT INTO source_status(name) VALUES ('claimed_source');
INSERT INTO source_status(name) VALUES ('observed_source');
INSERT INTO source_status(name) VALUES ('modeled_source');
INSERT INTO source_status(name) VALUES ('verified_source');
INSERT INTO source_status(name) VALUES ('unknown_source');
INSERT INTO evidence_class(name,meaning,position) VALUES ('Mythological','Exists within mythology.',1);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Fictional','Exists within fiction.',2);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Symbolic','Represents an idea or process.',3);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Ritual','Exists as a cultural or practical practice.',4);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Hypothetical','Proposed but unverified.',5);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Experimental','Being investigated.',6);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Observed','An observation has been recorded.',7);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Reproducible','Repeated under defined conditions.',8);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Verified','Evidence supports the mechanism.',9);
INSERT INTO evidence_class(name,meaning,position) VALUES ('Unknown','Insufficient evidence.',10);
INSERT INTO hybrid(name,note) VALUES ('technomagic','Magic plus technology. Mechanism domain, not a deployed system.');
INSERT INTO hybrid(name,note) VALUES ('computational-magic','Magic plus computation. Not a running spell engine.');
INSERT INTO hybrid(name,note) VALUES ('biomagic','Magic plus biology. Not a biological claim.');
INSERT INTO hybrid(name,note) VALUES ('information-magic','Magic plus information.');
INSERT INTO hybrid(name,note) VALUES ('consciousness-model-magic','A consciousness model. Not a claim that consciousness is magical or that SI is conscious.');
INSERT INTO rule(name,statement) VALUES ('representation-is-not-proof','Representation of magic is not proof of magic.');
INSERT INTO rule(name,statement) VALUES ('resource-not-physical-by-default','A named resource is not a physical quantity.');
INSERT INTO rule(name,statement) VALUES ('temporal-is-construct','Temporal and reality-model rows are fictional or theoretical unless evidence says otherwise.');
INSERT INTO rule(name,statement) VALUES ('unbounded-bound-unknown','Unbounded magic is a classification. The bound is unknown unless demonstrated in the applicable model.');
INSERT INTO rule(name,statement) VALUES ('source-status-required','A source is claimed, observed, modeled, verified, or unknown. Those are not the same.');
COMMIT;
