BEGIN TRANSACTION;
INSERT INTO layer_kind(name,meaning) VALUES ('knowledge','What an entity knows.');
INSERT INTO layer_kind(name,meaning) VALUES ('skill','What an entity can learn to perform.');
INSERT INTO layer_kind(name,meaning) VALUES ('super-knowledge','Integrated, cross-domain understanding.');
INSERT INTO layer_kind(name,meaning) VALUES ('super-skill','Ability to coordinate and adapt many skills.');
INSERT INTO layer_kind(name,meaning) VALUES ('capability','What an entity is structurally able to accomplish.');
INSERT INTO layer_kind(name,meaning) VALUES ('super-capability','A high-order capability from integrating capabilities.');
INSERT INTO layer_kind(name,meaning) VALUES ('power','A capability that materially expands possible actions or effects.');
INSERT INTO layer_kind(name,meaning) VALUES ('super-power','An unusually broad or system-level power.');
INSERT INTO capability_category(code,name,note,position) VALUES ('C0','Meta-capabilities','Capabilities governing other capabilities.',0);
INSERT INTO capability_category(code,name,note,position) VALUES ('C1','Perceptual','Acquire information. Possession is not assumed.',1);
INSERT INTO capability_category(code,name,note,position) VALUES ('C2','Cognitive','Internal processing.',2);
INSERT INTO capability_category(code,name,note,position) VALUES ('C3','Memory','Retention and retrieval. Not proof of experience.',3);
INSERT INTO capability_category(code,name,note,position) VALUES ('C4','Learning','Acquire or modify capability.',4);
INSERT INTO capability_category(code,name,note,position) VALUES ('C5','Creative','Generate structures. Novel is not verified.',5);
INSERT INTO capability_category(code,name,note,position) VALUES ('C6','Communication','Transmit meaning across agents and protocols.',6);
INSERT INTO capability_category(code,name,note,position) VALUES ('C7','Problem-solving','Identify, decompose, test, recover.',7);
INSERT INTO capability_category(code,name,note,position) VALUES ('C8','Decision','Select under uncertainty. Not a prediction.',8);
INSERT INTO capability_category(code,name,note,position) VALUES ('C9','Action and execution','Physical or digital action. Knowing is not doing.',9);
INSERT INTO capability_category(code,name,note,position) VALUES ('C10','Technical','Engineered systems.',10);
INSERT INTO capability_category(code,name,note,position) VALUES ('C11','Social and collective','Many entities. Does not imply a shared mind.',11);
INSERT INTO capability_category(code,name,note,position) VALUES ('C12','Autonomous','Independent operation. Does not imply consciousness, personhood, or moral agency.',12);
INSERT INTO capability_category(code,name,note,position) VALUES ('C13','Adaptive','Change strategy or structure when conditions change.',13);
INSERT INTO capability_category(code,name,note,position) VALUES ('C14','Systems','Model and orchestrate interconnected systems.',14);
INSERT INTO capability_category(code,name,note,position) VALUES ('C15','Temporal','History, real time, forecast. Forecast is not certainty.',15);
INSERT INTO capability_category(code,name,note,position) VALUES ('C16','Spatial','Navigation, mapping, geometry.',16);
INSERT INTO capability_category(code,name,note,position) VALUES ('C17','Resource','Detect and allocate resources.',17);
INSERT INTO capability_category(code,name,note,position) VALUES ('C18','Security and resilience','Detect, protect, recover.',18);
INSERT INTO capability_category(code,name,note,position) VALUES ('C19','Ethical and stewardship','Harm, consent, reversibility, coexistence.',19);
INSERT INTO capability(id,category_code,name) VALUES (1,'C0','Capability acquisition');
INSERT INTO capability(id,category_code,name) VALUES (2,'C0','Capability combination');
INSERT INTO capability(id,category_code,name) VALUES (3,'C0','Capability composition');
INSERT INTO capability(id,category_code,name) VALUES (4,'C0','Capability decomposition');
INSERT INTO capability(id,category_code,name) VALUES (5,'C0','Capability transfer');
INSERT INTO capability(id,category_code,name) VALUES (6,'C0','Capability scaling');
INSERT INTO capability(id,category_code,name) VALUES (7,'C0','Capability specialization');
INSERT INTO capability(id,category_code,name) VALUES (8,'C0','Capability generalization');
INSERT INTO capability(id,category_code,name) VALUES (9,'C0','Capability monitoring');
INSERT INTO capability(id,category_code,name) VALUES (10,'C0','Capability verification');
INSERT INTO capability(id,category_code,name) VALUES (11,'C0','Capability limitation');
INSERT INTO capability(id,category_code,name) VALUES (12,'C0','Capability recovery');
INSERT INTO capability(id,category_code,name) VALUES (13,'C0','Capability retirement');
INSERT INTO capability(id,category_code,name) VALUES (14,'C1','Vision');
INSERT INTO capability(id,category_code,name) VALUES (15,'C1','Hearing');
INSERT INTO capability(id,category_code,name) VALUES (16,'C1','Touch');
INSERT INTO capability(id,category_code,name) VALUES (17,'C1','Smell');
INSERT INTO capability(id,category_code,name) VALUES (18,'C1','Taste');
INSERT INTO capability(id,category_code,name) VALUES (19,'C1','Spatial perception');
INSERT INTO capability(id,category_code,name) VALUES (20,'C1','Temporal perception');
INSERT INTO capability(id,category_code,name) VALUES (21,'C1','Pattern detection');
INSERT INTO capability(id,category_code,name) VALUES (22,'C1','Anomaly detection');
INSERT INTO capability(id,category_code,name) VALUES (23,'C1','Environmental sensing');
INSERT INTO capability(id,category_code,name) VALUES (24,'C1','Multimodal perception');
INSERT INTO capability(id,category_code,name) VALUES (25,'C1','Remote sensing');
INSERT INTO capability(id,category_code,name) VALUES (26,'C1','Signal detection');
INSERT INTO capability(id,category_code,name) VALUES (27,'C2','Reasoning');
INSERT INTO capability(id,category_code,name) VALUES (28,'C2','Abstraction');
INSERT INTO capability(id,category_code,name) VALUES (29,'C2','Categorization');
INSERT INTO capability(id,category_code,name) VALUES (30,'C2','Comparison');
INSERT INTO capability(id,category_code,name) VALUES (31,'C2','Analysis');
INSERT INTO capability(id,category_code,name) VALUES (32,'C2','Synthesis');
INSERT INTO capability(id,category_code,name) VALUES (33,'C2','Inference');
INSERT INTO capability(id,category_code,name) VALUES (34,'C2','Deduction');
INSERT INTO capability(id,category_code,name) VALUES (35,'C2','Induction');
INSERT INTO capability(id,category_code,name) VALUES (36,'C2','Analogical reasoning');
INSERT INTO capability(id,category_code,name) VALUES (37,'C2','Causal reasoning');
INSERT INTO capability(id,category_code,name) VALUES (38,'C2','Counterfactual reasoning');
INSERT INTO capability(id,category_code,name) VALUES (39,'C2','Systems thinking');
INSERT INTO capability(id,category_code,name) VALUES (40,'C2','Metacognition');
INSERT INTO capability(id,category_code,name) VALUES (41,'C3','Information retention');
INSERT INTO capability(id,category_code,name) VALUES (42,'C3','Recall');
INSERT INTO capability(id,category_code,name) VALUES (43,'C3','Recognition');
INSERT INTO capability(id,category_code,name) VALUES (44,'C3','Association');
INSERT INTO capability(id,category_code,name) VALUES (45,'C3','Episodic memory');
INSERT INTO capability(id,category_code,name) VALUES (46,'C3','Semantic memory');
INSERT INTO capability(id,category_code,name) VALUES (47,'C3','Procedural memory');
INSERT INTO capability(id,category_code,name) VALUES (48,'C3','Working memory');
INSERT INTO capability(id,category_code,name) VALUES (49,'C3','Externalized memory');
INSERT INTO capability(id,category_code,name) VALUES (50,'C3','Distributed memory');
INSERT INTO capability(id,category_code,name) VALUES (51,'C3','Memory reconstruction');
INSERT INTO capability(id,category_code,name) VALUES (52,'C3','Memory verification');
INSERT INTO capability(id,category_code,name) VALUES (53,'C4','Learning');
INSERT INTO capability(id,category_code,name) VALUES (54,'C4','Self-learning');
INSERT INTO capability(id,category_code,name) VALUES (55,'C4','Reinforcement learning');
INSERT INTO capability(id,category_code,name) VALUES (56,'C4','Supervised learning');
INSERT INTO capability(id,category_code,name) VALUES (57,'C4','Unsupervised learning');
INSERT INTO capability(id,category_code,name) VALUES (58,'C4','Transfer learning');
INSERT INTO capability(id,category_code,name) VALUES (59,'C4','Few-shot learning');
INSERT INTO capability(id,category_code,name) VALUES (60,'C4','Continuous learning');
INSERT INTO capability(id,category_code,name) VALUES (61,'C4','Adaptive learning');
INSERT INTO capability(id,category_code,name) VALUES (62,'C4','Learning from failure');
INSERT INTO capability(id,category_code,name) VALUES (63,'C4','Learning from observation');
INSERT INTO capability(id,category_code,name) VALUES (64,'C4','Learning from other agents');
INSERT INTO capability(id,category_code,name) VALUES (65,'C5','Generation');
INSERT INTO capability(id,category_code,name) VALUES (66,'C5','Ideation');
INSERT INTO capability(id,category_code,name) VALUES (67,'C5','Design');
INSERT INTO capability(id,category_code,name) VALUES (68,'C5','Invention');
INSERT INTO capability(id,category_code,name) VALUES (69,'C5','Composition');
INSERT INTO capability(id,category_code,name) VALUES (70,'C5','Improvisation');
INSERT INTO capability(id,category_code,name) VALUES (71,'C5','Transformation');
INSERT INTO capability(id,category_code,name) VALUES (72,'C5','Novel combination');
INSERT INTO capability(id,category_code,name) VALUES (73,'C5','Concept generation');
INSERT INTO capability(id,category_code,name) VALUES (74,'C5','Artistic creation');
INSERT INTO capability(id,category_code,name) VALUES (75,'C5','Scientific hypothesis generation');
INSERT INTO capability(id,category_code,name) VALUES (76,'C5','Engineering invention');
INSERT INTO capability(id,category_code,name) VALUES (77,'C6','Speech');
INSERT INTO capability(id,category_code,name) VALUES (78,'C6','Writing');
INSERT INTO capability(id,category_code,name) VALUES (79,'C6','Reading');
INSERT INTO capability(id,category_code,name) VALUES (80,'C6','Translation');
INSERT INTO capability(id,category_code,name) VALUES (81,'C6','Interpretation');
INSERT INTO capability(id,category_code,name) VALUES (82,'C6','Symbolic communication');
INSERT INTO capability(id,category_code,name) VALUES (83,'C6','Mathematical communication');
INSERT INTO capability(id,category_code,name) VALUES (84,'C6','Visual communication');
INSERT INTO capability(id,category_code,name) VALUES (85,'C6','Multimodal communication');
INSERT INTO capability(id,category_code,name) VALUES (86,'C6','Machine communication');
INSERT INTO capability(id,category_code,name) VALUES (87,'C6','Agent-to-agent communication');
INSERT INTO capability(id,category_code,name) VALUES (88,'C6','Protocol negotiation');
INSERT INTO capability(id,category_code,name) VALUES (89,'C7','Problem identification');
INSERT INTO capability(id,category_code,name) VALUES (90,'C7','Problem decomposition');
INSERT INTO capability(id,category_code,name) VALUES (91,'C7','Root-cause analysis');
INSERT INTO capability(id,category_code,name) VALUES (92,'C7','Constraint analysis');
INSERT INTO capability(id,category_code,name) VALUES (93,'C7','Solution generation');
INSERT INTO capability(id,category_code,name) VALUES (94,'C7','Optimization');
INSERT INTO capability(id,category_code,name) VALUES (95,'C7','Troubleshooting');
INSERT INTO capability(id,category_code,name) VALUES (96,'C7','Experimentation');
INSERT INTO capability(id,category_code,name) VALUES (97,'C7','Verification');
INSERT INTO capability(id,category_code,name) VALUES (98,'C7','Recovery');
INSERT INTO capability(id,category_code,name) VALUES (99,'C7','Novel problem solving');
INSERT INTO capability(id,category_code,name) VALUES (100,'C8','Option generation');
INSERT INTO capability(id,category_code,name) VALUES (101,'C8','Risk analysis');
INSERT INTO capability(id,category_code,name) VALUES (102,'C8','Cost-benefit analysis');
INSERT INTO capability(id,category_code,name) VALUES (103,'C8','Uncertainty management');
INSERT INTO capability(id,category_code,name) VALUES (104,'C8','Prioritization');
INSERT INTO capability(id,category_code,name) VALUES (105,'C8','Planning');
INSERT INTO capability(id,category_code,name) VALUES (106,'C8','Resource allocation');
INSERT INTO capability(id,category_code,name) VALUES (107,'C8','Decision execution');
INSERT INTO capability(id,category_code,name) VALUES (108,'C8','Decision revision');
INSERT INTO capability(id,category_code,name) VALUES (109,'C8','Contingency planning');
INSERT INTO capability(id,category_code,name) VALUES (110,'C9','Physical action');
INSERT INTO capability(id,category_code,name) VALUES (111,'C9','Digital action');
INSERT INTO capability(id,category_code,name) VALUES (112,'C9','Tool use');
INSERT INTO capability(id,category_code,name) VALUES (113,'C9','Automation');
INSERT INTO capability(id,category_code,name) VALUES (114,'C9','Coordination');
INSERT INTO capability(id,category_code,name) VALUES (115,'C9','Construction');
INSERT INTO capability(id,category_code,name) VALUES (116,'C9','Modification');
INSERT INTO capability(id,category_code,name) VALUES (117,'C9','Deployment');
INSERT INTO capability(id,category_code,name) VALUES (118,'C9','Operation');
INSERT INTO capability(id,category_code,name) VALUES (119,'C9','Maintenance');
INSERT INTO capability(id,category_code,name) VALUES (120,'C9','Recovery');
INSERT INTO capability(id,category_code,name) VALUES (121,'C10','Computing');
INSERT INTO capability(id,category_code,name) VALUES (122,'C10','Programming');
INSERT INTO capability(id,category_code,name) VALUES (123,'C10','Engineering');
INSERT INTO capability(id,category_code,name) VALUES (124,'C10','Robotics');
INSERT INTO capability(id,category_code,name) VALUES (125,'C10','Electronics');
INSERT INTO capability(id,category_code,name) VALUES (126,'C10','Manufacturing');
INSERT INTO capability(id,category_code,name) VALUES (127,'C10','Biotechnology');
INSERT INTO capability(id,category_code,name) VALUES (128,'C10','Materials science');
INSERT INTO capability(id,category_code,name) VALUES (129,'C10','Cybersecurity');
INSERT INTO capability(id,category_code,name) VALUES (130,'C10','Infrastructure management');
INSERT INTO capability(id,category_code,name) VALUES (131,'C10','Scientific instrumentation');
INSERT INTO capability(id,category_code,name) VALUES (132,'C11','Cooperation');
INSERT INTO capability(id,category_code,name) VALUES (133,'C11','Negotiation');
INSERT INTO capability(id,category_code,name) VALUES (134,'C11','Coordination');
INSERT INTO capability(id,category_code,name) VALUES (135,'C11','Leadership');
INSERT INTO capability(id,category_code,name) VALUES (136,'C11','Teaching');
INSERT INTO capability(id,category_code,name) VALUES (137,'C11','Mentoring');
INSERT INTO capability(id,category_code,name) VALUES (138,'C11','Team formation');
INSERT INTO capability(id,category_code,name) VALUES (139,'C11','Collective decision-making');
INSERT INTO capability(id,category_code,name) VALUES (140,'C11','Conflict resolution');
INSERT INTO capability(id,category_code,name) VALUES (141,'C11','Knowledge sharing');
INSERT INTO capability(id,category_code,name) VALUES (142,'C11','Network formation');
INSERT INTO capability(id,category_code,name) VALUES (143,'C12','Independent operation');
INSERT INTO capability(id,category_code,name) VALUES (144,'C12','Goal pursuit');
INSERT INTO capability(id,category_code,name) VALUES (145,'C12','Self-monitoring');
INSERT INTO capability(id,category_code,name) VALUES (146,'C12','Self-correction');
INSERT INTO capability(id,category_code,name) VALUES (147,'C12','Self-maintenance');
INSERT INTO capability(id,category_code,name) VALUES (148,'C12','Resource acquisition');
INSERT INTO capability(id,category_code,name) VALUES (149,'C12','Planning');
INSERT INTO capability(id,category_code,name) VALUES (150,'C12','Environmental adaptation');
INSERT INTO capability(id,category_code,name) VALUES (151,'C12','Error recovery');
INSERT INTO capability(id,category_code,name) VALUES (152,'C12','Task persistence');
INSERT INTO capability(id,category_code,name) VALUES (153,'C13','Environmental adaptation');
INSERT INTO capability(id,category_code,name) VALUES (154,'C13','Behavioral adaptation');
INSERT INTO capability(id,category_code,name) VALUES (155,'C13','Strategy adaptation');
INSERT INTO capability(id,category_code,name) VALUES (156,'C13','Model adaptation');
INSERT INTO capability(id,category_code,name) VALUES (157,'C13','Structural adaptation');
INSERT INTO capability(id,category_code,name) VALUES (158,'C13','Self-optimization');
INSERT INTO capability(id,category_code,name) VALUES (159,'C13','Failure adaptation');
INSERT INTO capability(id,category_code,name) VALUES (160,'C13','Threat adaptation');
INSERT INTO capability(id,category_code,name) VALUES (161,'C13','Novel-environment adaptation');
INSERT INTO capability(id,category_code,name) VALUES (162,'C14','System modeling');
INSERT INTO capability(id,category_code,name) VALUES (163,'C14','System integration');
INSERT INTO capability(id,category_code,name) VALUES (164,'C14','System orchestration');
INSERT INTO capability(id,category_code,name) VALUES (165,'C14','Network management');
INSERT INTO capability(id,category_code,name) VALUES (166,'C14','Feedback control');
INSERT INTO capability(id,category_code,name) VALUES (167,'C14','Emergence management');
INSERT INTO capability(id,category_code,name) VALUES (168,'C14','Dependency management');
INSERT INTO capability(id,category_code,name) VALUES (169,'C14','Multi-agent coordination');
INSERT INTO capability(id,category_code,name) VALUES (170,'C14','Complex-system optimization');
INSERT INTO capability(id,category_code,name) VALUES (171,'C15','Historical analysis');
INSERT INTO capability(id,category_code,name) VALUES (172,'C15','Real-time response');
INSERT INTO capability(id,category_code,name) VALUES (173,'C15','Temporal modeling');
INSERT INTO capability(id,category_code,name) VALUES (174,'C15','Forecasting');
INSERT INTO capability(id,category_code,name) VALUES (175,'C15','Scenario generation');
INSERT INTO capability(id,category_code,name) VALUES (176,'C15','Long-term planning');
INSERT INTO capability(id,category_code,name) VALUES (177,'C15','Event sequencing');
INSERT INTO capability(id,category_code,name) VALUES (178,'C15','Trend detection');
INSERT INTO capability(id,category_code,name) VALUES (179,'C15','Change detection');
INSERT INTO capability(id,category_code,name) VALUES (180,'C16','Navigation');
INSERT INTO capability(id,category_code,name) VALUES (181,'C16','Mapping');
INSERT INTO capability(id,category_code,name) VALUES (182,'C16','Localization');
INSERT INTO capability(id,category_code,name) VALUES (183,'C16','Spatial modeling');
INSERT INTO capability(id,category_code,name) VALUES (184,'C16','3D reconstruction');
INSERT INTO capability(id,category_code,name) VALUES (185,'C16','Geometric reasoning');
INSERT INTO capability(id,category_code,name) VALUES (186,'C16','Environmental modeling');
INSERT INTO capability(id,category_code,name) VALUES (187,'C16','Spatial optimization');
INSERT INTO capability(id,category_code,name) VALUES (188,'C17','Resource detection');
INSERT INTO capability(id,category_code,name) VALUES (189,'C17','Resource allocation');
INSERT INTO capability(id,category_code,name) VALUES (190,'C17','Resource optimization');
INSERT INTO capability(id,category_code,name) VALUES (191,'C17','Energy management');
INSERT INTO capability(id,category_code,name) VALUES (192,'C17','Material management');
INSERT INTO capability(id,category_code,name) VALUES (193,'C17','Information management');
INSERT INTO capability(id,category_code,name) VALUES (194,'C17','Computational resource management');
INSERT INTO capability(id,category_code,name) VALUES (195,'C17','Ecological resource management');
INSERT INTO capability(id,category_code,name) VALUES (196,'C18','Threat detection');
INSERT INTO capability(id,category_code,name) VALUES (197,'C18','Threat analysis');
INSERT INTO capability(id,category_code,name) VALUES (198,'C18','Prevention');
INSERT INTO capability(id,category_code,name) VALUES (199,'C18','Protection');
INSERT INTO capability(id,category_code,name) VALUES (200,'C18','Authentication');
INSERT INTO capability(id,category_code,name) VALUES (201,'C18','Integrity preservation');
INSERT INTO capability(id,category_code,name) VALUES (202,'C18','Fault tolerance');
INSERT INTO capability(id,category_code,name) VALUES (203,'C18','Recovery');
INSERT INTO capability(id,category_code,name) VALUES (204,'C18','Redundancy');
INSERT INTO capability(id,category_code,name) VALUES (205,'C18','Containment');
INSERT INTO capability(id,category_code,name) VALUES (206,'C18','Resilience');
INSERT INTO capability(id,category_code,name) VALUES (207,'C19','Harm assessment');
INSERT INTO capability(id,category_code,name) VALUES (208,'C19','Consent recognition');
INSERT INTO capability(id,category_code,name) VALUES (209,'C19','Rights recognition');
INSERT INTO capability(id,category_code,name) VALUES (210,'C19','Responsibility tracking');
INSERT INTO capability(id,category_code,name) VALUES (211,'C19','Impact assessment');
INSERT INTO capability(id,category_code,name) VALUES (212,'C19','Reversibility assessment');
INSERT INTO capability(id,category_code,name) VALUES (213,'C19','Stewardship');
INSERT INTO capability(id,category_code,name) VALUES (214,'C19','Preservation');
INSERT INTO capability(id,category_code,name) VALUES (215,'C19','Resource sustainability');
INSERT INTO capability(id,category_code,name) VALUES (216,'C19','Intergenerational consideration');
INSERT INTO capability(id,category_code,name) VALUES (217,'C19','Life-preservation');
INSERT INTO capability(id,category_code,name) VALUES (218,'C19','Coexistence management');
INSERT INTO super_capability(code,name,note) VALUES ('SC-01','Super perception','Integrates sensing and interpretation. Not possessed here.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-02','Super cognition','Integrates reasoning, abstraction, memory, learning, and synthesis.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-03','Super learning','Integrates information into new capabilities. Not seeded as possessed.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-04','Super creativity','Novel solutions. Novel is not verified.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-05','Super problem solving','Decompose, model, solve, test, revise.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-06','Super adaptation','Modify strategy, behavior, or architecture when conditions change.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-07','Super communication','Translate across languages, modalities, domains, and agent types.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-08','Super coordination','Coordinate agents, processes, tools, and resources.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-09','Super autonomy','Complex sequences with limited intervention. Still requires authorization.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-10','Super systems intelligence','Model interactions among systems. Not a built civilization model.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-11','Super simulation','Evaluate scenarios before acting. A fixture is not a twin.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-12','Super verification','Test outputs, assumptions, evidence, and processes.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-13','Super engineering','Design, construct, test, optimize, maintain.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-14','Super security','Detect, prevent, contain, recover, learn.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-15','Super stewardship','Long-term viability and coexistence.');
INSERT INTO super_capability(code,name,note) VALUES ('SC-16','Super integration','Combine heterogeneous parts. Combination is not a running system.');
INSERT INTO power_family(code,name,note) VALUES ('P1','Cognitive','Range of internal processing. Not possessed.');
INSERT INTO power_family(code,name,note) VALUES ('P2','Informational','Scale of information effect. Not a live index.');
INSERT INTO power_family(code,name,note) VALUES ('P3','Computational','Scale of computation. No cluster attached.');
INSERT INTO power_family(code,name,note) VALUES ('P4','Creative','Generative effect. A generation is not a discovery.');
INSERT INTO power_family(code,name,note) VALUES ('P5','Technological','Effect through technology. Named, not deployed.');
INSERT INTO power_family(code,name,note) VALUES ('P6','Physical','Tied to a mechanism. Not supernatural.');
INSERT INTO power_family(code,name,note) VALUES ('P7','Collective','Produced by many entities. Can belong to a system.');
INSERT INTO power_family(code,name,note) VALUES ('P8','Transformative','Can change a system. Safeguards required. Not enabled.');
INSERT INTO power(id,family_code,name) VALUES (1,'P1','Extreme reasoning');
INSERT INTO power(id,family_code,name) VALUES (2,'P1','Extreme memory');
INSERT INTO power(id,family_code,name) VALUES (3,'P1','Accelerated learning');
INSERT INTO power(id,family_code,name) VALUES (4,'P1','Parallel cognition');
INSERT INTO power(id,family_code,name) VALUES (5,'P1','Cross-domain synthesis');
INSERT INTO power(id,family_code,name) VALUES (6,'P1','Advanced abstraction');
INSERT INTO power(id,family_code,name) VALUES (7,'P1','Metacognitive monitoring');
INSERT INTO power(id,family_code,name) VALUES (8,'P1','Complex-system comprehension');
INSERT INTO power(id,family_code,name) VALUES (9,'P2','Massive information integration');
INSERT INTO power(id,family_code,name) VALUES (10,'P2','Real-time information processing');
INSERT INTO power(id,family_code,name) VALUES (11,'P2','Universal-format interpretation');
INSERT INTO power(id,family_code,name) VALUES (12,'P2','Translation across communication systems');
INSERT INTO power(id,family_code,name) VALUES (13,'P2','Knowledge graph construction');
INSERT INTO power(id,family_code,name) VALUES (14,'P2','Distributed information synthesis');
INSERT INTO power(id,family_code,name) VALUES (15,'P2','Provenance reconstruction');
INSERT INTO power(id,family_code,name) VALUES (16,'P3','Massive computation');
INSERT INTO power(id,family_code,name) VALUES (17,'P3','Distributed computation');
INSERT INTO power(id,family_code,name) VALUES (18,'P3','Parallel simulation');
INSERT INTO power(id,family_code,name) VALUES (19,'P3','Optimization at scale');
INSERT INTO power(id,family_code,name) VALUES (20,'P3','Real-time modeling');
INSERT INTO power(id,family_code,name) VALUES (21,'P3','Automated theorem proving');
INSERT INTO power(id,family_code,name) VALUES (22,'P3','Large-scale search');
INSERT INTO power(id,family_code,name) VALUES (23,'P4','Generative invention');
INSERT INTO power(id,family_code,name) VALUES (24,'P4','Automated design');
INSERT INTO power(id,family_code,name) VALUES (25,'P4','Multimodal creation');
INSERT INTO power(id,family_code,name) VALUES (26,'P4','Scientific hypothesis generation');
INSERT INTO power(id,family_code,name) VALUES (27,'P4','Engineering synthesis');
INSERT INTO power(id,family_code,name) VALUES (28,'P4','Artistic generation');
INSERT INTO power(id,family_code,name) VALUES (29,'P4','Novel solution discovery');
INSERT INTO power(id,family_code,name) VALUES (30,'P5','Robotics');
INSERT INTO power(id,family_code,name) VALUES (31,'P5','Autonomous manufacturing');
INSERT INTO power(id,family_code,name) VALUES (32,'P5','Advanced automation');
INSERT INTO power(id,family_code,name) VALUES (33,'P5','Infrastructure control');
INSERT INTO power(id,family_code,name) VALUES (34,'P5','Human-machine integration');
INSERT INTO power(id,family_code,name) VALUES (35,'P5','Machine orchestration');
INSERT INTO power(id,family_code,name) VALUES (36,'P5','Adaptive software and hardware systems');
INSERT INTO power(id,family_code,name) VALUES (37,'P6','Enhanced strength');
INSERT INTO power(id,family_code,name) VALUES (38,'P6','Enhanced speed');
INSERT INTO power(id,family_code,name) VALUES (39,'P6','Enhanced endurance');
INSERT INTO power(id,family_code,name) VALUES (40,'P6','Enhanced precision');
INSERT INTO power(id,family_code,name) VALUES (41,'P6','Enhanced perception');
INSERT INTO power(id,family_code,name) VALUES (42,'P6','Environmental tolerance');
INSERT INTO power(id,family_code,name) VALUES (43,'P6','Autonomous locomotion');
INSERT INTO power(id,family_code,name) VALUES (44,'P6','Advanced manipulation');
INSERT INTO power(id,family_code,name) VALUES (45,'P7','Swarm intelligence');
INSERT INTO power(id,family_code,name) VALUES (46,'P7','Collective computation');
INSERT INTO power(id,family_code,name) VALUES (47,'P7','Distributed sensing');
INSERT INTO power(id,family_code,name) VALUES (48,'P7','Distributed memory');
INSERT INTO power(id,family_code,name) VALUES (49,'P7','Collective problem solving');
INSERT INTO power(id,family_code,name) VALUES (50,'P7','Network intelligence');
INSERT INTO power(id,family_code,name) VALUES (51,'P7','Mass coordination');
INSERT INTO power(id,family_code,name) VALUES (52,'P7','Collective creation');
INSERT INTO power(id,family_code,name) VALUES (53,'P8','Self-reconfiguration');
INSERT INTO power(id,family_code,name) VALUES (54,'P8','System transformation');
INSERT INTO power(id,family_code,name) VALUES (55,'P8','Capability generation');
INSERT INTO power(id,family_code,name) VALUES (56,'P8','Capability transfer');
INSERT INTO power(id,family_code,name) VALUES (57,'P8','Ecosystem restoration');
INSERT INTO power(id,family_code,name) VALUES (58,'P8','Infrastructure transformation');
INSERT INTO power(id,family_code,name) VALUES (59,'P8','Knowledge transformation');
INSERT INTO power(id,family_code,name) VALUES (60,'P8','Organizational transformation');
INSERT INTO power(id,family_code,name) VALUES (61,'P8','Technology transformation');
INSERT INTO power_state(name,position) VALUES ('Conceptual',1);
INSERT INTO power_state(name,position) VALUES ('Theoretically possible',2);
INSERT INTO power_state(name,position) VALUES ('Feasible',3);
INSERT INTO power_state(name,position) VALUES ('Prototyped',4);
INSERT INTO power_state(name,position) VALUES ('Demonstrated',5);
INSERT INTO power_state(name,position) VALUES ('Tested',6);
INSERT INTO power_state(name,position) VALUES ('Verified',7);
INSERT INTO power_state(name,position) VALUES ('Operational',8);
INSERT INTO power_state(name,position) VALUES ('Reliable',9);
INSERT INTO power_state(name,position) VALUES ('Adaptive',10);
INSERT INTO power_state(name,position) VALUES ('Generalized',11);
INSERT INTO agent_class(name,note) VALUES ('human','No capability is assumed.');
INSERT INTO agent_class(name,note) VALUES ('animal','No capability is assumed.');
INSERT INTO agent_class(name,note) VALUES ('organization','A power can belong to a system.');
INSERT INTO agent_class(name,note) VALUES ('ai','No consciousness, personhood, or moral agency is assumed.');
INSERT INTO agent_class(name,note) VALUES ('si','No consciousness is assumed. Criteria required.');
INSERT INTO agent_class(name,note) VALUES ('machine','Limited by mechanism.');
INSERT INTO agent_class(name,note) VALUES ('biological','Limited by the organism.');
INSERT INTO agent_class(name,note) VALUES ('hybrid','No capability is assumed from the label.');
INSERT INTO constraint_kind(name,question) VALUES ('permitted','What may be done.');
INSERT INTO constraint_kind(name,question) VALUES ('required','What must be done.');
INSERT INTO constraint_kind(name,question) VALUES ('unable','What cannot be done.');
INSERT INTO constraint_kind(name,question) VALUES ('forbidden','What must not be done.');
INSERT INTO constraint_kind(name,question) VALUES ('authorization','Who allowed the action.');
INSERT INTO constraint_kind(name,question) VALUES ('safety','What harm bound applies.');
INSERT INTO constraint_kind(name,question) VALUES ('reversibility','Whether the effect can be undone.');
INSERT INTO constraint_kind(name,question) VALUES ('evidence','Why the chain is believed.');
INSERT INTO chain_step(position,name,direction) VALUES (1,'subject','forward');
INSERT INTO chain_step(position,name,direction) VALUES (2,'knowledge','forward');
INSERT INTO chain_step(position,name,direction) VALUES (3,'super-knowledge','forward');
INSERT INTO chain_step(position,name,direction) VALUES (4,'skills','forward');
INSERT INTO chain_step(position,name,direction) VALUES (5,'super-skills','forward');
INSERT INTO chain_step(position,name,direction) VALUES (6,'capabilities','forward');
INSERT INTO chain_step(position,name,direction) VALUES (7,'super-capabilities','forward');
INSERT INTO chain_step(position,name,direction) VALUES (8,'powers','forward');
INSERT INTO chain_step(position,name,direction) VALUES (9,'super-powers','forward');
INSERT INTO chain_step(position,name,direction) VALUES (10,'constraints','forward');
INSERT INTO chain_step(position,name,direction) VALUES (11,'authorization','forward');
INSERT INTO chain_step(position,name,direction) VALUES (12,'action','forward');
INSERT INTO chain_step(position,name,direction) VALUES (13,'effect','forward');
INSERT INTO chain_step(position,name,direction) VALUES (14,'observation','forward');
INSERT INTO chain_step(position,name,direction) VALUES (15,'evidence','forward');
INSERT INTO chain_step(position,name,direction) VALUES (16,'verification','forward');
INSERT INTO chain_step(position,name,direction) VALUES (17,'learning','forward');
INSERT INTO chain_step(position,name,direction) VALUES (18,'adaptation','forward');
INSERT INTO rule(name,statement) VALUES ('potential-is-not-demonstrated','Possessing the potential for something is not demonstrating it.');
INSERT INTO rule(name,statement) VALUES ('capability-is-not-power','A capability is potential action. A power is consequential capacity to produce effects.');
INSERT INTO rule(name,statement) VALUES ('autonomy-is-not-consciousness','Autonomy does not imply consciousness, personhood, or moral agency.');
INSERT INTO rule(name,statement) VALUES ('physical-needs-mechanism','A physical power stays tied to a mechanism. It is not supernatural.');
INSERT INTO rule(name,statement) VALUES ('chain-needs-provenance','An effect must be traceable to action, power, capability, skill, knowledge, and evidence.');
COMMIT;
