BEGIN TRANSACTION;
INSERT INTO skill_category(code,name,note,position) VALUES ('S0','Meta-skills','Skills for managing skills. Sits above the others because every skill can be learned, evaluated, decomposed, and improved.',0);
INSERT INTO skill_category(code,name,note,position) VALUES ('S1','Perception','Acquire information from an environment or source.',1);
INSERT INTO skill_category(code,name,note,position) VALUES ('S2','Attention','Select what deserves processing. Access is not attention.',2);
INSERT INTO skill_category(code,name,note,position) VALUES ('S3','Memory','Retain and retrieve. Memory is coupled to provenance.',3);
INSERT INTO skill_category(code,name,note,position) VALUES ('S4','Learning','Acquire or modify capability.',4);
INSERT INTO skill_category(code,name,note,position) VALUES ('S5','Reasoning','Derive or evaluate conclusions.',5);
INSERT INTO skill_category(code,name,note,position) VALUES ('S6','Communication','Transmit and receive meaning. Not the same as language knowledge.',6);
INSERT INTO skill_category(code,name,note,position) VALUES ('S7','Language','Manipulate linguistic systems.',7);
INSERT INTO skill_category(code,name,note,position) VALUES ('S8','Creative skills','Generate structures. Novelty is not usefulness.',8);
INSERT INTO skill_category(code,name,note,position) VALUES ('S9','Problem solving','Transform a problematic state into an acceptable state.',9);
INSERT INTO skill_category(code,name,note,position) VALUES ('S10','Decision and judgment','Select among alternatives. A decision is not a prediction.',10);
INSERT INTO skill_category(code,name,note,position) VALUES ('S11','Planning','Construct paths toward objectives.',11);
INSERT INTO skill_category(code,name,note,position) VALUES ('S12','Execution','Perform an intended operation. Knowing is not doing.',12);
INSERT INTO skill_category(code,name,note,position) VALUES ('S13','Technical skills','Engineered systems.',13);
INSERT INTO skill_category(code,name,note,position) VALUES ('S14','Scientific and investigative skills','Discover and validate knowledge.',14);
INSERT INTO skill_category(code,name,note,position) VALUES ('S15','Mathematical and computational skills','Formal and numerical operations.',15);
INSERT INTO skill_category(code,name,note,position) VALUES ('S16','Social skills','Interact with other agents. Does not imply emotion or consciousness.',16);
INSERT INTO skill_category(code,name,note,position) VALUES ('S17','Ethical and responsibility skills','Consent, harm, reversibility, and human escalation.',17);
INSERT INTO skill_category(code,name,note,position) VALUES ('S18','Self-management','Manage own operation. Does not assume subjective experience.',18);
INSERT INTO skill_category(code,name,note,position) VALUES ('S19','Physical and embodied skills','Physical interaction. SI embodiment is only what is available.',19);
INSERT INTO skill_category(code,name,note,position) VALUES ('S20','Resource and environment management','Stewardship as an operation, not only a value.',20);
INSERT INTO skill_category(code,name,note,position) VALUES ('S21','Governance and coordination','Rules, oversight, and multi-agent coordination.',21);
INSERT INTO skill_category(code,name,note,position) VALUES ('S22','Security and resilience','Threat, integrity, provenance, and recovery.',22);
INSERT INTO skill_category(code,name,note,position) VALUES ('S23','Teaching and knowledge transfer','Transfer without corrupting.',23);
INSERT INTO skill_category(code,name,note,position) VALUES ('S24','Adaptation and evolution','Change in response to circumstances.',24);
INSERT INTO skill_category(code,name,note,position) VALUES ('S25','Integration and synthesis','Combine capabilities across domains. A combination is not yet a new truth.',25);
INSERT INTO skill(id,name) VALUES (1,'Learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (1,'S0');
INSERT INTO skill(id,name) VALUES (2,'Skill acquisition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (2,'S0');
INSERT INTO skill(id,name) VALUES (3,'Practice');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (3,'S0');
INSERT INTO skill(id,name) VALUES (4,'Deliberate practice');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (4,'S0');
INSERT INTO skill(id,name) VALUES (5,'Self-assessment');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (5,'S0');
INSERT INTO skill(id,name) VALUES (6,'Metacognition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (6,'S0');
INSERT INTO skill(id,name) VALUES (7,'Error recognition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (7,'S0');
INSERT INTO skill(id,name) VALUES (8,'Error correction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (8,'S0');
INSERT INTO skill(id,name) VALUES (9,'Calibration');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (9,'S0');
INSERT INTO skill(id,name) VALUES (10,'Adaptation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (10,'S0');
INSERT INTO skill(id,name) VALUES (11,'Transfer learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (11,'S0');
INSERT INTO skill(id,name) VALUES (12,'Generalization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (12,'S0');
INSERT INTO skill(id,name) VALUES (13,'Specialization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (13,'S0');
INSERT INTO skill(id,name) VALUES (14,'Skill decomposition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (14,'S0');
INSERT INTO skill(id,name) VALUES (15,'Skill composition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (15,'S0');
INSERT INTO skill(id,name) VALUES (16,'Strategy selection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (16,'S0');
INSERT INTO skill(id,name) VALUES (17,'Planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (17,'S0');
INSERT INTO skill(id,name) VALUES (18,'Reflection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (18,'S0');
INSERT INTO skill(id,name) VALUES (19,'Self-improvement');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (19,'S0');
INSERT INTO skill(id,name) VALUES (20,'Teaching');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (20,'S0');
INSERT INTO skill(id,name) VALUES (21,'Coaching');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (21,'S0');
INSERT INTO skill(id,name) VALUES (22,'Mentoring');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (22,'S0');
INSERT INTO skill(id,name) VALUES (23,'Seeing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (23,'S1');
INSERT INTO skill(id,name) VALUES (24,'Hearing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (24,'S1');
INSERT INTO skill(id,name) VALUES (25,'Touch');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (25,'S1');
INSERT INTO skill(id,name) VALUES (26,'Smell');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (26,'S1');
INSERT INTO skill(id,name) VALUES (27,'Taste');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (27,'S1');
INSERT INTO skill(id,name) VALUES (28,'Spatial perception');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (28,'S1');
INSERT INTO skill(id,name) VALUES (29,'Proprioception');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (29,'S1');
INSERT INTO skill(id,name) VALUES (30,'Interoception');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (30,'S1');
INSERT INTO skill(id,name) VALUES (31,'Computer vision');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (31,'S1');
INSERT INTO skill(id,name) VALUES (32,'Audio processing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (32,'S1');
INSERT INTO skill(id,name) VALUES (33,'Speech recognition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (33,'S1');
INSERT INTO skill(id,name) VALUES (34,'Sensor fusion');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (34,'S1');
INSERT INTO skill(id,name) VALUES (35,'Pattern recognition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (35,'S1');
INSERT INTO skill(id,name) VALUES (36,'Document recognition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (36,'S1');
INSERT INTO skill(id,name) VALUES (37,'Environmental sensing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (37,'S1');
INSERT INTO skill(id,name) VALUES (38,'Data ingestion');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (38,'S1');
INSERT INTO skill(id,name) VALUES (39,'Observation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (39,'S1');
INSERT INTO skill(id,name) VALUES (40,'Detection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (40,'S1');
INSERT INTO skill(id,name) VALUES (41,'Recognition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (41,'S1');
INSERT INTO skill(id,name) VALUES (42,'Classification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (42,'S1');
INSERT INTO skill(id,name) VALUES (43,'Localization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (43,'S1');
INSERT INTO skill(id,name) VALUES (44,'Tracking');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (44,'S1');
INSERT INTO skill(id,name) VALUES (45,'Discrimination');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (45,'S1');
INSERT INTO skill(id,name) VALUES (46,'Anomaly detection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (46,'S1');
INSERT INTO skill(id,name) VALUES (47,'Focus');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (47,'S2');
INSERT INTO skill(id,name) VALUES (48,'Filtering');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (48,'S2');
INSERT INTO skill(id,name) VALUES (49,'Prioritization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (49,'S2');
INSERT INTO skill(id,name) VALUES (50,'Salience detection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (50,'S2');
INSERT INTO skill(id,name) VALUES (51,'Context selection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (51,'S2');
INSERT INTO skill(id,name) VALUES (52,'Attention switching');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (52,'S2');
INSERT INTO skill(id,name) VALUES (53,'Sustained attention');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (53,'S2');
INSERT INTO skill(id,name) VALUES (54,'Divided attention');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (54,'S2');
INSERT INTO skill(id,name) VALUES (55,'Signal extraction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (55,'S2');
INSERT INTO skill(id,name) VALUES (56,'Noise suppression');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (56,'S2');
INSERT INTO skill(id,name) VALUES (57,'Information triage');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (57,'S2');
INSERT INTO skill(id,name) VALUES (58,'Encoding');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (58,'S3');
INSERT INTO skill(id,name) VALUES (59,'Storage');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (59,'S3');
INSERT INTO skill(id,name) VALUES (60,'Retrieval');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (60,'S3');
INSERT INTO skill(id,name) VALUES (61,'Recall');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (61,'S3');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (41,'S3');
INSERT INTO skill(id,name) VALUES (62,'Association');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (62,'S3');
INSERT INTO skill(id,name) VALUES (63,'Indexing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (63,'S3');
INSERT INTO skill(id,name) VALUES (64,'Contextual retrieval');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (64,'S3');
INSERT INTO skill(id,name) VALUES (65,'Episodic memory');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (65,'S3');
INSERT INTO skill(id,name) VALUES (66,'Semantic memory');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (66,'S3');
INSERT INTO skill(id,name) VALUES (67,'Procedural memory');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (67,'S3');
INSERT INTO skill(id,name) VALUES (68,'Working memory');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (68,'S3');
INSERT INTO skill(id,name) VALUES (69,'Long-term memory');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (69,'S3');
INSERT INTO skill(id,name) VALUES (70,'Knowledge consolidation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (70,'S3');
INSERT INTO skill(id,name) VALUES (71,'Forgetting');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (71,'S3');
INSERT INTO skill(id,name) VALUES (72,'Memory validation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (72,'S3');
INSERT INTO skill(id,name) VALUES (73,'Provenance retrieval');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (73,'S3');
INSERT INTO skill(id,name) VALUES (74,'Observation learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (74,'S4');
INSERT INTO skill(id,name) VALUES (75,'Instructional learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (75,'S4');
INSERT INTO skill(id,name) VALUES (76,'Experiential learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (76,'S4');
INSERT INTO skill(id,name) VALUES (77,'Reinforcement learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (77,'S4');
INSERT INTO skill(id,name) VALUES (78,'Supervised learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (78,'S4');
INSERT INTO skill(id,name) VALUES (79,'Unsupervised learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (79,'S4');
INSERT INTO skill(id,name) VALUES (80,'Self-supervised learning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (80,'S4');
INSERT INTO skill(id,name) VALUES (81,'Imitation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (81,'S4');
INSERT INTO skill(id,name) VALUES (82,'Apprenticeship');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (82,'S4');
INSERT INTO skill(id,name) VALUES (83,'Exploration');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (83,'S4');
INSERT INTO skill(id,name) VALUES (84,'Experimentation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (84,'S4');
INSERT INTO skill(id,name) VALUES (85,'Skill refinement');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (85,'S4');
INSERT INTO skill(id,name) VALUES (86,'Knowledge transfer');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (86,'S4');
INSERT INTO skill(id,name) VALUES (87,'Deduction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (87,'S5');
INSERT INTO skill(id,name) VALUES (88,'Induction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (88,'S5');
INSERT INTO skill(id,name) VALUES (89,'Abduction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (89,'S5');
INSERT INTO skill(id,name) VALUES (90,'Analogical reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (90,'S5');
INSERT INTO skill(id,name) VALUES (91,'Causal reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (91,'S5');
INSERT INTO skill(id,name) VALUES (92,'Probabilistic reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (92,'S5');
INSERT INTO skill(id,name) VALUES (93,'Counterfactual reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (93,'S5');
INSERT INTO skill(id,name) VALUES (94,'Spatial reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (94,'S5');
INSERT INTO skill(id,name) VALUES (95,'Temporal reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (95,'S5');
INSERT INTO skill(id,name) VALUES (96,'Mathematical reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (96,'S5');
INSERT INTO skill(id,name) VALUES (97,'Logical reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (97,'S5');
INSERT INTO skill(id,name) VALUES (98,'Systems reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (98,'S5');
INSERT INTO skill(id,name) VALUES (99,'Ethical reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (99,'S5');
INSERT INTO skill(id,name) VALUES (100,'Strategic reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (100,'S5');
INSERT INTO skill(id,name) VALUES (101,'Multi-step reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (101,'S5');
INSERT INTO skill(id,name) VALUES (102,'Constraint reasoning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (102,'S5');
INSERT INTO skill(id,name) VALUES (103,'Speaking');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (103,'S6');
INSERT INTO skill(id,name) VALUES (104,'Writing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (104,'S6');
INSERT INTO skill(id,name) VALUES (105,'Reading');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (105,'S6');
INSERT INTO skill(id,name) VALUES (106,'Listening');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (106,'S6');
INSERT INTO skill(id,name) VALUES (107,'Sign language');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (107,'S6');
INSERT INTO skill(id,name) VALUES (108,'Translation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (108,'S6');
INSERT INTO skill(id,name) VALUES (109,'Interpretation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (109,'S6');
INSERT INTO skill(id,name) VALUES (110,'Explanation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (110,'S6');
INSERT INTO skill(id,name) VALUES (111,'Questioning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (111,'S6');
INSERT INTO skill(id,name) VALUES (112,'Clarification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (112,'S6');
INSERT INTO skill(id,name) VALUES (113,'Negotiation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (113,'S6');
INSERT INTO skill(id,name) VALUES (114,'Presentation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (114,'S6');
INSERT INTO skill(id,name) VALUES (115,'Storytelling');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (115,'S6');
INSERT INTO skill(id,name) VALUES (116,'Dialogue');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (116,'S6');
INSERT INTO skill(id,name) VALUES (117,'Nonverbal communication');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (117,'S6');
INSERT INTO skill(id,name) VALUES (118,'Human-machine communication');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (118,'S6');
INSERT INTO skill(id,name) VALUES (119,'Machine-machine communication');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (119,'S6');
INSERT INTO skill(id,name) VALUES (120,'Persuasion');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (120,'S6');
INSERT INTO skill(id,name) VALUES (121,'Vocabulary acquisition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (121,'S7');
INSERT INTO skill(id,name) VALUES (122,'Grammar');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (122,'S7');
INSERT INTO skill(id,name) VALUES (123,'Syntax');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (123,'S7');
INSERT INTO skill(id,name) VALUES (124,'Semantics');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (124,'S7');
INSERT INTO skill(id,name) VALUES (125,'Pragmatics');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (125,'S7');
INSERT INTO skill(id,name) VALUES (126,'Discourse');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (126,'S7');
INSERT INTO skill(id,name) VALUES (127,'Summarization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (127,'S7');
INSERT INTO skill(id,name) VALUES (128,'Parsing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (128,'S7');
INSERT INTO skill(id,name) VALUES (129,'Generation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (129,'S7');
INSERT INTO skill(id,name) VALUES (130,'Terminology management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (130,'S7');
INSERT INTO skill(id,name) VALUES (131,'Formal language manipulation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (131,'S7');
INSERT INTO skill(id,name) VALUES (132,'Programming-language use');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (132,'S7');
INSERT INTO skill(id,name) VALUES (133,'Multilingual processing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (133,'S7');
INSERT INTO skill(id,name) VALUES (134,'Ideation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (134,'S8');
INSERT INTO skill(id,name) VALUES (135,'Brainstorming');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (135,'S8');
INSERT INTO skill(id,name) VALUES (136,'Composition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (136,'S8');
INSERT INTO skill(id,name) VALUES (137,'Improvisation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (137,'S8');
INSERT INTO skill(id,name) VALUES (138,'Design');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (138,'S8');
INSERT INTO skill(id,name) VALUES (139,'Invention');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (139,'S8');
INSERT INTO skill(id,name) VALUES (140,'Artistic creation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (140,'S8');
INSERT INTO skill(id,name) VALUES (141,'Music creation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (141,'S8');
INSERT INTO skill(id,name) VALUES (142,'Visual creation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (142,'S8');
INSERT INTO skill(id,name) VALUES (143,'Game design');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (143,'S8');
INSERT INTO skill(id,name) VALUES (144,'Problem reframing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (144,'S8');
INSERT INTO skill(id,name) VALUES (145,'Concept synthesis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (145,'S8');
INSERT INTO skill(id,name) VALUES (146,'Novel combination');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (146,'S8');
INSERT INTO skill(id,name) VALUES (147,'Generative exploration');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (147,'S8');
INSERT INTO skill(id,name) VALUES (148,'Problem identification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (148,'S9');
INSERT INTO skill(id,name) VALUES (149,'Problem decomposition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (149,'S9');
INSERT INTO skill(id,name) VALUES (150,'Root-cause analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (150,'S9');
INSERT INTO skill(id,name) VALUES (151,'Constraint identification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (151,'S9');
INSERT INTO skill(id,name) VALUES (152,'Solution generation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (152,'S9');
INSERT INTO skill(id,name) VALUES (153,'Optimization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (153,'S9');
INSERT INTO skill(id,name) VALUES (154,'Troubleshooting');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (154,'S9');
INSERT INTO skill(id,name) VALUES (155,'Debugging');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (155,'S9');
INSERT INTO skill(id,name) VALUES (156,'Repair');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (156,'S9');
INSERT INTO skill(id,name) VALUES (157,'Verification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (157,'S9');
INSERT INTO skill(id,name) VALUES (158,'Validation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (158,'S9');
INSERT INTO skill(id,name) VALUES (159,'Failure analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (159,'S9');
INSERT INTO skill(id,name) VALUES (160,'Recovery');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (160,'S9');
INSERT INTO skill(id,name) VALUES (161,'Option generation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (161,'S10');
INSERT INTO skill(id,name) VALUES (162,'Risk assessment');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (162,'S10');
INSERT INTO skill(id,name) VALUES (163,'Cost-benefit analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (163,'S10');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (49,'S10');
INSERT INTO skill(id,name) VALUES (164,'Uncertainty management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (164,'S10');
INSERT INTO skill(id,name) VALUES (165,'Decision analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (165,'S10');
INSERT INTO skill(id,name) VALUES (166,'Tradeoff analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (166,'S10');
INSERT INTO skill(id,name) VALUES (167,'Resource allocation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (167,'S10');
INSERT INTO skill(id,name) VALUES (168,'Scenario analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (168,'S10');
INSERT INTO skill(id,name) VALUES (169,'Contingency planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (169,'S10');
INSERT INTO skill(id,name) VALUES (170,'Reversibility assessment');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (170,'S10');
INSERT INTO skill(id,name) VALUES (171,'Escalation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (171,'S10');
INSERT INTO skill(id,name) VALUES (172,'Delegation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (172,'S10');
INSERT INTO skill(id,name) VALUES (173,'Goal definition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (173,'S11');
INSERT INTO skill(id,name) VALUES (174,'Requirement analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (174,'S11');
INSERT INTO skill(id,name) VALUES (175,'Task decomposition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (175,'S11');
INSERT INTO skill(id,name) VALUES (176,'Sequencing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (176,'S11');
INSERT INTO skill(id,name) VALUES (177,'Scheduling');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (177,'S11');
INSERT INTO skill(id,name) VALUES (178,'Dependency management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (178,'S11');
INSERT INTO skill(id,name) VALUES (179,'Resource planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (179,'S11');
INSERT INTO skill(id,name) VALUES (180,'Risk planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (180,'S11');
INSERT INTO skill(id,name) VALUES (181,'Milestone creation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (181,'S11');
INSERT INTO skill(id,name) VALUES (182,'Execution planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (182,'S11');
INSERT INTO skill(id,name) VALUES (183,'Long-term planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (183,'S11');
INSERT INTO skill(id,name) VALUES (184,'Strategic planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (184,'S11');
INSERT INTO skill(id,name) VALUES (185,'Task execution');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (185,'S12');
INSERT INTO skill(id,name) VALUES (186,'Tool use');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (186,'S12');
INSERT INTO skill(id,name) VALUES (187,'Procedure following');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (187,'S12');
INSERT INTO skill(id,name) VALUES (188,'Automation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (188,'S12');
INSERT INTO skill(id,name) VALUES (189,'Coordination');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (189,'S12');
INSERT INTO skill(id,name) VALUES (190,'Transaction execution');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (190,'S12');
INSERT INTO skill(id,name) VALUES (191,'Physical manipulation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (191,'S12');
INSERT INTO skill(id,name) VALUES (192,'Computational execution');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (192,'S12');
INSERT INTO skill(id,name) VALUES (193,'Workflow execution');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (193,'S12');
INSERT INTO skill(id,name) VALUES (194,'Monitoring');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (194,'S12');
INSERT INTO skill(id,name) VALUES (195,'Intervention');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (195,'S12');
INSERT INTO skill(id,name) VALUES (196,'Completion verification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (196,'S12');
INSERT INTO skill(id,name) VALUES (197,'Programming');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (197,'S13');
INSERT INTO skill(id,name) VALUES (198,'Software development');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (198,'S13');
INSERT INTO skill(id,name) VALUES (199,'Testing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (199,'S13');
INSERT INTO skill(id,name) VALUES (200,'Systems administration');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (200,'S13');
INSERT INTO skill(id,name) VALUES (201,'Cybersecurity');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (201,'S13');
INSERT INTO skill(id,name) VALUES (202,'Data engineering');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (202,'S13');
INSERT INTO skill(id,name) VALUES (203,'Database management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (203,'S13');
INSERT INTO skill(id,name) VALUES (204,'Networking');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (204,'S13');
INSERT INTO skill(id,name) VALUES (205,'Electronics');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (205,'S13');
INSERT INTO skill(id,name) VALUES (206,'Robotics');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (206,'S13');
INSERT INTO skill(id,name) VALUES (207,'Mechanical engineering');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (207,'S13');
INSERT INTO skill(id,name) VALUES (208,'CAD');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (208,'S13');
INSERT INTO skill(id,name) VALUES (209,'Manufacturing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (209,'S13');
INSERT INTO skill(id,name) VALUES (210,'Construction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (210,'S13');
INSERT INTO skill(id,name) VALUES (211,'AI development');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (211,'S13');
INSERT INTO skill(id,name) VALUES (212,'Model development');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (212,'S13');
INSERT INTO skill(id,name) VALUES (213,'Model evaluation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (213,'S13');
INSERT INTO skill(id,name) VALUES (214,'Measurement');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (214,'S14');
INSERT INTO skill(id,name) VALUES (215,'Experimental design');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (215,'S14');
INSERT INTO skill(id,name) VALUES (216,'Hypothesis formation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (216,'S14');
INSERT INTO skill(id,name) VALUES (217,'Sampling');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (217,'S14');
INSERT INTO skill(id,name) VALUES (218,'Data collection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (218,'S14');
INSERT INTO skill(id,name) VALUES (219,'Statistical analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (219,'S14');
INSERT INTO skill(id,name) VALUES (220,'Modeling');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (220,'S14');
INSERT INTO skill(id,name) VALUES (221,'Simulation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (221,'S14');
INSERT INTO skill(id,name) VALUES (222,'Reproduction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (222,'S14');
INSERT INTO skill(id,name) VALUES (223,'Replication');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (223,'S14');
INSERT INTO skill(id,name) VALUES (224,'Peer review');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (224,'S14');
INSERT INTO skill(id,name) VALUES (225,'Literature review');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (225,'S14');
INSERT INTO skill(id,name) VALUES (226,'Evidence evaluation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (226,'S14');
INSERT INTO skill(id,name) VALUES (227,'Falsification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (227,'S14');
INSERT INTO skill(id,name) VALUES (228,'Documentation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (228,'S14');
INSERT INTO skill(id,name) VALUES (229,'Research synthesis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (229,'S14');
INSERT INTO skill(id,name) VALUES (230,'Calculation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (230,'S15');
INSERT INTO skill(id,name) VALUES (231,'Algebraic manipulation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (231,'S15');
INSERT INTO skill(id,name) VALUES (232,'Geometry');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (232,'S15');
INSERT INTO skill(id,name) VALUES (233,'Calculus');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (233,'S15');
INSERT INTO skill(id,name) VALUES (234,'Statistics');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (234,'S15');
INSERT INTO skill(id,name) VALUES (235,'Probability');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (235,'S15');
INSERT INTO skill(id,name) VALUES (236,'Algorithm design');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (236,'S15');
INSERT INTO skill(id,name) VALUES (237,'Computational complexity analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (237,'S15');
INSERT INTO skill(id,name) VALUES (238,'Formal proof');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (238,'S15');
INSERT INTO skill(id,name) VALUES (239,'Numerical methods');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (239,'S15');
INSERT INTO skill(id,name) VALUES (240,'Data analysis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (240,'S15');
INSERT INTO skill(id,name) VALUES (241,'Cooperation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (241,'S16');
INSERT INTO skill(id,name) VALUES (242,'Collaboration');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (242,'S16');
INSERT INTO skill(id,name) VALUES (243,'Empathy');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (243,'S16');
INSERT INTO skill(id,name) VALUES (244,'Active listening');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (244,'S16');
INSERT INTO skill(id,name) VALUES (245,'Conflict resolution');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (245,'S16');
INSERT INTO skill(id,name) VALUES (246,'Mediation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (246,'S16');
INSERT INTO skill(id,name) VALUES (247,'Leadership');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (247,'S16');
INSERT INTO skill(id,name) VALUES (248,'Followership');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (248,'S16');
INSERT INTO skill(id,name) VALUES (249,'Team coordination');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (249,'S16');
INSERT INTO skill(id,name) VALUES (250,'Relationship building');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (250,'S16');
INSERT INTO skill(id,name) VALUES (251,'Trust building');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (251,'S16');
INSERT INTO skill(id,name) VALUES (252,'Boundary setting');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (252,'S16');
INSERT INTO skill(id,name) VALUES (253,'Consensus building');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (253,'S16');
INSERT INTO skill(id,name) VALUES (254,'Community building');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (254,'S16');
INSERT INTO skill(id,name) VALUES (255,'Consent verification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (255,'S17');
INSERT INTO skill(id,name) VALUES (256,'Harm assessment');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (256,'S17');
INSERT INTO skill(id,name) VALUES (257,'Responsibility tracking');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (257,'S17');
INSERT INTO skill(id,name) VALUES (258,'Accountability');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (258,'S17');
INSERT INTO skill(id,name) VALUES (259,'Transparency');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (259,'S17');
INSERT INTO skill(id,name) VALUES (260,'Disclosure');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (260,'S17');
INSERT INTO skill(id,name) VALUES (261,'Privacy protection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (261,'S17');
INSERT INTO skill(id,name) VALUES (262,'Safety assessment');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (262,'S17');
INSERT INTO skill(id,name) VALUES (263,'Rights recognition');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (263,'S17');
INSERT INTO skill(id,name) VALUES (264,'Conflict-of-interest detection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (264,'S17');
INSERT INTO skill(id,name) VALUES (265,'Stewardship');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (265,'S17');
INSERT INTO skill(id,name) VALUES (266,'Resource responsibility');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (266,'S17');
INSERT INTO skill(id,name) VALUES (267,'Environmental responsibility');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (267,'S17');
INSERT INTO skill(id,name) VALUES (268,'Withdrawal handling');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (268,'S17');
INSERT INTO skill(id,name) VALUES (269,'Escalation to human oversight');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (269,'S17');
INSERT INTO skill(id,name) VALUES (270,'Time management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (270,'S18');
INSERT INTO skill(id,name) VALUES (271,'Organization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (271,'S18');
INSERT INTO skill(id,name) VALUES (272,'Emotional regulation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (272,'S18');
INSERT INTO skill(id,name) VALUES (273,'Goal management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (273,'S18');
INSERT INTO skill(id,name) VALUES (274,'Habit formation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (274,'S18');
INSERT INTO skill(id,name) VALUES (275,'Stress management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (275,'S18');
INSERT INTO skill(id,name) VALUES (276,'Self-care');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (276,'S18');
INSERT INTO skill(id,name) VALUES (277,'Self-monitoring');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (277,'S18');
INSERT INTO skill(id,name) VALUES (278,'Resource management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (278,'S18');
INSERT INTO skill(id,name) VALUES (279,'Process monitoring');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (279,'S18');
INSERT INTO skill(id,name) VALUES (280,'State monitoring');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (280,'S18');
INSERT INTO skill(id,name) VALUES (281,'Error monitoring');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (281,'S18');
INSERT INTO skill(id,name) VALUES (282,'Goal tracking');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (282,'S18');
INSERT INTO skill(id,name) VALUES (283,'Context management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (283,'S18');
INSERT INTO skill(id,name) VALUES (284,'Memory management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (284,'S18');
INSERT INTO skill(id,name) VALUES (285,'Compute management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (285,'S18');
INSERT INTO skill(id,name) VALUES (286,'Self-diagnostics');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (286,'S18');
INSERT INTO skill(id,name) VALUES (287,'System recovery');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (287,'S18');
INSERT INTO skill(id,name) VALUES (288,'Locomotion');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (288,'S19');
INSERT INTO skill(id,name) VALUES (289,'Balance');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (289,'S19');
INSERT INTO skill(id,name) VALUES (290,'Dexterity');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (290,'S19');
INSERT INTO skill(id,name) VALUES (291,'Manipulation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (291,'S19');
INSERT INTO skill(id,name) VALUES (292,'Navigation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (292,'S19');
INSERT INTO skill(id,name) VALUES (293,'Driving');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (293,'S19');
INSERT INTO skill(id,name) VALUES (294,'Flying');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (294,'S19');
INSERT INTO skill(id,name) VALUES (295,'Swimming');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (295,'S19');
INSERT INTO skill(id,name) VALUES (296,'Surgery');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (296,'S19');
INSERT INTO skill(id,name) VALUES (297,'Craftsmanship');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (297,'S19');
INSERT INTO skill(id,name) VALUES (298,'Sports');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (298,'S19');
INSERT INTO skill(id,name) VALUES (299,'Dance');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (299,'S19');
INSERT INTO skill(id,name) VALUES (300,'Robotic manipulation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (300,'S19');
INSERT INTO skill(id,name) VALUES (301,'Autonomous navigation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (301,'S19');
INSERT INTO skill(id,name) VALUES (302,'Sensorimotor control');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (302,'S19');
INSERT INTO skill(id,name) VALUES (303,'Industrial automation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (303,'S19');
INSERT INTO skill(id,name) VALUES (304,'Energy management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (304,'S20');
INSERT INTO skill(id,name) VALUES (305,'Water management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (305,'S20');
INSERT INTO skill(id,name) VALUES (306,'Food production');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (306,'S20');
INSERT INTO skill(id,name) VALUES (307,'Agriculture');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (307,'S20');
INSERT INTO skill(id,name) VALUES (308,'Conservation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (308,'S20');
INSERT INTO skill(id,name) VALUES (309,'Waste management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (309,'S20');
INSERT INTO skill(id,name) VALUES (310,'Environmental monitoring');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (310,'S20');
INSERT INTO skill(id,name) VALUES (311,'Infrastructure management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (311,'S20');
INSERT INTO skill(id,name) VALUES (312,'Ecosystem management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (312,'S20');
INSERT INTO skill(id,name) VALUES (313,'Sustainability');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (313,'S20');
INSERT INTO skill(id,name) VALUES (314,'Disaster response');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (314,'S20');
INSERT INTO skill(id,name) VALUES (315,'Resilience planning');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (315,'S20');
INSERT INTO skill(id,name) VALUES (316,'Policy implementation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (316,'S21');
INSERT INTO skill(id,name) VALUES (317,'Institutional management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (317,'S21');
INSERT INTO skill(id,name) VALUES (318,'Rule interpretation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (318,'S21');
INSERT INTO skill(id,name) VALUES (319,'Compliance');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (319,'S21');
INSERT INTO skill(id,name) VALUES (320,'Auditing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (320,'S21');
INSERT INTO skill(id,name) VALUES (321,'Oversight');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (321,'S21');
INSERT INTO skill(id,name) VALUES (322,'Voting systems');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (322,'S21');
INSERT INTO skill(id,name) VALUES (323,'Consensus mechanisms');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (323,'S21');
INSERT INTO skill(id,name) VALUES (324,'Organizational management');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (324,'S21');
INSERT INTO skill(id,name) VALUES (325,'Multi-agent coordination');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (325,'S21');
INSERT INTO skill(id,name) VALUES (326,'Threat detection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (326,'S22');
INSERT INTO skill(id,name) VALUES (327,'Risk identification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (327,'S22');
INSERT INTO skill(id,name) VALUES (328,'Defensive programming');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (328,'S22');
INSERT INTO skill(id,name) VALUES (329,'Authentication');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (329,'S22');
INSERT INTO skill(id,name) VALUES (330,'Authorization');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (330,'S22');
INSERT INTO skill(id,name) VALUES (331,'Access control');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (331,'S22');
INSERT INTO skill(id,name) VALUES (332,'Incident response');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (332,'S22');
INSERT INTO skill(id,name) VALUES (333,'Fault tolerance');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (333,'S22');
INSERT INTO skill(id,name) VALUES (334,'Redundancy');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (334,'S22');
INSERT INTO skill(id,name) VALUES (335,'Disaster preparedness');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (335,'S22');
INSERT INTO skill(id,name) VALUES (336,'Security auditing');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (336,'S22');
INSERT INTO skill(id,name) VALUES (337,'Integrity verification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (337,'S22');
INSERT INTO skill(id,name) VALUES (338,'Provenance verification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (338,'S22');
INSERT INTO skill(id,name) VALUES (339,'Tamper detection');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (339,'S22');
INSERT INTO skill(id,name) VALUES (340,'Instruction');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (340,'S23');
INSERT INTO skill(id,name) VALUES (341,'Demonstration');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (341,'S23');
INSERT INTO skill(id,name) VALUES (342,'Curriculum design');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (342,'S23');
INSERT INTO skill(id,name) VALUES (343,'Assessment');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (343,'S23');
INSERT INTO skill(id,name) VALUES (344,'Feedback');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (344,'S23');
INSERT INTO skill(id,name) VALUES (345,'Training-system design');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (345,'S23');
INSERT INTO skill(id,name) VALUES (346,'Reconfiguration');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (346,'S24');
INSERT INTO skill(id,name) VALUES (347,'Learning from failure');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (347,'S24');
INSERT INTO skill(id,name) VALUES (348,'Strategy modification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (348,'S24');
INSERT INTO skill(id,name) VALUES (349,'Environmental adaptation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (349,'S24');
INSERT INTO skill(id,name) VALUES (350,'Skill evolution');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (350,'S24');
INSERT INTO skill(id,name) VALUES (351,'System evolution');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (351,'S24');
INSERT INTO skill(id,name) VALUES (352,'Architecture modification');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (352,'S24');
INSERT INTO skill(id,name) VALUES (353,'Continuous improvement');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (353,'S24');
INSERT INTO skill(id,name) VALUES (354,'Innovation');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (354,'S24');
INSERT INTO skill(id,name) VALUES (355,'Cross-domain synthesis');
INSERT INTO skill_category_link(skill_id,category_code) VALUES (355,'S25');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S1','human','Seeing, hearing, touch, smell, taste, spatial, proprioception, interoception.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S1','ai','Computer vision, audio, speech, sensor fusion, document recognition, data ingestion.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S1','si','Only the sensors and feeds this system actually has.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S1','shared','Observation, detection, recognition, classification, localization, tracking, discrimination, anomaly detection.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S16','ai','Capability only. Does not imply emotion or consciousness.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S16','si','Capability only. Does not imply emotion or consciousness.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S18','human','Time, organization, emotion, habit, stress, self-care.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S18','ai','Resource, process, state, error, goal, context, memory, compute, diagnostics, recovery.');
INSERT INTO agent_scope(category_code,agent,note) VALUES ('S19','si','Whatever physical embodiment is actually available. None is assumed.');
INSERT INTO maturity_level(level,name) VALUES (0,'Unknown');
INSERT INTO maturity_level(level,name) VALUES (1,'Aware');
INSERT INTO maturity_level(level,name) VALUES (2,'Exposed');
INSERT INTO maturity_level(level,name) VALUES (3,'Learning');
INSERT INTO maturity_level(level,name) VALUES (4,'Practicing');
INSERT INTO maturity_level(level,name) VALUES (5,'Functional');
INSERT INTO maturity_level(level,name) VALUES (6,'Proficient');
INSERT INTO maturity_level(level,name) VALUES (7,'Advanced');
INSERT INTO maturity_level(level,name) VALUES (8,'Expert');
INSERT INTO maturity_level(level,name) VALUES (9,'Mastery');
INSERT INTO maturity_level(level,name) VALUES (10,'Adaptive');
INSERT INTO distinction(name,note) VALUES ('communication-is-not-language','A system can know a language and still fail to communicate.');
INSERT INTO distinction(name,note) VALUES ('novelty-is-not-usefulness','A new structure is not a useful one.');
INSERT INTO distinction(name,note) VALUES ('decision-is-not-prediction','A choice under uncertainty is not a claim about the future.');
INSERT INTO distinction(name,note) VALUES ('knowing-is-not-doing','A described procedure is not an execution.');
INSERT INTO distinction(name,note) VALUES ('capability-is-not-experience','A social or ethical skill does not imply subjective experience.');
INSERT INTO distinction(name,note) VALUES ('maturity-needs-evidence','A level without a verification record is not a level.');
INSERT INTO learning_loop(position,name) VALUES (1,'know');
INSERT INTO learning_loop(position,name) VALUES (2,'practice');
INSERT INTO learning_loop(position,name) VALUES (3,'act');
INSERT INTO learning_loop(position,name) VALUES (4,'observe');
INSERT INTO learning_loop(position,name) VALUES (5,'evaluate');
INSERT INTO learning_loop(position,name) VALUES (6,'correct');
INSERT INTO learning_loop(position,name) VALUES (7,'learn');
INSERT INTO learning_loop(position,name) VALUES (8,'improve');
INSERT INTO evaluation_dimension(name) VALUES ('accuracy');
INSERT INTO evaluation_dimension(name) VALUES ('reliability');
INSERT INTO evaluation_dimension(name) VALUES ('efficiency');
INSERT INTO evaluation_dimension(name) VALUES ('safety');
INSERT INTO evaluation_dimension(name) VALUES ('reproducibility');
COMMIT;
